### ISSUE TITLE
Hooking text

### ISSUE THREAD

**Issue by FuckYouIdontneedanotheraccount** [bbepis/XUnity.AutoTranslator#1]
Is it possible to send hooked text to clipboard or have this implemented?

**Comment by gravydevsupreme** [comment]
How would this work? You would want the latest translated string (original text) seen to be copied to the clipboard on a keyboard command?

**Comment by FuckYouIdontneedanotheraccount** [comment]
just send new raw text to clipboard instead of to the output file, like for example having an option in the config file to send all IMGUI text directly to clipboard but still process everything else like it currently does

**Comment by gravydevsupreme** [comment]
I'm simply trying to understand the use-case here, so I have an idea if it is feasible. But it is very possible to say that the text should not be added to the clipboard if it was already encountered (and therefore translated) before.

**Comment by FuckYouIdontneedanotheraccount** [comment]
i was personally thinking it would be easier to grab lines of text to translate on the fly without having to deal with a google translate mess and not needing to have an internet connection, but it might be useful for your other issue as well. i'm not familiar with machine TL in the west but i know koreans have their own program that does so and chinese may as well, i believe sending text to clipboard is how they work

**Comment by gravydevsupreme** [comment]
I am working on fixing all of these things. Give me a few hours, and I will post a test version here.

**Comment by gravydevsupreme** [comment]
Apparently I was doing some refactoring, which created the bug to always populate Endpoint if no string was present, oops.

Here's a new version. All of the described features should work in that (at least they do for me). Can you try that out?

[XUnity.AutoTranslator-BepIn-2.3.2.zip](https://github.com/bbepis/XUnity.AutoTranslator/files/1971470/XUnity.AutoTranslator-BepIn-2.3.2.zip)
[XUnity.AutoTranslator-IPA-2.3.2.zip](https://github.com/bbepis/XUnity.AutoTranslator/files/1971471/XUnity.AutoTranslator-IPA-2.3.2.zip)

NOTE: You must let the untranslated text appear for at least a small while, as I have implemented some "debouncing" functionality to prevent texts that are rapidly changing from being translated.

Also: Is this roughly what you are looking for then, or is it still the clipboard part that is important.

**Comment by FuckYouIdontneedanotheraccount** [comment]
well i saw someone ask for the clipboard part in the /h/ thread a few days ago which is what gave me the idea in the first place but with the features fixed this is good enough for me so thanks for your trouble

**Comment by gravydevsupreme** [comment]
Alright. In this case I will close this issue and include this change in the next release.
