### ISSUE TITLE
Portuguese Brazil does not work

### ISSUE THREAD

**Issue by Marcos547** [bbepis/XUnity.AutoTranslator#100]
O plugin cria as pastas mas, fica faltando um arquivo "_AutoGeneratedTranslations" e por isso não faz a tradução para Portuguese Brazil

**Comment by gravydevsupreme** [comment]
What language code are you using in the configuration file for `Language`?

**Comment by Marcos547** [comment]
[General]
Language=pt-br
FromLanguage=en
----------------------
game: Castle of Temptation V0.1.3_English

**Comment by gravydevsupreme** [comment]
The country modifier "br" is not supported by any translator. You should simply use set the language to

```
Language=pt
```

[Reference](https://cloud.google.com/translate/docs/languages)

**Comment by Marcos547** [comment]
ok

**Comment by gravydevsupreme** [comment]
I hope this fixed the issue. Feel free to re-open if it did not.
