### ISSUE TITLE
The function OverrideFont can't find some fonts installed in OS

### ISSUE THREAD

**Issue by 1101839859** [bbepis/XUnity.AutoTranslator#102]
I have installed some fonts and want to use it,but when I tried to use it,it tolds me:
The specified override font is not available. 
and give me a long list,which have some fonts installed on my computer——but not all.
I have thought it only supported for the fonts which has installed at the system install.but I find a font named TeamViewer15,it's not a pre - installed font——Actually it was installed by Teamviewer.So I think whether this function need fonts have some special fix?Or it's a bug...?
"This font can be use,and I don't know why"
![image](https://user-images.githubusercontent.com/68044286/86996132-64b8fe80-c1dd-11ea-9980-eeafeda5e3d1.png)
"This is the list,and I don't know why many fonts can't display"
![image](https://user-images.githubusercontent.com/68044286/86996204-97fb8d80-c1dd-11ea-938d-92d470958699.png)

**Comment by gravydevsupreme** [comment]
To be honest I don't know the answer to this. The API used to obtain these fonts is called `Font.GetOSInstalledFontNames()`, which is a part of Unity.

I have no idea which fonts qualifies to be returned from this API. The unity documentation states that the supported font formats are [.otf and .ttf (old docs)](https://docs.unity3d.com/560/Documentation/Manual/class-Font.html). But this is during design time in the editor.

If your font is in this format and it still doesn't show up, then I have no idea.

**Comment by 1101839859** [comment]
I use a monitor software and find  why. The  Font.GetOSInstalledFontNames()  tried to read the fonts that included in C:\Windows\Fonts . But in WIN10(Or my computer?),The font that you tried to install will put in this folder:
C:\Users\Administrator\AppData\Local\Microsoft\Windows\Fonts
And that's why the game cannot find the fonts. Seems it is hard to change that... there don't have any way to change the method and allowed it to read another location...

**Comment by gravydevsupreme** [comment]
Can't say I know much about how fonts are installed. Perhaps you can simply drag your font file into the C:\Windows\Fonts folder? That's how I've installed fonts in the past.

**Comment by 1101839859** [comment]
I tried,but it also put it in C:\Users\Administrator\AppData\Local\Microsoft\Windows\Fonts.but I find how to fix(?) it.

1.Use WinHex to open UnityPlayer.dll (Which can change Hexadecimal) and search "466f6e7473"(Mean Fonts),then change the Fonts to others like Donts, and put fonts in this folder.
2.Use WinRAR or other tools and set the unzip location to C:\Windows\Fonts,It will successfully put the fonts in this folder.
(I think it must need Administrator to do that)
The fonts name seems must only English letters/numbers.
Thank you for answer me, or I'll never know how to fix it.

**Comment by ag2s20150909** [comment]
Fix Way:when you install font,choose install for all user.

**Comment by gravydevsupreme** [comment]
I assume this issue has been solved. Feel free to re-open if not.
