### ISSUE TITLE
Translate Methods For Manual Patching?

### ISSUE THREAD

**Issue by marcussacana** [bbepis/XUnity.AutoTranslator#103]
I was looking for a method to translate the string, and looks like is this one:
`XUnity.AutoTranslator.Plugin.Core.AutoTranslationPlugin.Current.TranslateOrQueueWebJob` 
But this method is private.

I  wanted apply a manual patching in the AssemblyCSharp to can fix the 'typewrite' effect untranslated.

**Comment by marcussacana** [comment]
Forget, I added my own: https://github.com/marcussacana/XUnity.AutoTranslator/commit/813fdb2777e8048067893917d9532709c32efd2f
If you want PR (well, it's a bit useless to you maybe) just say.
I will left open because maybe there is a 'proper way' to do that and I don't know

**Comment by gravydevsupreme** [comment]
Greetings!

If you simply want to translate a text then there is a public interface available to do so:

```csharp
   /// <summary>
   /// Public API Surface for the Auto Translator Plugin.
   /// </summary>
   public interface ITranslator
   {
      /// <summary>
      /// Queries the plugin to provide a translated text for the untranslated text.
      /// If the translation cannot be found in the cache, it will make a
      /// request to the translator selected by the user.
      /// </summary>
      /// <param name="untranslatedText">The untranslated text to provide a translation for.</param>
      /// <param name="onCompleted">Callback to completion of the translation.</param>
      void TranslateAsync( string untranslatedText, Action<TranslationResult> onCompleted );

      /// <summary>
      /// Queries the plugin to provide a translated text for the untranslated text.
      /// If the translation cannot be found in the cache, it will make a
      /// request to the translator selected by the user.
      /// </summary>
      /// <param name="untranslatedText">The untranslated text to provide a translation for.</param>
      /// <param name="scope">Scope to be used during translation cache lookup.</param>
      /// <param name="onCompleted">Callback to completion of the translation.</param>
      void TranslateAsync( string untranslatedText, int scope, Action<TranslationResult> onCompleted );

      /// <summary>
      /// Queries the plugin to provide a translated text for the untranslated text.
      /// If the translation cannot be found in the cache, the method returns false
      /// and returns null as the untranslated text.
      /// </summary>
      /// <param name="untranslatedText">The untranslated text to provide a translation for.</param>
      /// <param name="translatedText">The translated text.</param>
      /// <returns></returns>
      bool TryTranslate( string untranslatedText, out string translatedText );

      /// <summary>
      /// Queries the plugin to provide a translated text for the untranslated text.
      /// If the translation cannot be found in the cache, the method returns false
      /// and returns null as the untranslated text.
      /// </summary>
      /// <param name="untranslatedText">The untranslated text to provide a translation for.</param>
      /// <param name="scope">Scope to be used during translation cache lookup.</param>
      /// <param name="translatedText">The translated text.</param>
      /// <returns></returns>
      bool TryTranslate( string untranslatedText, int scope, out string translatedText );
   }
```

An instance of this interface can be obtained through `AutoTranslator.Default`.

Do note that if you want to use this API translate texts, and simply hook various text components yourself, then if you queue a lot of similar texts to this API in a sequential fashion, the plugin will shutdown because it detects it as spam (Similar texts are often produced by type-writer-like techniques). For example if you queue:
 1. "
 2. "I
 3. "I a
 4. "I am

and so on...

**Comment by gravydevsupreme** [comment]
Also, forgot to add. If you want to enable type-writer effects on PRETRANSLATED texts, then in some games the following setting might be helpful:

```ini
[Behaviour]
GeneratePartialTranslations=False ;Indicates that the plugin should generate partial translations to support text translations as it is "scrolling in"
```

That setting is not entirely memory-friendly though. But it's just text so who cares ^_^.

**Comment by marcussacana** [comment]
In my case I patched very early, after the game load the string in their script.
then probably he don't will flood requests.
Anyway, thanks for the info, that should help, i almost forget to ensure if he isn't spamming anyway.
