### ISSUE TITLE
Could not find the TextMeshPro

### ISSUE THREAD

**Issue by mem0ric** [bbepis/XUnity.AutoTranslator#115]
There was a problem with capturing fonts and gives such an error. You can advise how to deal with it. Game Ostranauts Demo for free on Steam.

[INFO][XUnity.AutoTranslator]:  Loaded XUnity.AutoTranslator into Unity [5.6.3p1] game.
[INFO][XUnity.AutoTranslator]:  Attempting to load TextMesh Pro font from asset bundle.
[ERROR][XUnity.AutoTranslator]:  Could not find the TextMeshPro font asset: arialuni_sdf_u2018

This error also occurred on other versions of the Unity.

**Comment by gravydevsupreme** [comment]
Hi. Sorry for the late reply.

The asset bundles provided in the download does not support this version of Unity nor do they support the specific version of TextMesh Pro.

In order for them to work, both of the versions would have to match.

**Comment by mem0ric** [comment]
XUnity.AutoTranslator transfers the game to Unity [5.6.3p1] but not part on EnableTextMeshPro.
original
![Screenshot_3](https://user-images.githubusercontent.com/49410206/92837759-2b348780-f408-11ea-8fe1-5988a181573d.png)

transfer

![Screenshot_5](https://user-images.githubusercontent.com/49410206/92837971-6afb6f00-f408-11ea-8cdd-f80b9c19be95.png)

but at the same time it gives an error in the console that I wrote above.

**Comment by gravydevsupreme** [comment]
Not quite sure I understand what you're saying.

The error above indicates that the font that you try to load through the file `arialuni_sdf_u2018` is not supported. The reason for this is version mismatch. There is not much I can do to help with this. All I can do is guide you to this [issue](https://github.com/bbepis/XUnity.AutoTranslator/issues/57), but even that wont fully help you when the game is using this old of an engine.

In the screenshot you're showing parts of the game appears to be translated using the cyrillic character set, but those part likely are not based on TextMesh Pro, but rather standard Unity UI (some games uses more than one UI text component type).

**Comment by TaoDeimos** [comment]
After several years, by chance, a complete solution to this problem was not found?

**Comment by Atamg1994** [comment]
> Not quite sure I understand what you're saying.
> 
> The error above indicates that the font that you try to load through the file `arialuni_sdf_u2018` is not supported. The reason for this is version mismatch. There is not much I can do to help with this. All I can do is guide you to this [issue](https://github.com/bbepis/XUnity.AutoTranslator/issues/57), but even that wont fully help you when the game is using this old of an engine.
> 
> In the screenshot you're showing parts of the game appears to be translated using the cyrillic character set, but those part likely are not based on TextMesh Pro, but rather standard Unity UI (some games uses more than one UI text component type).

I shared a mod here somewhere that connects dynamic fonts from a ttf file
it is for the melon loader, the original version is for l2ccp, but somewhere in the answers I made a mono version, why not see how everything works there and add this support

**Comment by Atamg1994** [comment]
> After several years, by chance, a complete solution to this problem was not found?

look at my posts in this topic 
https://github.com/bbepis/XUnity.AutoTranslator/issues/287
https://github.com/bbepis/XUnity.AutoTranslator/issues/57
https://github.com/bbepis/XUnity.AutoTranslator/issues/351
