### ISSUE TITLE
Questions about TextMesh Pro

### ISSUE THREAD

**Issue by Cecropis** [bbepis/XUnity.AutoTranslator#121]
I generate a font follows the step described in #57, but I can only get .asset files (different from those without extension).
Then I put it in the root folder of the game and relaunch it.
![image](https://user-images.githubusercontent.com/30413607/93637194-841fa380-fa38-11ea-8977-12221a9a54cd.png)
And I got a message from the console shows that "Could not load asset bundle while loading font":
![image](https://user-images.githubusercontent.com/30413607/93637553-2049aa80-fa39-11ea-92b1-1e343f78638a.png)

I'm pretty sure the version of unity and TMP is matching.

Could you tell me the possible reason for this fault? Thanks~: )

**Comment by Cecropis** [comment]
![image](https://user-images.githubusercontent.com/30413607/93639284-16757680-fa3c-11ea-9419-66c3c3eaba72.png)
This is the configure of my Font Asset Creator

**Comment by gravydevsupreme** [comment]
It's really hard for me to tell.

All I really know is that when the asset bundle itself is being attempted to be loaded, a null reference is returned from the API.

Perhaps you can try to use BepInEx to print out the Unity log to see if it indicates any specific error messages in relation to the loading of the asset bundles.

**Comment by Cecropis** [comment]
The Unity Log tells me "Unable to read header from archive file"
![image](https://user-images.githubusercontent.com/30413607/93671795-59415800-fae9-11ea-9ac6-24b0b6101c48.png)
Is it indicated that the way I generate the font file is wrong?

**Comment by Cecropis** [comment]
> It's really hard for me to tell.
> 
> All I really know is that when the asset bundle itself is being attempted to be loaded, a null reference is returned from the API.
> 
> Perhaps you can try to use BepInEx to print out the Unity log to see if it indicates any specific error messages in relation to the loading of the asset bundles.

The Unity Log tells me "Unable to read header from archive file"
image
Is it indicated that the way I generate the font file is wrong?

**Comment by Cecropis** [comment]
> It's really hard for me to tell.
> 
> All I really know is that when the asset bundle itself is being attempted to be loaded, a null reference is returned from the API.
> 
> Perhaps you can try to use BepInEx to print out the Unity log to see if it indicates any specific error messages in relation to the loading of the asset bundles.

The Unity Log tells me "Unable to read header from archive file"
![image](https://user-images.githubusercontent.com/30413607/93671821-96a5e580-fae9-11ea-9853-2023906dbd61.png)

Is it indicated that the way I generate the font file is wrong?

**Comment by Cecropis** [comment]
It seems I have some misunderstanding about the asset bundle. I actually need to write a script to create the bundle after generate the font asset.XD

**Comment by Cecropis** [comment]
I have fixed my font file and it works.
I'll share the file here:

[arialuni_sdf_201731f1.zip](https://github.com/bbepis/XUnity.AutoTranslator/files/5250295/arialuni_sdf_201731f1.zip)

**Comment by Cecropis** [comment]
Thanks for your help @gravydevsupreme o(*￣▽￣*)o
