### ISSUE TITLE
"This Land Is My Land" dont work anymore

### ISSUE THREAD

**Issue by cacarasa** [bbepis/XUnity.AutoTranslator#122]
Before it worked perfectly for me with the ReiPatcher, but now it doesn't translate anything...

The "MonoBleedingEdge" folder was not in that location before...

![game](https://user-images.githubusercontent.com/20714192/93801425-5b560480-fc18-11ea-85c9-68f0955d6a82.png)

**Comment by gravydevsupreme** [comment]
Greetings,

I don't really understand. 
 * The installer doesn't move any files or folders. It only creates them.
 * You're saying it worked and then stopped in this game? Perhaps you can provide some log or console information after running the game?

**Comment by cacarasa** [comment]
Could it be because it is a game that is not installed?

**Comment by gravydevsupreme** [comment]
No, that should not matter at all.

**Comment by gravydevsupreme** [comment]
Closing due to inacitvity.
