### ISSUE TITLE
XUnity.AutoTranslator 4.12.1 won't translate for me.

### ISSUE THREAD

**Issue by forbidden101v** [bbepis/XUnity.AutoTranslator#123]
I don't believe this is a bug but more so a set up issue on my end. This is what I get when I run it. I was able to inject another dll file so I know BepInEx is working.

[Info   :XUnity.AutoTranslator] Skipping plugin scan because no plugin-specific translations has been registered.

I have no clue what settings I need to change. All I did was install BepInEx and XUnity.AutoTranslator to their proper directories. I tried playing around with the AutoTranslatorConfig.ini but I have no idea what to adjust really. Any help would be much appreciated.

**Comment by gravydevsupreme** [comment]
You're going to have to provide more information.
 * Game?
 * Language?

The log message your are showing is related to plugin-specific translations that are used in some games with a big modding community behind them and here it is simply indicating that it could find no such mods/plugins.

But the plugin is quite obviously loading given that message, so the error is more likely related to text hooking or similar.

**Comment by forbidden101v** [comment]
Upon closer inspection it turns out the text I was trying to translate are images so thats why it didn't work. I'll close this issue since theres nothing left to be resolved now.
