### ISSUE TITLE
Problem with hooking a game

### ISSUE THREAD

**Issue by spiritov0d** [bbepis/XUnity.AutoTranslator#125]
Hello. Latest AutoTranslator build doesn't work properly with the newly released game called Silent Space (缄默星空). Basically, when you apply ReiPatcher version, it will patch and create AutoTranslation folder with config, but doesn't produce any results. At first I thought it's the same issue as here https://github.com/bbepis/XUnity.AutoTranslator/issues/87 - but the game is using default libraries (I've compared them with clean unity project on the same engine version). 
After that I've switched to BeInEx version and got [this log](https://drive.google.com/file/d/1XdK2pgWRZX2W7f8Y9EF5dPNTNRfoq7qR/view?usp=sharing). Not sure if the problem is due to mentioned in the log errors or the game is using some unsupported text framework.

**Comment by gravydevsupreme** [comment]
Does it work with default configuration? I am pretty sure some of the hooks it tries to apply in this log are off by default.

Either way it looks like it could be an issue with MonoMod, as it appears the error originates from there.

Maybe updating MonoMod could help. (Or it could break things further)

Please try downloading this:

**Comment by spiritov0d** [comment]
Thanks for the reply. 
No, it doesn't work with default settings as well (only AutoTranslator folder with config is created). I've just checked and replacing DLLs didn't work either, the result is still the same. I suspect it could be because of tolua plugin used by game. If it translates original lua to mono-compatible code, it can affect some standard functions (probably). Here is untouched [managed folder](https://drive.google.com/file/d/1X6XvRgFdzqo-ziXpO6j9IbalazscfMj4/view?usp=sharing), if you're willing to take a look.

**Comment by gravydevsupreme** [comment]
Hello again,

I looked at the managed folder and it appears this game is using FairyGUI, which is not overly well tested, but should work. I have not tested it myself as I do not currently have access to the game.

That is somewhat unrelated from errors that are posted in the log, though. Those indicate that the plugin is unable to generate dynamic code to call functions in the game logic. I have implemented a new version that uses some fallback logic, perhaps you can try that? It should still give some warnings but it might just work.

Could you try it and post the log afterwards?

[XUnity.AutoTranslator-ReiPatcher-4.12.1.zip](https://github.com/bbepis/XUnity.AutoTranslator/files/5322874/XUnity.AutoTranslator-ReiPatcher-4.12.1.zip)
[XUnity.AutoTranslator-BepIn-5x-4.12.1.zip](https://github.com/bbepis/XUnity.AutoTranslator/files/5322875/XUnity.AutoTranslator-BepIn-5x-4.12.1.zip)

**Comment by spiritov0d** [comment]
Thank you, it now works properly with both provided BepIn and ReiPatcher versions. Here are [logs](https://drive.google.com/file/d/1JnfU9d_gQxE2smAxdPHB40zzpEyvw2W_/view?usp=sharing) from BepIn, but like you've said, errors mentioned there can be ignored and updated plugin works fine with the game.

**Comment by gravydevsupreme** [comment]
Good. For now I will keep this issue open, as I am still uncertain as to why it fails to generate dynamic code. I think I have actually seen this is another game before, but back then I simply ignored it.

Could be an issue with Cecil/MonoMod that needs to be resolved.

**Comment by gravydevsupreme** [comment]
The latest release includes a fix for this. Still based on reflection, but changing the MonoMod backend with BepInEx may solve it as well (I am  guessing)
