### ISSUE TITLE
Issues about Plugin-specific Manual Translations

### ISSUE THREAD

**Issue by gbhayate** [bbepis/XUnity.AutoTranslator#127]
According to the tutorial, I made specific translation texts for several plugins. When using specific translations, these plugins do not always show the translated texts. After multiple runs, these texts are sometimes shown as translations and sometimes as original texts.
As you can see from the screenshot, the text in the text box and the text in the drop-down list are shown in different languages.
![demo](https://user-images.githubusercontent.com/4521809/95009617-05d91900-0656-11eb-9ab8-6305375bc178.png)

**Comment by gravydevsupreme** [comment]
Wow, someone actually using this feature. 👍 

I will investigate why this is not behaving as expected.

**Comment by gravydevsupreme** [comment]
Does this work as expected?

[XUnity.AutoTranslator-BepIn-5x-4.12.1.zip](https://github.com/bbepis/XUnity.AutoTranslator/files/5323369/XUnity.AutoTranslator-BepIn-5x-4.12.1.zip)

**Comment by gbhayate** [comment]
> Does this work as expected?
> 
> [XUnity.AutoTranslator-BepIn-5x-4.12.1.zip](https://github.com/bbepis/XUnity.AutoTranslator/files/5323378/XUnity.AutoTranslator-BepIn-5x-4.12.1.zip)
> 
> (edit: updated link)

It does work in a sense, for the part on the screenshot, but a drop-down box of another plugin is still the same as before.

When using a specific translation, the text on some components will never be translated, and other texts sometimes show the translated texts and sometimes show the original texts.

The two pictures show how it works when the same translation texts are using as specific translation and non-specific translation.
![01](https://user-images.githubusercontent.com/4521809/95020967-d56a9c80-06a0-11eb-91c6-49bf12c30778.png)
![02](https://user-images.githubusercontent.com/4521809/95020974-d8658d00-06a0-11eb-99f2-220db5de1747.png)

**Comment by gravydevsupreme** [comment]
That would be because all standard UI extensions are actually handled by a different mod:
 * HS2API for HS2
 * AIAPI (I think) for AI Shoujo
 * etc...

So you would have to also make a plugin translation folder for that plugin.

This translation plugin has no way of knowing that it was actually Material Editor that caused AIAPI to generate custom UI.

**Comment by gbhayate** [comment]
> That would be because all standard UI extensions are actually handled by a different mod:
> 
> * HS2API for HS2
> * AIAPI (I think) for AI Shoujo
> * etc...
> 
> So you would have to also make a plugin translation folder for that plugin.
> 
> This translation plugin has no way of knowing that it was actually Material Editor that caused AIAPI to generate custom UI.

Many thanks.This is really helpful.By putting translated text under the AIAPI folder, some plugins are indeed translated.
