### ISSUE TITLE
BaiduTranslate problem

### ISSUE THREAD

**Issue by Inory0203** [bbepis/XUnity.AutoTranslator#130]
After several versions of testing，I found that the version after 4.11.3(contain) cant recognize cht but zh can in BaiduTranslate when I play the game.

Situation like this In AutoTranslatorConfig.ini :

Language=cht
FromLanguage=ja

previous version can recognize cht，after the game update I had to update XUnity.AutoTranslator and I found this problem.
I saw there was a bug fix of BaiduTranslate in 4.11.3，will the reason be there?
How can I solve it? 
Thank you.

**Comment by Inory0203** [comment]
I'm using BepInEx v5.3.

**Comment by gravydevsupreme** [comment]
You need to use one of the following monikers:
 * zh
 * zh-Hans
 * zh-Hant
 * zh-CN
 * zh-TW

**Comment by gravydevsupreme** [comment]
(I know this is not what the official baidu API description indicates, but I've tried to normalized these monikers across the different translators that are integrated into this plugin)

**Comment by Inory0203** [comment]
Oh...I see.
According to my test, zh-Hans, zh-CN and zh works but zh-Hant and zh-TW still can'ts, show "not support".

**Comment by flywhc** [comment]
Baidu online Translator uses cht for Traditional Chinese.
I haven't tested the baidu API.

**Comment by Inory0203** [comment]
> Baidu online Translator uses cht for Traditional Chinese.
> I haven't tested the baidu API.


Yes, I know. But either cht or zh-TW can't work.

**Comment by Inory0203** [comment]
> You need to use one of the following monikers:
> 
> * zh
> * zh-Hans
> * zh-Hant
> * zh-CN
> * zh-TW
> 
> zh-Hans, zh-CN and zh = simplified
> zh-Hant and zh-TW = traditional
> 
> Please report back if these works as expected.

**Comment by gravydevsupreme** [comment]
The plugin converts the monikers like this:

Left-hand side = input into config file
Right-hand side = input to baidu API

```
         { "zh", "zh" },
         { "zh-Hans", "zh" },
         { "zh-CN", "zh" },
         { "zh-Hant", "cht" },
         { "zh-TW", "cht" },
```

**Comment by gravydevsupreme** [comment]
I'm not sure why you would get not-supported when using something that converts into cht, but the Baidu plugin is not massively well tested on my part.

**Comment by Inory0203** [comment]
Hmm...strange.

**Comment by Inory0203** [comment]
This is the picture of Logging.Console where the error occurred.
[img]https://upload.cc/i1/2020/10/14/3tYgBu.png[/img]
Could you figure out something?

**Comment by gravydevsupreme** [comment]
Please try this:

[BaiduTranslate.zip](https://github.com/bbepis/XUnity.AutoTranslator/files/5384224/BaiduTranslate.zip)


That may have been a basic mistake on my part.

**Comment by Inory0203** [comment]
It works! Thank you very much!

**Comment by gravydevsupreme** [comment]
Now released.
