### ISSUE TITLE
MaxCharactersPerTranslation / possibility to capture the right original string

### ISSUE THREAD

**Issue by sandzhaj** [bbepis/XUnity.AutoTranslator#131]
Is it possible to make an option to capture untranslated text to the _AutoGeneratedTranslations.txt without a translation, or copy it to the clipboard even if it has > 1000 characters? So, I could use it and make manual translation.

I'm trying to translate Twilight Struggle and in some places it has big text with some invisible tags:

For example:
![image](https://user-images.githubusercontent.com/13132782/95770656-6b667e80-0cc2-11eb-910c-bfcf26f178ec.png)
****

And since that text is a single string - it couldn't be captured with your program. I tried to guess how that string looks:
```Except for <color%3Dwhite>Scoring Cards</color>, all cards contain an <color%3Dwhite>Operation Point</color> value, an <color%3Dwhite>Event Title</color> and <color%3Dwhite>Event Description</color>. <color%3Dwhite>Scoring Cards</color> are labeled "SCORING" and must be played sometime during the turn they are drawn. Cards with a Red star are only associated with the USSR, and cards with a White star are only associated with the US. Cards that have a split Red/White star are Neutral, and are associated with both sides.\n\nCards are played in either one of two ways - as <color%3Dwhite>Events</color> or <color%3Dwhite>Operations</color>. Many cards have an asterisk following their <color%3Dwhite>Event Title</color>. When these cards are played as <color%3Dwhite>Events</color>, they are removed permanently from the game. Cards that have their <color%3Dwhite>Event Title</color> underlined, and are played as an Event, are in effect on the game board until they are cancelled. Cards that are discarded, but not removed from the game, are placed face up in the discarded pile.=```
But translation doesn't work, maybe i missed some special symbol or something else. I just want to have a possibility to capture the right original string if it has more than 1000 symbols.

**Comment by gravydevsupreme** [comment]
Perhaps it is time to increase the limit again. :D

**Comment by sandzhaj** [comment]
For my personal use, I did that already, so I can capture any text from that game I want. Many thanks for your tool.

That thread is about a proposal to create something. For example, there could be a mode, without translating, but original text being captured to the txt file without any limits?

It would be useful for translators. :)

**Comment by gravydevsupreme** [comment]
I added a new optional `OutputTooLongText=False`. If you change this to true it should now output text even if it is too long.

Can you try it out and tell me if it works?

[XUnity.AutoTranslator-BepIn-5x-4.13.0-beta3.zip](https://github.com/bbepis/XUnity.AutoTranslator/files/5384299/XUnity.AutoTranslator-BepIn-5x-4.13.0-beta3.zip)
[XUnity.AutoTranslator-ReiPatcher-4.13.0-beta3.zip](https://github.com/bbepis/XUnity.AutoTranslator/files/5384301/XUnity.AutoTranslator-ReiPatcher-4.13.0-beta3.zip)

Also increased the max characters from 1000 to 2500.

**Comment by sandzhaj** [comment]
Yes! That function works as expected! 

With 200 limit, I got the original text, so i can make my own translation. That is very useful. Thanks

![image](https://user-images.githubusercontent.com/13132782/96128969-aa811380-0efe-11eb-983e-cdbad4163755.png)

**Comment by gravydevsupreme** [comment]
Fixed in 4.13.0
