### ISSUE TITLE
Translation error, The game crashes when changing scene.

### ISSUE THREAD

**Issue by HimikoS** [bbepis/XUnity.AutoTranslator#134]
Hello, good I am using (SetupReiPatcherAndAutoTranslator), When I start the game, it translates it normal, there are scenes where I can play normal, but in some scenes, when the scene changes, the game closes, and I tried switching to another language to translate, as an example from (English-Italian), and it is translated normal without error throughout the game, but when you translate from (English-Spanish), there are scenes where the game freezes and closes. the game I'm talking about is (third crisis 0.28.0), some way to solve it, I'm a beginner is this.

**Comment by gravydevsupreme** [comment]
It's hard for me comment on why this is occurring. But usually when this type of thing happens it's because the game relies on text that is displayed on the screen for game logic (which is stupid!).

I have experienced it in many games. Usually what I do when I encounter such things is simply to turn off the translations (ALT+T) when the error would usually occur and turn it back on again afterwards (ALT+T).

**Alternatively** you can try to enable `TextGetterCompatibilityMode` in the configuration. That should try to fool the game into thinking it is not actually translated, so when logic like this occurs it uses the original text for it's internal processing instead of the translated text.

**Comment by HimikoS** [comment]
> It's hard for me comment on why this is occurring. But usually when this type of thing happens it's because the game relies on text that is displayed on the screen for game logic (which is stupid!).
> 
> I have experienced it in many games. Usually what I do when I encounter such things is simply to turn off the translations (ALT+T) when the error would usually occur and turn it back on again afterwards (ALT+T).
> 
> **Alternatively** you can try to enable in the configuration. That should try to fool the game into thinking it is not actually translated, so when logic like this occurs it uses the original text for it's internal processing instead of the translated text.`TextGetterCompatibilityMode`

Well, I already put the code but it remains the same, and I have been changing the translations manually to Spanish, and apparently the game closes when processing translations that contain the following characters (á, é, í, ó, ú, Á, É, Í , Ó, Ú, ñ, Ñ), which gives me to understand that it could be the type of font that the game uses, but in the Italian language, these characters are used more frequently, and there it is not closed, it I wonder if there is a way to change the font, or exclude these characters when they are translated?

**Comment by gravydevsupreme** [comment]
You can try setting `TranslationPostProcessing=RemoveAllDiacritics` in the configuration.

**Comment by HimikoS** [comment]
> You can try setting `TranslationPostProcessing=RemoveAllDiacritics` in the configuration.

Thank you very much this I solve it, for now it's fine, what this does is replace the characters (á, é, í, ó, ú, Á, É, Í, Ó, Ú, ñ, Ñ) by (a, e, i, o, u, A, E, I, O, U, n, N), well now I can play it well, but I think it would be better to change the fonts (ttf) of the game for one that contains those characters, try to extract ttf sources with UnityEX, but it gives me an error in the middle of the extraction, well this is another matter. I consider this issue solved, thank you very much

Only one last query you know how to reduce the translated text, is that some leave the text box, Texts like (Omit, Hide, etc), and as according to what I read in your information about this program if it can be done in the config .ini.

**Comment by gravydevsupreme** [comment]
It's primarily a manual process but it is possible to reduce font size and change wrapping behaviour. This should be documented and you can find examples of it being done in games such as HS2 and AIS.

**Comment by HimikoS** [comment]
> It's primarily a manual process but it is possible to reduce font size and change wrapping behaviour. This should be documented and you can find examples of it being done in games such as HS2 and AIS.

ok, thank you very much, I give this issue as solved.
