### ISSUE TITLE
il2-cpp

### ISSUE THREAD

**Issue by djlaser** [bbepis/XUnity.AutoTranslator#136]
Hello.I would like to know if there will be support for XUnityAutoTranslator in the il2cc plugin

**Comment by gravydevsupreme** [comment]
There is some support.

https://github.com/bbepis/XUnity.AutoTranslator/issues/98

Most features in this version are disabled.

**Comment by djlaser** [comment]
Thanks a lot. Good luck working on the plugin

**Comment by gravydevsupreme** [comment]
Will definitely be supported when BepInEx supports it.

**Comment by gravydevsupreme** [comment]
Issue is tracked in pinned issue. Closing
