### ISSUE TITLE
arialuni_sdf_u2019 doesn't support some Chineses

### ISSUE THREAD

**Issue by flywhc** [bbepis/XUnity.AutoTranslator#137]
set font in configuration:
OverrideFont=BepInEx\Translation\Font\arialuni_sdf_u2019
OverrideFontTextMeshPro=BepInEx\Translation\Font\arialuni_sdf_u2019

HS2 Studio displays many Chinese characters as a box in random locations.

while arialuni_sdf_u2018 almost works fine except Studio displays an extra box after many correct Chinese Translations. I guess it is caused by another issue that I will try to find the pattern.

**Comment by gravydevsupreme** [comment]
If I am not mistaken it is generated with the following unicode ranges:

```
0000-052F,2E80-2EFF,3000-4DBF,4E00-9FFF,AC00-D7AF
```

**Comment by gravydevsupreme** [comment]
If it simply display the "missing character"-character after each translation it may simply be because you've set `RedirectedResourceDetectionStrategy=AppendMongolianVowelSeparator`. I do not believe this font package I created include the mongolian vowel separator. (and in general the fonts illusion uses doesn't either).

**Comment by flywhc** [comment]
It shouldn't be related to other settings or translations because the problem is solved by simply replacing arialuni_sdf_u2019 with arialuni_sdf_u2018 

I wonder what are the differences between arialuni_sdf_u2018 and arialuni_sdf_u2019?


The second issue I mentioned may be caused by AppendMongolianVowelSeparator because the "missing characters" are all at the end of labels in the HS2 studio.

**Comment by flywhc** [comment]
I changed the setting to:
RedirectedResourceDetectionStrategy=AppendMongolianVowelSeparatorAndRemoveAppended
Most text in Studio has no ‘missing char’ now except one mistakenly load text from redirected resources - will check the reason.

**Comment by gravydevsupreme** [comment]
The only different between those two asset bundles is the version with which they are generated. One is with Unity 2019.x and the other is with 2018.x (I am not sure which exact version of TextMesh Pro they were generated with). These fonts will always be able to contain oddities unless they are generated with an exact version match, which they almost certainly are not.

About missing char: Probably best to set the option to `RedirectedResourceDetectionStrategy=AppendMongolianVowelSeparatorAndRemoveAll`, so it removes all occurrences of that character, no matter where they are placed in the text string.

**Comment by ag2s20150909** [comment]
arialuni_sdf_u2019 is missing some full-width symbols

**Comment by cangjieBlue** [comment]
arialuni_sdf_U2018 is missing {…} Symbol, HS2 needs this symbol to hide characters beyond the display range

**Comment by gravydevsupreme** [comment]
Hi,

I am not going to generate the asset bundle with the font needed to support HS2 (for what I assume is Chinese).

However, generating it is not difficult in later versions of the Unity Editor.

Here's some of the settings I used to generated arialuni_sdf_2019/2018:

https://github.com/bbepis/XUnity.AutoTranslator/issues/57#issuecomment-569442090
