### ISSUE TITLE
CM3D2 (x64) 1.62 crash when launching the game

### ISSUE THREAD

**Issue by KatouMegumi-osu** [bbepis/XUnity.AutoTranslator#14]
So.. The plugin is working through BepInEx (Sybaris loader and UnityInjector loader also installed) framework, that's what I can say. The game is also being ran through NTLEAS. 

[2018-10-15_234156.zip](https://github.com/bbepis/XUnity.AutoTranslator/files/2480071/2018-10-15_234156.zip)

**Comment by gravydevsupreme** [comment]
Apologies for not having provided feedback to this, now, very old issue. If it is still an issue with newer versions please re-open the issue.

With that being said, this plugin should work just fine in both CM3D2 and COM3D2.
