### ISSUE TITLE
Help with "The Red Lantern" game

### ISSUE THREAD

**Issue by cacarasa** [bbepis/XUnity.AutoTranslator#140]
In this great game the XUnity AutoTranslator ReiPatcher does not translate, I read that it does not work only with games that contain the il2cpp texts. How can they be translated with the MelonMod or is there another way? 

Here are screenshot of structure of game:
[http://imgfz.com/i/4QoIFjh.png](url)

Sorry for my English and thanks in advance

**Comment by gravydevsupreme** [comment]
Your link links to nowhere.

Anyway, if you're talking about IL2CPP there is currently limited supported.

https://github.com/bbepis/XUnity.AutoTranslator/issues/98

**Comment by cacarasa** [comment]
<img src="http://imgfz.com/i/4QoIFjh.png" style="max-width:100%;"></a>

Thank you for responding. Yes, I mean games with il2cpp texts, but as I read in another post this line "I have a very preliminary version of the plugin that works with IL2CPP through MelonMod. I wanted to know how to use it...

Thanks

**Comment by gravydevsupreme** [comment]
I have not tried the game in question, but I recently updated it to support the latest version of MelonLoader (v0.2.7.2 Open-Beta).

[XUnity.AutoTranslator-MelonMod-4.13.0.zip](https://github.com/bbepis/XUnity.AutoTranslator/files/5540939/XUnity.AutoTranslator-MelonMod-4.13.0.zip)

I think that version of MelonLoader is a lot easier to install than previous versions, since it is better at downloading the external dependencies during installation.

This version i still very preliminary. It should simply be a drop-in after having installed MelonLoader. If it doesn't work I cannot currently provide too much support on it, though.

**Comment by cacarasa** [comment]
thanks!!! for the mod! how to install this?

**Comment by gravydevsupreme** [comment]
It really should just be unzip directly into game directory after having installed MelonMod. And MelonMod has a managed installer.

**Comment by NekoChanTaiwan** [comment]
> It really should just be unzip directly into game directory after having installed MelonLoader. And MelonLoader has a managed installer.

can u update the plugin to support the latest version of MelonLoader (v0.2.7.4 Open-Beta) plz

**Comment by longxa762** [comment]
> 
> 
> I have not tried the game in question, but I recently updated it to support the latest version of MelonLoader (v0.2.7.2 Open-Beta).
> 
> [XUnity.AutoTranslator-MelonMod-4.13.0.zip](https://github.com/bbepis/XUnity.AutoTranslator/files/5540939/XUnity.AutoTranslator-MelonMod-4.13.0.zip)
> 
> I think that version of MelonLoader is a lot easier to install than previous versions, since it is better at downloading the external dependencies during installation.
> 
> This version i still very preliminary. It should simply be a drop-in after having installed MelonLoader. If it doesn't work I cannot currently provide too much support on it, though.

Can you please update this to support the latest alpha version (0.3.0)?

**Comment by gravydevsupreme** [comment]
I will keep track of latest version in the issue below.

https://github.com/bbepis/XUnity.AutoTranslator/issues/159

Sorry for generally not responding to these threads. I am not really getting any notifications, so it's a bit of a pain. To avoid further issues with that I will also close this (and some other issues).
