### ISSUE TITLE
Translation text

### ISSUE THREAD

**Issue by djlaser** [bbepis/XUnity.AutoTranslator#141]
Hi, watch this video and help if you can.
[https://mega.nz/file/lmwUAQQZ#bAMcPuDgfgQt8deIvX6ts725LSeS3GHKZstrhE7HjcI](url)

**Comment by djlaser** [comment]
Hi, watch this video and help if you can.
https://mega.nz/file/lmwUAQQZ#bAMcPuDgfgQt8deIvX6ts725LSeS3GHKZstrhE7HjcI

**Comment by gravydevsupreme** [comment]
It feels like the game is appending untranslated text to text that has already been translated.

Does this also occur if you simply disable `GeneratePartialTranslations`? Not all games will work equally well with that option enabled.

**Comment by djlaser** [comment]
Thank you now everything is fine, the text is in English then in Russian, can we make it so that it was immediately translated.

**Comment by djlaser** [comment]
Thank you now everything is just fine.Health To You. If necessary, I can support your project with money. Write where
