### ISSUE TITLE
Copy and Paste into Translation Aggregator

### ISSUE THREAD

**Issue by Terell2018** [bbepis/XUnity.AutoTranslator#143]
I just wonder is it possible it you could add copy and paste as the feather into the translator aggregator, like it you edit the translator in the translation aggregator.

**Comment by gravydevsupreme** [comment]
Just so we're clear about what is being asked here: You want to be able to input your own text into the translation aggregator window, allowing you to use it to translate any text?

**Comment by Terell2018** [comment]
Yes, but i am not sure it that might work.
