### ISSUE TITLE
Any way to shotcut key to Switch translator or send untranslated text to clipboard ?

### ISSUE THREAD

**Issue by FabioManoel1977** [bbepis/XUnity.AutoTranslator#147]
Sorry bad english

not sure how explain in english, but, I will try, If you not understand me I will try use others words

I trefer to use Textractor, too bad several games not works with textractor but works fine with XUnity.AutoTranslator-ReiPatcher-4.13.0

Everybody who play hentai games with auto translators knows that several translators translate the same sentence in different ways, then is good to compare the same sentence translated by GoogleTranslate, YandexTranslate and BaiduTranslate, sometimes the same sentence is translated totally differently, I guess is unnecessary give examples, everybody knows it.

I wanted to use the option CopyToClipboard=True but for some reason the text is NOT copied to clipboard for me translate it using Translator Aggregator, I guess is not because  I installed it wrong, since the game text is translated perfect fine, I am using XUnity.AutoTranslator-ReiPatcher-4.13.0

Then since is impossible to copy the untranslated text to clipboard to translate it using translator aggregator, exist a shortcut key that when we press it circle the text desired to be translated between the different translator sites ?

For instance, just a example using a ramdom key,  I press CTRL+ J the text is translated by google, but pressing teh same CTRL+ J  teh same text is then translated by Yandex and the If press again the same text is then translated by Baidu, in few words, exist a way to compare the translated text between the compatible Online Translators ?

Ok, Ok, maybe you guys thinks that it is unnecessary, but see the example:

![64071029-5dcd7100-cc47-11e9-9044-734a46ec8881](https://user-images.githubusercontent.com/41028393/101411051-10669780-38bf-11eb-91d1-4674ef55faaa.jpg)

In this example the text was translated very differently, and thanks to the different Translators  I can understand the meaning: The girl wanted to keep distance of the male protagonist because she thinks that he is someone vulgar.

Then I think that is a BIG mistake play a game using only ONE translator, we need to use all of then at same time.

**Comment by gravydevsupreme** [comment]
I think the functionality in this plugin to send text to clipboard has always been a bit wonky at best.

In the following version I've changed it so that it sends text to the clipboard at the same time it sends it to the internal translation aggregator (ALT+1 hotkey).

Perhaps this works better?

[XUnity.AutoTranslator-ReiPatcher-4.13.0.zip](https://github.com/bbepis/XUnity.AutoTranslator/files/5683096/XUnity.AutoTranslator-ReiPatcher-4.13.0.zip)

**Comment by GustJc** [comment]
I've made a simple workaround if you want the untranslated text copied to the clipboard.
Here is a gist of a very crude and simple python3 HTTP server that takes the translation request and copies it to the clipboard.
https://gist.github.com/GustJc/ba46236e1ae4e6f42a5668d04f9e0fb0

You need to configure a custom translator URL to be
```
[Custom]
Url=http://127.0.0.1:8080
```
Run the server and set to use the Custom(127.0.0.1) online translator.

**Comment by gravydevsupreme** [comment]
This issue should be fixed in the latest version 4.14.0. Behavior should be like the version posted above.
