### ISSUE TITLE
Translation is working, but I can't find where config is.

### ISSUE THREAD

**Issue by dbdufan** [bbepis/XUnity.AutoTranslator#150]
When I use BepinEX, there is AutoTranslatorConfig.ini to change the output language. 
But when I use UnityInjector version, I can't find AutoTranslatorConfig.ini or similar things.
Where can I find that?
Thank you for great plugin.

**Comment by gravydevsupreme** [comment]
For Sybaris, the ini file is located at `Sybaris\UnityInjector\Config\AutoTranslatorPlugin.ini`

**Comment by dbdufan** [comment]
I found it. Thank you for kind instruction.
