### ISSUE TITLE
Translating beyond current line

### ISSUE THREAD

**Issue by AtotehZ** [bbepis/XUnity.AutoTranslator#152]
As the title says.

Is there a way to translate beyond the current line?

Can I change something in "config.ini" to make it translate more at a time?

I haven't seen it explained anywhere, I apologise in advance if I've missed it somewhere.

**Comment by gravydevsupreme** [comment]
Not entirely sure what you mean.

If you are talking about translating the resources of a game before they are used, then no, since all games handles resources differently.

**Comment by AtotehZ** [comment]
That was pretty much what I meant. Thank you.

It's easier to swallow it isn't made that way when you know the option isn't readily available somewhere. That it's because it would require separate plugins game by game.

My problem is that I read fast.. So when I have to wait a little second each line, even the short ones, things are slowed down significantly.

I appreciate your answer.
