### ISSUE TITLE
Latest versions targeting IL2CPP

### ISSUE THREAD

**Issue by gravydevsupreme** [bbepis/XUnity.AutoTranslator#159]
Closing this issue as I've published v5.0.0.

Releases available [here](https://github.com/bbepis/XUnity.AutoTranslator/releases).

**--- OUTDATED ---**
Using this issue to keep track of latest releases for IL2CPP, rather than posting them in various other issues or as a release.

Not using a release because I don't want to constantly provide support for beta/alpha software.
[XUnity.AutoTranslator-BepInEx-IL2CPP-5.0.0-beta13.zip](https://github.com/bbepis/XUnity.AutoTranslator/files/7818213/XUnity.AutoTranslator-BepInEx-IL2CPP-5.0.0-beta13.zip)
[XUnity.AutoTranslator-MelonMod-IL2CPP-5.0.0-beta13.zip](https://github.com/bbepis/XUnity.AutoTranslator/files/7818214/XUnity.AutoTranslator-MelonMod-IL2CPP-5.0.0-beta13.zip)

Version 5.0.0-beta13 should bring many improvements as the code bases has now been properly merged. It includes support for:
 * Translator UI (ALT+0 in-game)
 * UI Resizing
 * Texture Translation
 * Resource Redirection
 * Uses correct library directories for MelonLoader
 * Fixes various initialization issues with mod in IL2CPP
 * Fixed UTAGE hooks for IL2CPP

There are still many things missing, however.

.
.
.
[XUnity.AutoTranslator-BepInEx-IL2CPP-5.0.0-beta12.zip](https://github.com/bbepis/XUnity.AutoTranslator/files/7816927/XUnity.AutoTranslator-BepInEx-IL2CPP-5.0.0-beta12.zip)
[XUnity.AutoTranslator-MelonMod-IL2CPP-5.0.0-beta12.zip](https://github.com/bbepis/XUnity.AutoTranslator/files/7816928/XUnity.AutoTranslator-MelonMod-IL2CPP-5.0.0-beta12.zip)

[XUnity.AutoTranslator-BepInEx-IL2CPP-5.0.0-beta10.zip](https://github.com/bbepis/XUnity.AutoTranslator/files/7797845/XUnity.AutoTranslator-BepInEx-IL2CPP-5.0.0-beta10.zip)
[XUnity.AutoTranslator-MelonMod-IL2CPP-5.0.0-beta10.zip](https://github.com/bbepis/XUnity.AutoTranslator/files/7797846/XUnity.AutoTranslator-MelonMod-IL2CPP-5.0.0-beta10.zip)

[XUnity.AutoTranslator-BepInEx-IL2CPP-5.0.0-beta9.zip](https://github.com/bbepis/XUnity.AutoTranslator/files/7796362/XUnity.AutoTranslator-BepInEx-IL2CPP-5.0.0-beta9.zip)
[XUnity.AutoTranslator-MelonMod-IL2CPP-5.0.0-beta9.zip](https://github.com/bbepis/XUnity.AutoTranslator/files/7796363/XUnity.AutoTranslator-MelonMod-IL2CPP-5.0.0-beta9.zip)

[XUnity.AutoTranslator-BepInEx-IL2CPP-5.0.0-beta7.zip](https://github.com/bbepis/XUnity.AutoTranslator/files/7794240/XUnity.AutoTranslator-BepInEx-IL2CPP-5.0.0-beta7.zip)
[XUnity.AutoTranslator-MelonMod-IL2CPP-5.0.0-beta7.zip](https://github.com/bbepis/XUnity.AutoTranslator/files/7794219/XUnity.AutoTranslator-MelonMod-IL2CPP-5.0.0-beta7.zip)

[XUnity.AutoTranslator-BepInEx-IL2CPP-5.0.0-beta4.zip](https://github.com/bbepis/XUnity.AutoTranslator/files/7786656/XUnity.AutoTranslator-BepInEx-IL2CPP-5.0.0-beta4.zip)
[XUnity.AutoTranslator-MelonMod-IL2CPP-5.0.0-beta4.zip](https://github.com/bbepis/XUnity.AutoTranslator/files/7786657/XUnity.AutoTranslator-MelonMod-IL2CPP-5.0.0-beta4.zip)

[XUnity.AutoTranslator-BepInEx-IL2CPP-5.0.0-beta3.zip](https://github.com/bbepis/XUnity.AutoTranslator/files/7782012/XUnity.AutoTranslator-BepInEx-IL2CPP-5.0.0-beta3.zip)
[XUnity.AutoTranslator-MelonMod-IL2CPP-5.0.0-beta3.zip](https://github.com/bbepis/XUnity.AutoTranslator/files/7782013/XUnity.AutoTranslator-MelonMod-IL2CPP-5.0.0-beta3.zip)

[XUnity.AutoTranslator-BepInEx-IL2CPP-5.0.0-beta2.zip](https://github.com/bbepis/XUnity.AutoTranslator/files/7780740/XUnity.AutoTranslator-BepInEx-IL2CPP-5.0.0-beta2.zip)
[XUnity.AutoTranslator-MelonMod-IL2CPP-5.0.0-beta2.zip](https://github.com/bbepis/XUnity.AutoTranslator/files/7780744/XUnity.AutoTranslator-MelonMod-IL2CPP-5.0.0-beta2.zip)

[XUnity.AutoTranslator-BepInEx-IL2CPP-5.0.0-beta1.zip](https://github.com/bbepis/XUnity.AutoTranslator/files/7777513/XUnity.AutoTranslator-BepInEx-IL2CPP-5.0.0.zip) (For BepInEx Unity IL2CPP for Windows x64/x86 machines)
[XUnity.AutoTranslator-MelonMod-5.0.0-beta1.zip](https://github.com/bbepis/XUnity.AutoTranslator/files/7777514/XUnity.AutoTranslator-MelonMod-5.0.0.zip) (for MelonLoader 0.5.2)

[XUnity.AutoTranslator-BepInEx-IL2CPP-4.21.0.zip](https://github.com/bbepis/XUnity.AutoTranslator/files/7770650/XUnity.AutoTranslator-BepInEx-IL2CPP-4.21.0.zip) (For BepInEx Unity IL2CPP for Windows x64/x86 machines)
[XUnity.AutoTranslator-MelonMod-4.21.0.zip](https://github.com/bbepis/XUnity.AutoTranslator/files/7770651/XUnity.AutoTranslator-MelonMod-4.21.0.zip) (for MelonLoader 0.5.2)

[XUnity.AutoTranslator-BepInEx-IL2CPP-4.18.0.zip](https://github.com/bbepis/XUnity.AutoTranslator/files/7025210/XUnity.AutoTranslator-BepInEx-IL2CPP-4.18.0.zip) (For BepInEx Unity IL2CPP for Windows x64/x86 machines)
[XUnity.AutoTranslator-MelonMod-4.18.0.zip](https://github.com/bbepis/XUnity.AutoTranslator/files/7025211/XUnity.AutoTranslator-MelonMod-4.18.0.zip) (for MelonLoader 0.4.3)

[XUnity.AutoTranslator-BepInEx-IL2CPP-4.13.0.zip](https://github.com/bbepis/XUnity.AutoTranslator/files/5938786/XUnity.AutoTranslator-BepInEx-IL2CPP-4.13.0.zip) (For BepInEx Unity IL2CPP for Windows x64/x86 machines)
[XUnity.AutoTranslator-MelonMod-4.13.0.zip](https://github.com/bbepis/XUnity.AutoTranslator/files/5938787/XUnity.AutoTranslator-MelonMod-4.13.0.zip) (for MelonLoader 0.3.0 ALPHA)

UPDATE (new version for BepInEx):
[XUnity.AutoTranslator-BepInEx-IL2CPP-4.18.0.zip](https://github.com/bbepis/XUnity.AutoTranslator/files/7009038/XUnity.AutoTranslator-BepInEx-IL2CPP-4.18.0.zip)

This new version is barely tested. Only seen it working in one game. I am currently working on a lot of refactoring to be able to merge the IL2CPP and main branch, but this will take some time. Most important change: shortcuts should now work if the Input API is not trimmed away from the game in question.

**Comment by memsenpai** [comment]
@gravydevsupreme  can you share source ?

**Comment by gravydevsupreme** [comment]
Latest source for IL2CPP available here: 

https://github.com/bbepis/XUnity.AutoTranslator/tree/il2cpp_update

**Comment by orangespoons** [comment]
@gravydevsupreme 
Does it include changing the sdf font? It doesn't work for me.
OverrideFont=Arial is doesn't work either.

I was translated from Japanese to English and from Japanese to Chinese (Simplified), the translation works fine.
Game officially supports English, Japanese, Chinese (Simplified), and Chinese (Traditional).
I checked the textures of the sdf font and found that the Korean language was included normally.
I think xunity.autotranslator can't load external sdf fonts.


----
[General]
Language=ko
FromLanguage=ja
...
EnableTextMeshPro=True
EnableTextMesh=False
...
OverrideFontTextMeshPro=arialuni_sdf_u2019

**Comment by gravydevsupreme** [comment]
The current version of the IL2CPP plugin does not support changing fonts.

**Comment by orangespoons** [comment]
> The current version of the IL2CPP plugin does not support changing fonts.

Thank you! I hope the font change will be supported soon! :)

**Comment by Mochongli** [comment]
[Info   :XUnity.AutoTranslator] Loaded XUnity.AutoTranslator into Unity [2019.4.22f1] game.
[Warning:XUnity.AutoTranslator] Input API is not available!
System.TypeLoadException: Could not resolve type with token 010000a4 from typeref (expected class 'UnityEngine.Input' in assembly 'UnityEngine.CoreModule, Version=3.7.1.6, Culture=neutral, PublicKeyToken=null')
  at XUnity.AutoTranslator.Plugin.Core.AutoTranslationPlugin.HandleInputSafe () [0x00007] in <855e1b6e49cf4dd88249de51e100ff6e>:0 
[Info   :XUnity.AutoTranslator] Skipping plugin scan because no plugin-specific translations has been registered.

**Comment by gravydevsupreme** [comment]
That is more of a warning than an error. That being said, it could probably be fixed. But I have not prioritized fixing it and simply fallen back to disabling user interaction.

**Comment by cacarasa** [comment]
could someone make a tutorial on how to install these tools? 

thank you very much and sorry for my ignorance.

**Comment by gravydevsupreme** [comment]
Seems I missed this comment by about half a month.

Either way, I am not really doing a lot to keep the above versions updated, so I am probably not going to be making a guide either. BepInEx is probably the easier of the two to setup since it is just a matter of copy-paste the correct versions. Also I am not sure the current MelonLoader release supports the latest version. In fact I doubt it.

**Comment by dima245** [comment]
translate.google
But it is impossible, in the program, to add scanning of the entire game and at once translation of all the text in the game? 
analogous to the MTool program https://www.patreon.com/AdventCirno 
and then, each line to translate, each time, separately, takes a lot of time. especially when the connection to the Internet is not stable, due to the dir-300 router 
original text
а нельзя, в програму, добавить сканирование  всей игры и разом перевод всего текста в игре?
по аналогу програмы MTool  https://www.patreon.com/AdventCirno
а то, каждую строчку переводить, каждый раз, отдельно , много времени занимает. особено когда связь с интернетом, не стабильна, изза роутера dir-300

**Comment by djlaser** [comment]
Hello.
And you can't tell me when the
tehmeh translation and font support for it will be added to translator icc2.

**Comment by thesuperfatcat** [comment]
@gravydevsupreme Can you please update the translaslator.dll files? il2cpp targets only work on googletranslate. Watson,bing etc not working.

**Comment by gravydevsupreme** [comment]
@dima245 - I know the tool by AdventCirno, but that tool, impressive as it is, (probably) works primarily by knowing the resource structures of the games it support (although it is probably more advanced than just that). Doing that with Unity is problematic in many ways. 

@djlaser @thesuperfatcat - I have been kinda putting off updating the IL2CPP plugin because of how much it diverges from the original. I may look into getting it updated soonishly.

**Comment by gravydevsupreme** [comment]
UPDATE: Added highly untested version 4.18.0.

**Comment by cacarasa** [comment]
I am also looking forward to the new plugin for melonloader which works better than bepinex. Thanks!!!! Great job!!!!

**Comment by gravydevsupreme** [comment]
UPDATE: Added 4.18.0 for MelonLoader.

**Comment by thesuperfatcat** [comment]
Thanks for the new update! But still only work google translate. Bing, watson etc. get some errors. Same error appears in bepinex and melonloader.
Here error log:
[ERROR] A batch operation failed. Disabling batching and restarting failed jobs.
[ERROR] 5 or more consecutive errors occurred. Shutting down translator endpoint.

**Comment by gravydevsupreme** [comment]
And this is not happening in Non-IL2CPP games?

**Comment by baoenzo** [comment]
Wow, this work for me. But is there a way to change the game font?
Sorry for my bad english

**Comment by dima245** [comment]
XUnity.AutoTranslator-BepInEx-IL2CPP  
does not work "OverrideFont="
game 
RJ278044 Snow Brandia
RJ293542 Snow Brandia fairy later

**Comment by Mochongli** [comment]
sup load external sdf fonts now?

**Comment by gravydevsupreme** [comment]
Well. The code to support it should be included, but I have not tested it. But custom TextMesh Pro support is shaky even in the Mono version of the plugin due to the strict version requirements.

**Comment by Mochongli** [comment]
Fonts cannot be completely overwritten in Computer Tycoon
I have turned on all TextFrameworks

**Comment by Mochongli** [comment]
I can't change fonts in Computer Tycoon using the same version of unityfs

**Comment by gravydevsupreme** [comment]
This updated version should print out the version of TextMesh Pro the game uses. It should also attempt to print out the version of the font asset used. But in my experience that information is often unavailable in IL2CPP.

[XUnity.AutoTranslator-BepInEx-IL2CPP-5.0.0-beta8.zip](https://github.com/bbepis/XUnity.AutoTranslator/files/7796285/XUnity.AutoTranslator-BepInEx-IL2CPP-5.0.0-beta8.zip)
[XUnity.AutoTranslator-MelonMod-IL2CPP-5.0.0-beta8.zip](https://github.com/bbepis/XUnity.AutoTranslator/files/7796286/XUnity.AutoTranslator-MelonMod-IL2CPP-5.0.0-beta8.zip)

**Comment by gravydevsupreme** [comment]
This version adds a new option `FallbackFontTextMeshPro` that can replace `OverrideFontTextMeshPro` which may be more reliable.

[XUnity.AutoTranslator-BepInEx-IL2CPP-5.0.0-beta9.zip](https://github.com/bbepis/XUnity.AutoTranslator/files/7796360/XUnity.AutoTranslator-BepInEx-IL2CPP-5.0.0-beta9.zip)
[XUnity.AutoTranslator-MelonMod-IL2CPP-5.0.0-beta9.zip](https://github.com/bbepis/XUnity.AutoTranslator/files/7796361/XUnity.AutoTranslator-MelonMod-IL2CPP-5.0.0-beta9.zip)

**Comment by orangespoons** [comment]
@gravydevsupreme 
Hello,
In-game text hook of the il2cpp game does not work, and I ask you about the error.
There seems to be an error in the process of hooking the UGUI.
Error log: https://pastebin.com/pBGRNMXv
Game: HolyKnightRicca (hentai game)

The UI part is often not translated at all.
Some UIs appear when the UI is reloaded without restart game. 
( ex)main menu - setting - main menu... maybe a unity scene change? )

And the main dialogue part is not translated at all.
This game can hide or show the dialogue window by right-click button,
I have to turn off and on the dialogue window each time for translation to take place.

What should I do if an error like this appears?
Thanks.

**Comment by gravydevsupreme** [comment]
These may work better.
[XUnity.AutoTranslator-BepInEx-IL2CPP-5.0.0-beta10.zip](https://github.com/bbepis/XUnity.AutoTranslator/files/7797843/XUnity.AutoTranslator-BepInEx-IL2CPP-5.0.0-beta10.zip)
[XUnity.AutoTranslator-MelonMod-IL2CPP-5.0.0-beta10.zip](https://github.com/bbepis/XUnity.AutoTranslator/files/7797844/XUnity.AutoTranslator-MelonMod-IL2CPP-5.0.0-beta10.zip)

You will need to set `DisableTextMeshProScrollInEffects=True`.

**Comment by orangespoons** [comment]
hi, I'm having issue with OverrideFontTextMeshPro or FallbackFontTextMeshPro option.
I created an AssetBundle by referring to [this link](https://github.com/bbepis/XUnity.AutoTranslator/issues/182), but it didn't work.
[TMP_Font_AssetBundles.zip](https://github.com/bbepis/XUnity.AutoTranslator/releases/download/v4.21.0/TMP_Font_AssetBundles.zip) also failed because the game unity version is 2020.

So, I opened the log file to find out what the problem was.
`[06:32:56.874] Version of TextMesh Pro: 1.4.0.`
yaay, I figured this was the problem because I found out that the versions of TextMeshPro were different.
When I install Unity 2020.3.24, the default installed version of TextMeshPro is 3.0.6.
After referring to [this link](https://github.com/needle-mirror/com.unity.textmeshpro/releases/tag/1.4.0) and setting the version of TextMeshPro to 1.4.0, I tried again, but the error still occurred.
Changing the compression method in the [AssetBundles - Advances Settings] didn't help.

Am I doing something wrong?
If the OverrideFontTextMeshPro option is enabled, the text is broken into squares, 
and if the FallbackFontTextMeshPro option is enabled, AutoTranslator does not work.

Game: HolyKnightRicca (hentai game)
Config.ini: https://pastebin.com/dKw6KGi1
Error Log (FallbackFontTextMeshPro): https://pastebin.com/8gEHBZLY
Error Log (OverrideFontTextMeshPro) : https://pastebin.com/cySEUt6K
AssetBundle file I created(contain English Character, Korean Character): https://mega.nz/file/rhUwVL6S#MkFYtxsmaLmVFkWLgQth8AwaPmTshFM-ZBxq__Nfp8k

Thanks for help.

**Comment by gravydevsupreme** [comment]
Seems that this game has stripped away the methods to load asset bundles synchronously. Will probably see if I can fallback to asynchronous loading in t his case.

**Comment by gravydevsupreme** [comment]
I managed to load your font file in the newly published beta121 using `FallbackFontTextMeshPro`.

**Comment by orangespoons** [comment]
> I managed to load your font file in the newly published beta12 using `FallbackFontTextMeshPro`.

hmm. for me, it still doesn't work with some red error lines.
Is it correct to set the config.ini file like this?
config.ini: https://pastebin.com/0hu4QeJ1
and, log: https://pastebin.com/4wgZ9Jzf

MelonLoader x64 0.5.2 + AutoTranslator 5.0.0 beta 12 + ezTransXP

**Comment by gravydevsupreme** [comment]
In general I think you should just use the same version as the game if possible. Some versions are probably cross-compatible, though. But I don't know which.

About compression, as long as the unity engine used supports it, it probably does not matter. 

I added a new version, but I have not changed anything that should get it working compared to beta12. Your configuration looks correct as well.

I used BepInEx 6, however. Although I do not believe that would have made the difference given the error you got. To me the error simply looks like you're using the wrong version.

[XUnity.AutoTranslator-BepInEx-IL2CPP-5.0.0-beta13.zip](https://github.com/bbepis/XUnity.AutoTranslator/files/7818206/XUnity.AutoTranslator-BepInEx-IL2CPP-5.0.0-beta13.zip)
[XUnity.AutoTranslator-MelonMod-IL2CPP-5.0.0-beta13.zip](https://github.com/bbepis/XUnity.AutoTranslator/files/7818207/XUnity.AutoTranslator-MelonMod-IL2CPP-5.0.0-beta13.zip)

**Comment by orangespoons** [comment]
@gravydevsupreme 
Jesus, I changed the modloader from MelonLoader to BepinEX and it works fine.
Could it be a MelonLoader problem?
Anyway, thank you so much!
Thank you for your time.

**Comment by Mochongli** [comment]
System.Runtime.Serialization.SerializationException: The constructor to deserialize an object of type 'System.Net.Http.HttpRequestException' was not found. ---> System.Runtime.Serialization.SerializationException: The constructor to deserialize an object of type 'System.Net.Http.HttpRequestException' was not found.
  at System.Runtime.Serialization.ObjectManager.GetConstructor (System.RuntimeType t) [0x00029] in <986ed57b9a8f4699a3c59a69eb05944a>:0 
  at System.Runtime.Serialization.ObjectManager.CompleteISerializableObject (System.Object obj, System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context) [0x00034] in <986ed57b9a8f4699a3c59a69eb05944a>:0 
   --- End of inner exception stack trace ---
  at System.Runtime.Serialization.ObjectManager.CompleteISerializableObject (System.Object obj, System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context) [0x00058] in <986ed57b9a8f4699a3c59a69eb05944a>:0 
  at System.Runtime.Serialization.ObjectManager.FixupSpecialObject (System.Runtime.Serialization.ObjectHolder holder) [0x00088] in <986ed57b9a8f4699a3c59a69eb05944a>:0 
  at System.Runtime.Serialization.ObjectManager.DoFixups () [0x0005a] in <986ed57b9a8f4699a3c59a69eb05944a>:0 
  at System.Runtime.Serialization.Formatters.Binary.ObjectReader.Deserialize (System.Runtime.Remoting.Messaging.HeaderHandler handler, System.Runtime.Serialization.Formatters.Binary.__BinaryParser serParser, System.Boolean fCheck, System.Boolean isCrossAppDomain, System.Runtime.Remoting.Messaging.IMethodCallMessage methodCallMessage) [0x00077] in <986ed57b9a8f4699a3c59a69eb05944a>:0 
  at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize (System.IO.Stream serializationStream, System.Runtime.Remoting.Messaging.HeaderHandler handler, System.Boolean fCheck, System.Boolean isCrossAppDomain, System.Runtime.Remoting.Messaging.IMethodCallMessage methodCallMessage) [0x000a2] in <986ed57b9a8f4699a3c59a69eb05944a>:0 
  at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize (System.IO.Stream serializationStream, System.Runtime.Remoting.Messaging.HeaderHandler handler, System.Boolean fCheck, System.Runtime.Remoting.Messaging.IMethodCallMessage methodCallMessage) [0x00000] in <986ed57b9a8f4699a3c59a69eb05944a>:0 
  at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize (System.IO.Stream serializationStream, System.Runtime.Remoting.Messaging.HeaderHandler handler, System.Boolean fCheck) [0x00000] in <986ed57b9a8f4699a3c59a69eb05944a>:0 
  at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize (System.IO.Stream serializationStream, System.Runtime.Remoting.Messaging.HeaderHandler handler) [0x00000] in <986ed57b9a8f4699a3c59a69eb05944a>:0 
  at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize (System.IO.Stream serializationStream) [0x00000] in <986ed57b9a8f4699a3c59a69eb05944a>:0 
  at System.Runtime.Remoting.RemotingServices.DeserializeCallData (System.Byte[] array) [0x0001c] in <986ed57b9a8f4699a3c59a69eb05944a>:0 
  at (wrapper xdomain-invoke) BepInEx.IL2CPP.ProxyAssemblyGenerator+AppDomainRunner.GenerateAssembliesInternal(BepInEx.IL2CPP.ProxyAssemblyGenerator/AppDomainListener,string,BepInEx.IL2CPP.ProxyAssemblyGenerator/IL2CPPDumperType)
  at (wrapper remoting-invoke-with-check) BepInEx.IL2CPP.ProxyAssemblyGenerator+AppDomainRunner.GenerateAssembliesInternal(BepInEx.IL2CPP.ProxyAssemblyGenerator/AppDomainListener,string,BepInEx.IL2CPP.ProxyAssemblyGenerator/IL2CPPDumperType)
  at BepInEx.IL2CPP.ProxyAssemblyGenerator.GenerateAssemblies () [0x000ab] in <ad9e63b7f30343e7afd94c1a14adc2e4>:0 
  at BepInEx.IL2CPP.Preloader.Run () [0x002a6] in <ad9e63b7f30343e7afd94c1a14adc2e4>:0 
  at BepInEx.IL2CPP.UnityPreloaderRunner.PreloaderMain (System.String[] args) [0x0007e] in <ad9e63b7f30343e7afd94c1a14adc2e4>:0 
  at BepInEx.IL2CPP.DoorstopEntrypoint.Main (System.String[] args) [0x00088] in <ad9e63b7f30343e7afd94c1a14adc2e4>:0

**Comment by Mochongli** [comment]
> I can't change fonts in Computer Tycoon using the same version of unityfs

use FallbackFontTextMeshPro

**Comment by gravydevsupreme** [comment]
Closing this issue because an IL2CPP version has now been "officially" releases. Will no longer track this issue. Create separate issues to get help resolve problems.
