### ISSUE TITLE
Some space is deactivated.

### ISSUE THREAD

**Issue by u-u22** [bbepis/XUnity.AutoTranslator#163]
First of all, I am using the translator so well. Thank you.

The problem is that certain spaces are disabled when the game I play is being translated. Is there a way to solve it?
![1](https://user-images.githubusercontent.com/80884379/111597636-b9ebec00-8811-11eb-94c0-51627f71e9de.png)
![2](https://user-images.githubusercontent.com/80884379/111597655-bfe1cd00-8811-11eb-91f4-15d5f42ea60a.png)

**Comment by gravydevsupreme** [comment]
I'd say that looks like an oddity with the game in question where it depends on the text being displayed to the user to determine the interactability of the component. These types of problems can be hard to fix without doing some highly game-specific.

I'd suggest you try to press ALT+T and see if they are re-enabled while not translated.

**Comment by u-u22** [comment]
ALT+T로 번역을 비활성화 하면 잘 됩니다.
필요할 때만 끄면서 사용해야 겠네요 감사합니다.
