### ISSUE TITLE
Ingame Google Translate Different from WebService Google Translate

### ISSUE THREAD

**Issue by TheUnsaid** [bbepis/XUnity.AutoTranslator#164]
Translations by Xunity are different from what webservice google translate give.
Here's the text: カラスの使い魔

This is what Xunity translated:
https://gyazo.com/b00d4310b68a221de782a982629637d0

This is how it's translated using the webservice:
https://gyazo.com/c24073f14890874c126b3df64cbc3f7c

I don't know what happened but it wasn't always like this. It feels like translation quality has dropped significantly recently. No matter how far back I go in releases though it's the same problem.

**Comment by gravydevsupreme** [comment]
Took a deeper diver into the cause of this. It seems that the official client sends some fairly long haired parameters to their API backend that causes it to only send a single translation suggestion back to the client. This -seemingly- at least in this case, is better than the primary suggestion it sends back by default. 

That being said, the current call that this plugin makes to their API in this case also receives the suggestion that the translation should be "Crow Familiar", it just isn't the primary suggestion. ^_^

**Comment by TheUnsaid** [comment]
> Took a deeper diver into the cause of this. It seems that the official client sends some fairly long haired parameters to their API backend that causes it to only send a single translation suggestion back to the client. This -seemingly- at least in this case, is better than the primary suggestion it sends back by default.
> 
> That being said, the current call that this plugin makes to their API in this case also receives the suggestion that the translation should be "Crow Familiar", it just isn't the primary suggestion. ^_^

Is there any way to make it use the secondary suggestion?

**Comment by gravydevsupreme** [comment]
Not without affecting all translations. But you can try this:

[XUnity.AutoTranslator-BepIn-5x-4.15.0-custom.zip](https://github.com/bbepis/XUnity.AutoTranslator/files/6217900/XUnity.AutoTranslator-BepIn-5x-4.15.0-custom.zip)

You must use `GoogleTranslateV2` instead of the default google translate and you should set

```ini
[GoogleV2]
RPCID=MkEWBc
VERSION=boq_translate-webserver_20210323.10_p0
UseSimplest=True
```

In the configuration file. I recommend also printing enabling debug output to console. It should print out when it finds different translations for the same string and which it has chosen.

**Comment by TheUnsaid** [comment]
> ```ini
> True
> ```

No serviceURL?
I'm using Reipatcher so I'm not sure I need that BepIn zip.

**Comment by gravydevsupreme** [comment]
You should just be able to replace the DLLs placed in the managed folder with the DLLs from the BepInEx archive. 

And no, you should not set a ServiceUrl, and it is [GoogleV2]. It should be created by itself after first startup.

**Comment by TheUnsaid** [comment]
> 
> 
> You should just be able to replace the DLLs placed in the managed folder with the DLLs from the BepInEx archive.
I'm sorry, but this confuses me XD.
There are no DLLs to merge from the BepInEx. Am I forced to use BepInEx? Is this truly impossible to do with Reipatcher?
The DLLs in that folder are like XUnity.Common.dll

Hmmm...
OH, it's inside the [Game Name]_data/Managed
>
> And no, you should not set a ServiceUrl, and it is [GoogleV2]. It should be created by itself after first startup.
So the endpoint is GoogleTranslateV2
But the Ini Header is GoogleV2

**Comment by gravydevsupreme** [comment]
[XUnity.AutoTranslator-ReiPatcher-4.15.0-custom.zip](https://github.com/bbepis/XUnity.AutoTranslator/files/6230034/XUnity.AutoTranslator-ReiPatcher-4.15.0-custom.zip)

Try this.

**Comment by TheUnsaid** [comment]
> 
> 
> [XUnity.AutoTranslator-ReiPatcher-4.15.0-custom.zip](https://github.com/bbepis/XUnity.AutoTranslator/files/6230034/XUnity.AutoTranslator-ReiPatcher-4.15.0-custom.zip)
> 
> Try this.
Oh, I'm sorry you had to do that. You made a custom reipatcher executable for me....
I'll test it on a complete fresh game.

Unzipped the game.
Used the custom ReiPatcher.
Opened the game.

**Using the Crow** is still the translation for Crow Familiar.

I've gone into the config.ini and noticed that the endpoint is set to GoogleTranslate. I've changed it to GoogleTranslateV2 and deleted all translations from before.

The same issue of 90% of the game not being translated has appeared. Want me to send you the game?

**Comment by gravydevsupreme** [comment]
Can try that. As long as we agree you have the following configuration:

```ini
[Service]
Endpoint=GoogleTranslateV2
FallbackEndpoint=

...

[GoogleV2]
RPCID=MkEWBc
VERSION=boq_translate-webserver_20201220.16_p1
UseSimplest=True
ServiceUrl=
```

**Comment by TheUnsaid** [comment]
> 
> 
> Sure, you can try sending the game. As long as we agree you have the following configuration:
> 
> ```ini
> [Service]
> Endpoint=GoogleTranslateV2
> FallbackEndpoint=
> 
> ...
> 
> [GoogleV2]
> RPCID=MkEWBc
> VERSION=boq_translate-webserver_20201220.16_p1
> UseSimplest=True
> ServiceUrl=
> ```

Yes that's exactly correct.
Doesn't seem like I can direct message so I'll just post it here.
https://www.dropbox.com/s/kczr2otcryanha9/SuccubusReborn_Demo_20210325b.zip?dl=1

**Comment by gravydevsupreme** [comment]
It seems that google V2 has an odd problem with certain strings that causes google to timeout, which is what is causing the issue seen here.

Gonna need further investigation.

**Comment by gravydevsupreme** [comment]
[XUnity.AutoTranslator-ReiPatcher-4.15.0-custom2.zip](https://github.com/bbepis/XUnity.AutoTranslator/files/6243840/XUnity.AutoTranslator-ReiPatcher-4.15.0-custom2.zip)

This probably fixed it.

**Comment by TheUnsaid** [comment]
> 
> 
> [XUnity.AutoTranslator-ReiPatcher-4.15.0-custom2.zip](https://github.com/bbepis/XUnity.AutoTranslator/files/6243840/XUnity.AutoTranslator-ReiPatcher-4.15.0-custom2.zip)
> 
> This probably fixed it.

Thank you very much. This is the closest it'll get to what it was before, though the translation is still quite inferior to how it was before. I really appreciate you doing this.

BTW: If anyone's reading this in the future, you still need to modify config.ini and set UseSimplest=True after setting your endpoint to GoogleTranslateV2

**Comment by rumanddd** [comment]
Thank you, I'll try this and see if it fixes the issue, it seems to be like I'm having a similar issue, I've yet to do further research, but I think with each restart it seems to translate more and more, atleast I think, but I've just changed my files to what you have got set here such as UseSimplest=True to see if anything improves.
