### ISSUE TITLE
apostrophe is replaced by code &#39;

### ISSUE THREAD

**Issue by RichardB73** [bbepis/XUnity.AutoTranslator#165]
Hi, I started using the legitimate google translate api due to getting wrong/strange translations recently.
But now I have the issue of all apostrophe's being replaced by the code `&#39`; when using google translate legitimate.
Is there any way to do a substitution or preprocessing on the returned translated text so I can get rid of it?

Example:
`Hoshimi？　どうしたの？=Hoshimi? What&#39;s wrong?`

Forgot to mention it happens in the game custom order maid 3d2.

**Comment by gravydevsupreme** [comment]
Will provide a fix for this in next version. May need a config reset, though.

**Comment by RichardB73** [comment]
Thanks that would be appreciated.

After playing for again for a while I noticed it did the same thing with `"` replacing it with `&quot;` , just noticed it scrolling through the translation's.

**Comment by gravydevsupreme** [comment]
Will make sure it handles all html entities.

**Comment by gravydevsupreme** [comment]
Should now be fixed in latest version. It will require a configuration reset if you did a previous install, though.
