### ISSUE TITLE
BingTranslateLegitimate does not work.

### ISSUE THREAD

**Issue by kataxu** [bbepis/XUnity.AutoTranslator#166]
Times out on "Requesting Translation...". Tried both keys and regenerated keys for several hours before deciding to post this issue.

**Comment by gravydevsupreme** [comment]
Greetings,

Just tried setting up my own key in Azure, and it worked without problems.

Have you set it up like in the screenshot below (with global Location) and grabbed the key from the specified textbox?

![APIKEY](https://user-images.githubusercontent.com/51834260/113012086-bbef6c80-917a-11eb-8248-8c556b71845b.png)

To be fair, I do not know what the Location is used for, but they specifically asked me to pick Global during the setup.

**Comment by kataxu** [comment]
Thank you very much, that fixed it. I appreciate your time and the work you've done!

**Comment by gravydevsupreme** [comment]
No problem.
