### ISSUE TITLE
Regular expressions are getting ignored

### ISSUE THREAD

**Issue by BreadDain** [bbepis/XUnity.AutoTranslator#170]
[Info   :   BepInEx] Loading [XUnity Auto Translator 4.15.0]
[Info   :XUnity.AutoTranslator] Loaded XUnity.AutoTranslator into Unity [2019.4.16f1] game.
[Info   :   BepInEx] Loading [XUnity Resource Redirector 1.2.0]

Translator ignores regular expressions which aim to ignore certain non-word characters and dynamic values in text like "Quick- Actions:", "Specials:", "Wealth: 45" or "Stealth: 10", which results in additional translation requests and clutters the translation file.

sr:"(?<before>.*?(?=:*?))(?<colon_i>:\s{0,2}$)"="${before}${colon_i}"
sr:"(^?<before>.*?(?=:))(?<colon_i>:\s{0,2})(?<after>[^a-zA-Z]*)"="${before}${colon_i}${after_i}"

These expression couldn't fire properly. regex101 confirms that those are valid expressions for these lines.

**Comment by gravydevsupreme** [comment]
I highly doubt these regexes work with .NET regex variant. Please use this site to confirm that they work instead:

http://regexstorm.net/tester

Also, just from a quick glance, I can see that there is a "before" named group in the result (replacement) expression, but that name does not exist in the original regex.

**Comment by BreadDain** [comment]
> 
> 
> I highly doubt these regexes work with .NET regex variant. Please use this site to confirm that they work instead:
> 
> http://regexstorm.net/tester
> 
> Also, just from a quick glance, I can see that there is a "before" named group in the result (replacement) expression, but that name does not exist in the original regex.

My bad, I missed the part that addon uses .Net variant. Although those lines were preformatted by github (which I didn't notice) original lines still don't work with .Net format.
