### ISSUE TITLE
I can't translate rempy

### ISSUE THREAD

**Issue by caedus12** [bbepis/XUnity.AutoTranslator#174]
I'm trying to translate a game but when I select 32 I get a lot of hooks that translate a part and the 64-bit one doesn't work

![Captura de pantalla (30)](https://user-images.githubusercontent.com/75753392/116011918-084c9180-a5ed-11eb-8a87-02a378db82ab.png)
![Captura de pantalla (31)](https://user-images.githubusercontent.com/75753392/116011923-0d114580-a5ed-11eb-801b-d932d1079998.png)
![Captura de pantalla (32)](https://user-images.githubusercontent.com/75753392/116011926-0f739f80-a5ed-11eb-8466-55ecfdf8cf6d.png)
![Captura de pantalla (33)](https://user-images.githubusercontent.com/75753392/116011929-113d6300-a5ed-11eb-9509-81c8d1c5ef7e.png)
![Captura de pantalla (34)](https://user-images.githubusercontent.com/75753392/116011932-139fbd00-a5ed-11eb-84f1-e706b61ecf27.png)

**Comment by gravydevsupreme** [comment]
Greetings,

The Textractor repository is [that way](https://github.com/Artikash/Textractor).

Have a nice day :)
