### ISSUE TITLE
Recognize no game text

### ISSUE THREAD

**Issue by Bamboo-D** [bbepis/XUnity.AutoTranslator#175]
**Version:** XUnity.AutoTranslator-ReiPatcher-4.15.0.zip
**Game:** Amplitude's Humankind
**Language:** en->zh by DeepLTranslate

**Works & Not Works:**

**√** Patch and Run
**√** Created file **__Preprocessors.txt_** and **__Substitutions.txt_** within **_"HUMANKIND\AutoTranslator\Translation\zh\Text"_**
**×** Created file **__AutoGeneratedTranslations.txt_** ?

**√** ALT + 0 XUnity AutoTranslator UI
**√** ALT + 1 Translation Aggregator UI
**×** Translations being queued ?

![屏幕截图 2021-05-02 152120](https://user-images.githubusercontent.com/49357500/116806139-bb713980-ab5d-11eb-81ac-5a1a9dcff42b.jpg)
(Just an example. There would be no Original Text at any progress during my game.)

I've tried BepInEx Plugin Version, it has the same problem as above. As for the IL2CPP version, it is even worse.

This translator works well with my other games. Thank you.
Maybe it is too demanding to require it to run in such a large game that is still in testing? But considering that it will not have an official localization for at least three months, I very much hope that you can help me play it now without barriers.

**Comment by gravydevsupreme** [comment]
The fact that the UI works means it is not IL2CPP. So the likely issue with this game is that it is probably using unknown or customized UI components that the plugin does not know anything about.

Nothing I can do about this without taking a closer look at the specific game.

**Comment by Bamboo-D** [comment]
I see... That is really frustrating.

-More information if you need.
[LogOutput.log](https://github.com/bbepis/XUnity.AutoTranslator/files/6411801/LogOutput.log)
![image](https://user-images.githubusercontent.com/49357500/116820506-1def2780-aba8-11eb-8d93-bdbfc0f28520.png)
![image](https://user-images.githubusercontent.com/49357500/116820515-32332480-aba8-11eb-8a83-378c644ceda9.png)

**Comment by gravydevsupreme** [comment]
Afraid I cannot see anything from this. Would need to inspect the game in person.

About the log: In general if you get an error (not warning), like these:

```
[Error  :  HarmonyX] Failed to patch void UnityEngine.GameObject::SetActive(bool value): System.Exception: Parameter "active" not found in method void UnityEngine.GameObject::SetActive(bool value)
```

It is a good idea to disable the text-hook that causes this method-hook to be required, because in my experience simply attempting to hook these methods, in runtimes that for whatever reason does not support it, can cause it to crash or become unstable.
