### ISSUE TITLE
How to use regex correctly?

### ISSUE THREAD

**Issue by K14Mua** [bbepis/XUnity.AutoTranslator#179]
Here are some examples of text.

> 必要性欲 0/100=Necessary libido 100\n(now 0)
> 必要性欲 0/150=Necessary libido 150\n(now 0)
> 必要性欲 0/250=Necessary libido 250\n(now 0)
> 必要性欲 0/300=Necessary libido 300\n(now 0)
> 必要性欲 0/500=Necessary libido 500\n(now 0)
> 必要性欲 0/600=Necessary libido 600\n(now 0)
> 必要性欲 0/650=Necessary libido 650\n(now 0)
> 必要性欲 0/900=Necessary libido 900\n(now 0)

The numbers 100, 150, 250, 300, 500, 600, 650 and 900 are always fixed and unchanged. And the number 0 changes from 0 to 999. What regular expression should I use in this case?

Another example

> 必要なお金 0/500=Money needed 500\n(now 0)
> 必要なお金 0/1000=Money needed 1 000\n(now 0)

In this example, the numbers 500 and 1000 are fixed again. And 0 can vary from 0 to infinity. What regular expression should I use here?

I read README.md about regular expressions. But I could not find a suitable example there ...

**Comment by gravydevsupreme** [comment]
The following regex matches the first string `^必要性欲 ([0-9]+)/([0-9]+)$` and can easily be tested [here](http://regexstorm.net/tester).

You can use this in a translation file to generate a translation like the one you provided, like so:

`r:"^必要性欲 ([0-9]+)/([0-9]+)$"=Necessary libido $2\n(now $1)`

With this knowledge, the second example should be simple.

**Comment by K14Mua** [comment]
Thanks for the answer. I'll try to do as you wrote.
