### ISSUE TITLE
How to use a translator from another site?

### ISSUE THREAD

**Issue by w6238w1** [bbepis/XUnity.AutoTranslator#18]
I'm sorry to ask you this question.  I'm going to use this translator.(https://papago.naver.com/) 
But i don't know how to use .. 
Can I modify the config file of the AutoTranslator folder?
like this
.
.
.
[Service]
Endpoint=https://papago.naver.com/?from=ja&to=ko&text

[General]
Language=ko
FromLanguage=ja

[Files]
Directory=Translation
OutputFile=Translation\_AutoGeneratedTranslations.{lang}.txt

If this is wrong, I would appreciate it if you could tell me how to use it.

**Comment by gravydevsupreme** [comment]
CustomTranslate is primarily meant to allow a developer to implement a service compatible with the plugin, so using this against an arbitrary translation service is never going to work.

The newer version has support for Papago, though.

Apologies for not having responded.
