### ISSUE TITLE
Spaces in words

### ISSUE THREAD

**Issue by Loli-Kyn** [bbepis/XUnity.AutoTranslator#183]
Good evening. How do I remove spaces after each letter? I tried changing the font, but it didn't work. Game Incubus 2 Camlann
[https://wmpics.pics/di-O6RV.jpg](url)

**Comment by gravydevsupreme** [comment]
There's no way to do that at the moment. I am guessing the text component has been created to use a static-width for each character that fits well with JA characters, but does not work well with other alphabets.

But at the moment there is no way to control this at the moment. I also do not know what options control it either, so an investigation would be needed.
