### ISSUE TITLE
Two questions re: 1) manual assets translation + XUnityAutotranslator 2) system elements in text strings

### ISSUE THREAD

**Issue by seelebrn** [bbepis/XUnity.AutoTranslator#185]
Hello ! 
First, I'd like to thank every person working on XUnity Autotranslator, because it's really a wonderful tool ! And I'd also like to apologize in advance for my English. 
That being said, I'd have two issues I can't seem to solve. I've tried searching this Issues board for an answer but I didn't really find what I was searching for. 

1) Manual Asset Edition + XUnity Autotranslator issue

For a translation project, I've been thinking about using both XUnity Autotranslator and Manual assets edition. Because this game has a "scrolling effect" on some specific parts of its text (story dialogue). I've seen GeneratePartialTranslation setting could help with this, but it tends to affect the rest of the translation in weird ways. 

So what I did was manually editing story dialogue assets and trying to process the rest of the game text elements with XUnityAT. 

But in the output file, here's the kind of result I'm getting when the plugin hooks into already manually translated assets : 

> <color%3D#FFFFFF00>I've only learnt a few days of spells, so can I deal with it with just a few tricks?</color>=<color%3D#FFFFFF00>I've only learnt a few days of spells, so can I deal with it with just a few tricks?</color>
> I<color%3D#FFFFFF00>'ve only learnt a few days of spells, so can I deal with it with just a few tricks?</color>=I<color%3D#FFFFFF00>'ve only learnt a few days of spells, so can I deal with it with just a few tricks?</color>
> I'<color%3D#FFFFFF00>ve only learnt a few days of spells, so can I deal with it with just a few tricks?</color>=I'<color%3D#FFFFFF00>ve only learnt a few days of spells, so can I deal with it with just a few tricks?</color>
> I'v<color%3D#FFFFFF00>e only learnt a few days of spells, so can I deal with it with just a few tricks?</color>=I'v<color%3D#FFFFFF00>e only learnt a few days of spells, so can I deal with it with just a few tricks?</color>
> I've<color%3D#FFFFFF00> only learnt a few days of spells, so can I deal with it with just a few tricks?</color>=I've<color%3D#FFFFFF00> only learnt a few days of spells, so can I deal with it with just a few tricks?</color>
> I've <color%3D#FFFFFF00>only learnt a few days of spells, so can I deal with it with just a few tricks?</color>=I've <color%3D#FFFFFF00>only learnt a few days of spells, so can I deal with it with just a few tricks?</color>
> I've o<color%3D#FFFFFF00>nly learnt a few days of spells, so can I deal with it with just a few tricks?</color>=I've o<color%3D#FFFFFF00>nly learnt a few days of spells, so can I deal with it with just a few tricks?</color>
> I've on<color%3D#FFFFFF00>ly learnt a few days of spells, so can I deal with it with just a few tricks?</color>=I've on<color%3D#FFFFFF00>ly learnt a few days of spells, so can I deal with it with just a few tricks?</color>
> I've onl<color%3D#FFFFFF00>y learnt a few days of spells, so can I deal with it with just a few tricks?</color>=I've onl<color%3D#FFFFFF00>y learnt a few days of spells, so can I deal with it with just a few tricks?</color>
> I've only<color%3D#FFFFFF00> learnt a few days of spells, so can I deal with it with just a few tricks?</color>=I've only<color%3D#FFFFFF00> learnt a few days of spells, so can I deal with it with just a few tricks?</color>
> I've only <color%3D#FFFFFF00>learnt a few days of spells, so can I deal with it with just a few tricks?</color>=I've only <color%3D#FFFFFF00>learnt a few days of spells, so can I deal with it with just a few tricks?</color>
> I've only l<color%3D#FFFFFF00>earnt a few days of spells, so can I deal with it with just a few tricks?</color>=I've only l<color%3D#FFFFFF00>earnt a few days of spells, so can I deal with it with just a few tricks?</color>

[To make it clear, I didn't enable GeneratePartialTranslation]

If I revert back to the original assets, only a single line is generated with [Original Text]=[MTL], as intended. 

Could there be a way to fix this ? Or maybe to ask the plugin to ignore any object without text in the original language (Chinese, in this situation). 

2) Special values in text strings

I'm sorry in advance because though I've seen a few Issues dealing with this issue on a "string per string" basis, I wonder if a more general solution exists. And maybe I've read it and just didn't understand I was looking at it. So.. yeah, sorry, if it's been already stated many times.

Some of the text lines, especially dialogue, look like this : 

"Hello {0}, how are you today ?" 
{0} pointing to the Protagonist chosen name. 

Right now, any time a new character with a different name is created, a new line will be processed and added to the output file. 

Is there a way to prevent this and somehow keep the dynamic nature of the "{0}" pointer ? 

Thank you so much in advance !

**Comment by gravydevsupreme** [comment]
So, I suspect the output of these texts is a bug that was introduced in the latest version of the plugin.

Please try this version and tell me if this behavior has been corrected:

[XUnity.AutoTranslator-BepIn-5x-4.16.0-custom.zip](https://github.com/bbepis/XUnity.AutoTranslator/files/6468899/XUnity.AutoTranslator-BepIn-5x-4.16.0-custom.zip)

About manually editing assets:
 * This will help you translate things that has variables that will be substituted in, like the example line you are mentioning yourself, but will obviously require modifying game assets and overriding them. Is the `Hello {0}, how are you today ?` text not located in your resource files?
 * Alternatively this could be done through resource redirection, but this does require implementing an asset handler that knows about the resource types of the game. (This is done in various Illusion games)

But translating the assets directly should work fine as well, and with the version provided above, I hope you no longer have the odd translation output problem.

**Comment by gravydevsupreme** [comment]
Any comment on this potential fix? I'd really like to know. :)

**Comment by seelebrn** [comment]
Oh, sorry, just saw your reply!
Indeed, reverting to the last version solved this :)

Thanks a lot for your advice :)

**Comment by gravydevsupreme** [comment]
Hopefully this problem should be solved in 4.16.1
