### ISSUE TITLE
About Autotranslate and Online Translate

### ISSUE THREAD

**Issue by Terell2018** [bbepis/XUnity.AutoTranslator#186]
I just notice the different between autotranslate and online translate when it translate it have a different synonym.

example.

bing translate
autotranslate:It would have already been overwhelmed ...?
online translate:You've already looked at each other enough...?

google translate:
autotranslate:It would have already been overwhelmed ...?
online translate:You've already stared at each other ...?

deepl translate:
autotranslate:It would have already been overwhelmed ...?
online translate:Haven't we looked at each other enough already: ......?

it would be nice it there was a features like sync the translate from online.

**Comment by gravydevsupreme** [comment]
The plugin tries to emulated the API calls made towards their services as best it can. That being said, I am a bit surprised that there are differences to other translation services than Google.
