### ISSUE TITLE
deepL API

### ISSUE THREAD

**Issue by Cinder4815162342** [bbepis/XUnity.AutoTranslator#187]
So, deepL has a free plan for devs that lets you get an API key.
https://i.imgur.com/DEjQDNj.png

As it stands, I haven't been able to figure out how to get it to translate for me. I've entered the API into the config, and if I open autotranslator in-client then it lets me pick it (usually grayed out if no api key). But it still doesn't translate it if I choose the API method as the only option. I also noticed "ExecutableLocation=" in the config for autotranslator, but didn't find any documentation on it.

**Comment by gravydevsupreme** [comment]
I was not aware they had added a free tier for their API. Needless to say, I have not tested that. I will see if I can get that working. You can ignore the `ExecutableLocation` option.

**Comment by gravydevsupreme** [comment]
Please try this:

[XUnity.AutoTranslator-BepIn-5x-4.16.0.zip](https://github.com/bbepis/XUnity.AutoTranslator/files/6481262/XUnity.AutoTranslator-BepIn-5x-4.16.0.zip)

Start it up once. Then edit the configuration for DeepLLegitimate such that it sets `Free=True`

**Comment by Cinder4815162342** [comment]
I've tried for quite a while to get the game working with bepinex, but unfortunately I seem to be incapable. I used the reipatcher version before and it worked the way I expected it. But it just doesn't seem to be running the autotranslator? At least nothing happens when I try alt+0 or alt+1. I also found that a bepinex cfg is generated, but I can't find the autotranslator config anywhere. Neither can I find the output log that the bepinex installation guide mentions.

**Comment by gravydevsupreme** [comment]
[XUnity.AutoTranslator-ReiPatcher-4.16.0.zip](https://github.com/bbepis/XUnity.AutoTranslator/files/6481373/XUnity.AutoTranslator-ReiPatcher-4.16.0.zip)

**Comment by Cinder4815162342** [comment]
It works! Thanks a lot.

**Comment by Ayydrill** [comment]
Hey guys, how do I get this working exactly? I have BepInEx present already in the game I'm attempting to use this on. Sorry for the noob question, but I really wanna get DeepL working.

**Comment by gravydevsupreme** [comment]
You need to setup a free DeepL API account (not Pro). Then just:

> 
> 
> Please try this:
> 
> [XUnity.AutoTranslator-BepIn-5x-4.16.0.zip](https://github.com/bbepis/XUnity.AutoTranslator/files/6481262/XUnity.AutoTranslator-BepIn-5x-4.16.0.zip)
> 
> Start it up once. Then edit the configuration for DeepLLegitimate such that it sets `Free=True`

Also, you must, of course, specify your personal key in the configuration.

**Comment by Ayydrill** [comment]
> You need to setup a free DeepL API account (not Pro). Then just:
> 
> > Please try this:
> > [XUnity.AutoTranslator-BepIn-5x-4.16.0.zip](https://github.com/bbepis/XUnity.AutoTranslator/files/6481262/XUnity.AutoTranslator-BepIn-5x-4.16.0.zip)
> > Start it up once. Then edit the configuration for DeepLLegitimate such that it sets `Free=True`
> 
> Also, you must, of course, specify your personal key in the configuration.

When I try to sign up, it tells me my country is not supported? It just jumps to the "DeepL is only supported in these countries:" segment. :/
I don't see an option anywhere for a free account. So the user-specific API is only given when an account is made I assume.

**Comment by gravydevsupreme** [comment]
You need to sign up for the DeepL API "For developers" as shown below.

![DeepLPlans](https://user-images.githubusercontent.com/51834260/118676624-d9949600-b7fb-11eb-94df-1a501444af68.png)

Do note that in general DeepL supports fewer languages than Google/Bing, etc.

Also note that you can also use non-subscription option already available in the plugin which should be close to the same.

**Comment by Ayydrill** [comment]
Hey gravy, thanks for the reply. I'm not even able to access this page, unfortunately. Every time I try to click on the free plan it just tells me my country isn't supported because I live in Asia. :(

**Comment by gravydevsupreme** [comment]
Fix now included in 4.16.1-
