### ISSUE TITLE
Regarding Thai translation ? 

### ISSUE THREAD

**Issue by dilok0005** [bbepis/XUnity.AutoTranslator#194]
When I translate ONEONE1 サムライヴァンダリズム, many words are translated as □□□□□□□.

How can I fix it?

(I'm not very good at English)

**Comment by u06gji4jo3** [comment]
#191

**Comment by gravydevsupreme** [comment]
I'd recommend following this issue, since I have tried and am still unable to generate a working font for the game.

https://github.com/bbepis/XUnity.AutoTranslator/issues/191

**Comment by gravydevsupreme** [comment]
Close this as it is the same issue as the other.
