### ISSUE TITLE
Papago translate endpoint does not work

### ISSUE THREAD

**Issue by shkim101** [bbepis/XUnity.AutoTranslator#198]
![K-049](https://user-images.githubusercontent.com/25957290/122067933-f9e74e80-cdc1-11eb-93e1-2140de03aacb.jpg)

I am not sure, but it seems like Papago API has changed.

**Comment by gravydevsupreme** [comment]
Well, that seems like a pain. Especially given I was not the one that implemented the current support the plugin has for it, when it broke the last time. https://github.com/bbepis/XUnity.AutoTranslator/pull/109, 

Will see if I can find some time to fix it, unless someone else fixes it before me. ^_^
