### ISSUE TITLE
Cannot hook texts in-game

### ISSUE THREAD

**Issue by Asyente** [bbepis/XUnity.AutoTranslator#201]
Hi

I'm using XUnity.AutoTranslator-ReiPatcher-4.16.3 to translate a Japanese game into Korean.
I followed the installation manual properly, but it doesn't seem to hook any of the texts in-game.
This is what it looks like when I toggle XUnity AutoTranslator UI.

<img width="667" alt="화면 캡처 2021-06-22 021819" src="https://user-images.githubusercontent.com/86253809/122804063-60102c00-d302-11eb-99eb-68126affe629.png">

I assume there is nothing wrong with the game since there are many people who succeeded in translating this game with XUnity.AutoTranslator-ReiPatcher.

I tried this multiple times, and at one time I succeeded in translating some parts of the texts into □□□□□.
(And I tried OverrideFontTextMeshPro=arialuni_sdf_u2018, which didn't work.)
So I deleted the file and tried again, only to find all the texts back in Japanese.

I've been struggling with this problem for about a week and I need your help.

If you need any more information to solve this problem, please note them in your reply.
The following is my AutoTranslator\Config.ini file.

[Service]
Endpoint=PapagoTranslate
FallbackEndpoint=

[General]
Language=ko
FromLanguage=ja

[Files]
Directory=Translation\{Lang}\Text
OutputFile=Translation\{Lang}\Text\_AutoGeneratedTranslations.txt
SubstitutionFile=Translation\{Lang}\Text\_Substitutions.txt
PreprocessorsFile=Translation\{Lang}\Text\_Preprocessors.txt

[TextFrameworks]
EnableIMGUI=True
EnableUGUI=True
EnableNGUI=True
EnableTextMeshPro=True
EnableTextMesh=False
EnableFairyGUI=True

[Behaviour]
MaxCharactersPerTranslation=1000
IgnoreWhitespaceInDialogue=False
IgnoreWhitespaceInNGUI=False
MinDialogueChars=20
ForceSplitTextAfterCharacters=0
CopyToClipboard=False
MaxClipboardCopyCharacters=2500
EnableUIResizing=True
EnableBatching=True
UseStaticTranslations=True
OverrideFont=
OverrideFontSize=
OverrideFontTextMeshPro=
ResizeUILineSpacingScale=
ForceUIResizing=False
IgnoreTextStartingWith=\u180e;
TextGetterCompatibilityMode=False
GameLogTextPaths=
RomajiPostProcessing=ReplaceMacronWithCircumflex;RemoveApostrophes;ReplaceHtmlEntities
TranslationPostProcessing=ReplaceMacronWithCircumflex;ReplaceHtmlEntities
CacheRegexPatternResults=False
CacheRegexLookups=False
CacheWhitespaceDifferences=False
GenerateStaticSubstitutionTranslations=False
GeneratePartialTranslations=False
EnableTranslationScoping=False
EnableSilentMode=True
BlacklistedIMGUIPlugins=
EnableTextPathLogging=False
OutputUntranslatableText=False
IgnoreVirtualTextSetterCallingRules=False
MaxTextParserRecursion=1
HtmlEntityPreprocessing=True
HandleRichText=True
EnableTranslationHelper=False
ForceMonoModHooks=False
InitializeHarmonyDetourBridge=True
RedirectedResourceDetectionStrategy=AppendMongolianVowelSeparatorAndRemoveAll
OutputTooLongText=False
TemplateAllNumberAway=False
ReloadTranslationsOnFileChange=False
DisableTextMeshProScrollInEffects=False
CacheParsedTranslations=False

[Texture]
TextureDirectory=Translation\{Lang}\Texture
EnableTextureTranslation=False
EnableTextureDumping=False
EnableTextureToggling=False
EnableTextureScanOnSceneLoad=False
EnableSpriteRendererHooking=False
LoadUnmodifiedTextures=False
DetectDuplicateTextureNames=False
DuplicateTextureNames=
EnableLegacyTextureLoading=False
TextureHashGenerationStrategy=FromImageName
CacheTexturesInMemory=True
EnableSpriteHooking=False

[ResourceRedirector]
PreferredStoragePath=Translation\{Lang}\RedirectedResources
EnableTextAssetRedirector=False
LogAllLoadedResources=False
EnableDumping=False
CacheMetadataForAllFiles=True

[Http]
UserAgent=
DisableCertificateValidation=True

[TranslationAggregator]
Width=1000
Height=155
EnabledTranslators=

[Debug]
EnableConsole=False

[Migrations]
Enable=True
Tag=4.16.3

[Baidu]
BaiduAppId=
BaiduAppSecret=
DelaySeconds=1

[BingLegitimate]
OcpApimSubscriptionKey=

[Custom]
Url=

[DeepL]
ExecutableLocation=
MinDelaySeconds=2
MaxDelaySeconds=7

[DeepLLegitimate]
ExecutableLocation=
ApiKey=
Free=False

[ezTrans]
InstallationPath=

[Google]
ServiceUrl=

[GoogleV2]
ServiceUrl=
RPCID=MkEWBc
VERSION=boq_translate-webserver_20210323.10_p0
UseSimplest=False

[GoogleLegitimate]
GoogleAPIKey=

[LecPowerTranslator15]
InstallationPath=

[Watson]
Url=
Key=

[Yandex]
YandexAPIKey=

**Comment by gravydevsupreme** [comment]
I can't help you without knowing the game.

If you've had it working at some point in the past, perhaps you can try resetting the config by deleting the ini file and retracing your steps.

**Comment by gravydevsupreme** [comment]
You will probably need to change the font using `FallbackFontTextMeshPro`. Closing this issue for now.
