### ISSUE TITLE
[Error  :XUnity.AutoTranslator] Could not find the configured endpoint 'GoogleTranslate'.

### ISSUE THREAD

**Issue by m1371339094** [bbepis/XUnity.AutoTranslator#209]
I had this issue in the game when I put the new version of XUnity.AutoTranslator

**Comment by m1371339094** [comment]
[output_log.txt](https://github.com/bbepis/XUnity.AutoTranslator/files/6889345/output_log.txt)

**Comment by gravydevsupreme** [comment]
Can confirm the problem. For now, just press ALT+0 and select a translator. Will fix this weekend.

**Comment by gravydevsupreme** [comment]
Fixed in latest release.
