### ISSUE TITLE
failed create shortcut using SetupReiPatcherAndAutoTranslator

### ISSUE THREAD

**Issue by SMaiLubis** [bbepis/XUnity.AutoTranslator#21]
![issue](https://user-images.githubusercontent.com/46646098/54314652-963cac80-461f-11e9-8909-8ee9c9b7537c.jpg)
when i run SetupReiPatcherAndAutoTranslator.exe, it  freeze and i get this error
can you help me?

**Comment by trixyl** [comment]
u can just create the shortcut urself after running the failing installer

change the shortcut properties, 'Target' and 'Start in' to this:

Target: "D:\Program Files (x86)\ASTRONAUTS_SIRIUS\GUILDMASTER\ReiPatcher\ReiPatcher.exe" -c "GuildMaster_Game.ini"
Start in: "D:\Program Files (x86)\ASTRONAUTS_SIRIUS\GUILDMASTER\ReiPatcher"

or u can use IPA or BepInEx packages as they are both very easy to install. Then just install this as a plugin to those after that

**Comment by SMaiLubis** [comment]
It works, thanks. 
But why my text still in Japanese?

**Comment by trixyl** [comment]
just got around to trying out the game

it also did not work for me but it seems that if u disable certificate validation in the config file then it starts working:

```
[Http]
DisableCertificateValidation=True
```

**Comment by SMaiLubis** [comment]
OK thanks, i will try it.
In the end, we need wait for fans or official translation to play the game 100% English. 
Hahahahaha.
