### ISSUE TITLE
AutoTranslator doesn't initialises using MelonLoader

### ISSUE THREAD

**Issue by kadeler** [bbepis/XUnity.AutoTranslator#212]
I'm trying to use it on a map made on unity, but it seems to run into some issues
[Latest.log](https://github.com/bbepis/XUnity.AutoTranslator/files/7009364/Latest.log)

**Comment by gravydevsupreme** [comment]
Please try the latest version from [here](https://github.com/bbepis/XUnity.AutoTranslator/issues/159), with the latest version (0.4.3) of MelonLoader and report if that fixes the issue.

**Comment by kadeler** [comment]
At least it stopped crashing, but still, how's that translation google's?
[image: image.png]
I can type the same text in google translator, but the outcome will be
better, what gives?
And sometimes it doesn't even catch text
[image: image.png]
Am i doing something wrong?

сб, 21 авг. 2021 г. в 12:06, gravydevsupreme ***@***.***>:

**Comment by kadeler** [comment]
Nevermind, my config got reset, so that's why it worked badly, but i have another issue...
![image](https://user-images.githubusercontent.com/20907848/130321355-6b9dc4d1-9748-4726-843f-bc3ab8e58861.png)
Seems like label object doesn't get resized, so i cant see the rest of the text

**Comment by kadeler** [comment]
I had to use ForceUIResizing flag, issue is closed
