### ISSUE TITLE
Can you help me with this problem?

### ISSUE THREAD

**Issue by nonamebatbai** [bbepis/XUnity.AutoTranslator#213]
https://github.com/akintos/KingmakerKoreanFont 
this is mod kingmaker korean font. made by Korean people. Can you show me how to get korean font?
I tried to contact them but they did not reply.

**Comment by gravydevsupreme** [comment]
I'm not sure what the question is. But Korean font should be included in the `TMP_Font_AssetBundles.zip` on the release pages. But those may or may not work depending on version conflicts. The only alternative is to build the font asset yourself.

https://github.com/bbepis/XUnity.AutoTranslator/issues/182#issuecomment-841540202

But I know for a fact you asked for this before, so I am not sure how much of a help it is.

**Comment by gravydevsupreme** [comment]
Using `FallbackFontTextMeshPro` instead of `OverrideFontTextMeshPro`, which is available in v5.0.0 and later, may produce more predictable results.
