### ISSUE TITLE
Only the first letter is printed in 2byte characters.

### ISSUE THREAD

**Issue by orangespoons** [bbepis/XUnity.AutoTranslator#219]
Game: Twilight Struggle
The phenomenon of showing only the first letter appears in all 2-byte characters.
1-byte characters such as English and Russian are normally written, but only the first letter is printed in Chinese/Japanese/Korean.
What should I do?
** If you open _AutoGeneratedTranslations.txt, you can see that the translation is done properly.
** I changed some options in AutoTranslatorConfig.ini.
    - Language=ko
    - FromLanguage=en
    - OverrideFontTextMeshPro=arialuni_sdf_u2019
    - 
![1](https://user-images.githubusercontent.com/54737449/134136126-b7203cd1-2aed-43cf-9296-a3bf48dd6cc5.PNG)
![2](https://user-images.githubusercontent.com/54737449/134136140-14bd4bea-e4c9-49ee-b7e1-9ce51d633c5e.PNG)

**Comment by gravydevsupreme** [comment]
I am afraid I have no idea what might cause something like that. I would have to take a closer look at the game, but I do not currently have the time for that.

**Comment by gravydevsupreme** [comment]
You should try `FallbackFontTextMeshPro` instead of `OverrideFontTextMeshPro`. That may produce a more predictable result.

**Comment by orangespoons** [comment]
It doesn't work.
However, I'm using the EnableTextMeshPro option to False.
because I've found that the TextMeshPro part used in the game is small.
