### ISSUE TITLE
i cant use lec

### ISSUE THREAD

**Issue by pewzx** [bbepis/XUnity.AutoTranslator#22]
how edit config XUnity.AutoTranslator-ReiPatcher to use LEC offline?

**Comment by trixyl** [comment]
u just need to edit the AutoTranslatorConfig.ini file to specify the path to where u installed lec.see below for example

```
[LecPowerTranslator15]
InstallationPath=C:\Program Files (x86)\Power Translator 15
```

**Comment by qaz1314520qaz** [comment]
> how edit config XUnity.AutoTranslator-ReiPatcher to use LEC offline?

Counld  you use LEC offline successed?

**Comment by purposelycryptic** [comment]
Not sure how helpful this is, but just to answer @qaz1314520qaz's question, and not leave the issue hanging open in case anyone else has the same question in the future:

I am successfully using LEC offline, and have successfully tested doing so with both the ReiPatcher and BepInEx versions of XUnity.AutoTranslator.

Just as @trixyl explained, it simply involves pasting your local path to LEC into the proper spot in the **AutoTranslatorConfig.ini** file, and then choosing it as your Translator.

**Comment by gravydevsupreme** [comment]
The latest version now supports determining the LEC installation path at runtime, rather than requiring user input.

Closing this issue as resolved.
