### ISSUE TITLE
TMP problem in Koikatsu Sunshine

### ISSUE THREAD

**Issue by mikimoe** [bbepis/XUnity.AutoTranslator#222]
When I used Textmeshpro font in Koikatsu Sunshine some text messed up. I've tried 3 sdf font but the problem is the same. Here
is the screenshot.
[https://upload.cc/i1/2021/09/26/TL71mJ.png](url)

**Comment by gravydevsupreme** [comment]
I would make a guess that the font provided in the plugin is simply not up to the task for KKS. If I am not mistaken @ScrewThisNoise generated a compatible font for KKS with CJK included in his BetterRepack. I could be wrong though, as I have not really been following anything lately.

**Comment by mikimoe** [comment]
Well I have found the reason some days ago. The game auto changes the font and its shader when your mouse moves to  some buttons. But plugin may not update the shader. I didn't know how to solve it so I changed some monobehaviour files in game resouce. It did work but I thought we need a better solution.

**Comment by gravydevsupreme** [comment]
The next version of the plugin will have a new way to modify the font used for TextMesh Pro. Hopefully this will be more compatible with various games.

**Comment by gravydevsupreme** [comment]
v5.0.0 now provides `FallbackFontTextMeshPro`, which should produce better results than `OverrideFontTextMeshPro`. It's used in the same way and should not be used at the same time.
