### ISSUE TITLE
BepInEx with IL2CPP not working

### ISSUE THREAD

**Issue by linland-h** [bbepis/XUnity.AutoTranslator#226]
I'm trying to use auto translator on a game called  魔女と猫の隠れ里 and I have installed BepInEx IL2CPP plugin manager successfully, After I extracted the plugins into the game directory and launched it, the plugin did not generate the Translation folder under /BepInEx/, tranlation did not work either.

**Comment by baoenzo** [comment]
Use MelonLoader. It will work

**Comment by linland-h** [comment]
> Use MelonLoader. It will work

It works, thank you

**Comment by i3oi3o** [comment]
May I ask for your XUnity.AutoTranslator and MelonLoader version?

I can only make XUnity.AutoTranslator 4.18.0 (The early il2cpp version) and MelonLoader 0.4.3 work together.
