### ISSUE TITLE
Translated text is not fully displayed in game on IL2CPP

### ISSUE THREAD

**Issue by ivdos** [bbepis/XUnity.AutoTranslator#244]
I use XUnity.AutoTranslator-MelonMod-4.18.0, melon-loader 0.5.2 text is translated but not fully shown. Outputs the same number of characters as in the original text. Game 戦う魔法少女RPGガールズディフェンス
Screenshots: https://imgur.com/a/uD4FMZu
Also, the option to copy to the clipboard does not work.

**Comment by gravydevsupreme** [comment]
So this is definitely related to UTAGE, since I've dealt with this issue for Mono as well. Will see if I can get it working for this as well by introducing the same code and hooks.

**Comment by gravydevsupreme** [comment]
How did you get MelonLoader to load this game? Refuses to load it for me.

![image](https://user-images.githubusercontent.com/51834260/147852482-3550be54-40e0-46e0-b2e3-6a6de24c62c0.png)

**Comment by gravydevsupreme** [comment]
5.0.0-beta12 should fix this issue. Closing this issue for now.
