### ISSUE TITLE
FallbackFontTextMeshPro option not working in melonloader

### ISSUE THREAD

**Issue by orangespoons** [bbepis/XUnity.AutoTranslator#248]
Game: [RJ297937] HolyKnightRicca_v105ja
Melonloader: x64 0.5.2
Autotranslator: MelonMod-IL2CPP-5.0.0
ini file: https://pastebin.com/pWMaDj2D
Error log(melonloader): https://pastebin.com/UQf14tHW
Fallback fontasset bundle: [nanumgothicsdf140](https://mega.nz/file/XwMyHTSY#MkFYtxsmaLmVFkWLgQth8AwaPmTshFM-ZBxq__Nfp8k)
Uncensored Mod: [MelonLoaderFTHKRTWS](https://mega.nz/file/f9dwiRCZ#CQ_IoTnF-7xrQscDYVCxh5iaC9qA1zE3f5X07ejIbTY)

FallbackFontTextMeshPro option works with BepinEx, but not with Melonloader.
I am unable to use BepInEx because the Uncensored mod was developed for Melonloader.
I tried to open the dll file with dnspy. It's a simple mod, but I can't port it because I don't know much about C#.
[BepInEx.MelonLoader.Loader](https://github.com/BepInEx/BepInEx.MelonLoader.Loader) didn't work either.
So I would like you to take a look at the problem with MelonLoader.
thank you!

**Comment by gravydevsupreme** [comment]
Try this instead.
[XUnity.AutoTranslator-MelonMod-IL2CPP-5.0.0.zip](https://github.com/bbepis/XUnity.AutoTranslator/files/7835700/XUnity.AutoTranslator-MelonMod-IL2CPP-5.0.0.zip)

**Comment by orangespoons** [comment]
> Try this instead. [XUnity.AutoTranslator-MelonMod-IL2CPP-5.0.0.zip](https://github.com/bbepis/XUnity.AutoTranslator/files/7835700/XUnity.AutoTranslator-MelonMod-IL2CPP-5.0.0.zip)

It works really well. thank you!
