### ISSUE TITLE
Trouble with ResourceRedirector callbacks

### ISSUE THREAD

**Issue by raqu73** [bbepis/XUnity.AutoTranslator#249]
Hello. I'm struggling to get ResourceRedirector to work. For now I'm just testing a simple callback method that logs to the console, but no logging is ever done.

Here is the entire plugin as it stands:
```
using BepInEx;
using XUnity.ResourceRedirector;

namespace TestPlugin
{
    [BepInPlugin(PluginInfo.PLUGIN_GUID, PluginInfo.PLUGIN_NAME, PluginInfo.PLUGIN_VERSION)]
    [BepInDependency("gravydevsupreme.xunity.resourceredirector")]
    public class TestPlugin : BaseUnityPlugin
    {
        private void Awake()
        { 
            Logger.LogInfo($"Plugin {PluginInfo.PLUGIN_GUID} is loaded.");
            ResourceRedirection.RegisterAssetLoadedHook(HookBehaviour.OneCallbackPerResourceLoaded, AssetLoaded);
        }

        private void AssetLoaded(AssetLoadedContext context)
        {
            Logger.LogInfo("Callback.");
        }
    }
}
```

And here is the logged output:
[LogOutput.log](https://github.com/bbepis/XUnity.AutoTranslator/files/7885390/LogOutput.log)

Not sure exactly what I could be doing wrong here. Tried making the method public, running the Complete method, altering the context... No results in any case. Am I missing something?

**Comment by gravydevsupreme** [comment]
I can certainly see in the log some objects are being loaded. I think it may likely caused by them be loaded as resources rather than assets.

Try using `RegisterResourceLoadedHook` as well.

Take a look at: https://github.com/bbepis/XUnity.AutoTranslator/blob/master/src/XUnity.AutoTranslator.Plugin.Core/AssetRedirection/AssetLoadedHandlerBaseV2.cs#L23

**Comment by raqu73** [comment]
Yep, seems like that was it. Apologies for such a simple error, was thrown off by the logs specifying Asset. Thanks for clearing that up!
