### ISSUE TITLE
Koikatsu different meaning word from auto-translator and online translator website.

### ISSUE THREAD

**Issue by Terell2018** [bbepis/XUnity.AutoTranslator#25]
It kind of strange when the auto-translator the word. but when i copy and paste on google and bing from _AutoGeneratedTranslations.en on online translator website. some word have different meaning.

**Comment by TokcDK** [comment]
I suppose maybe it is because xunity.autotranslator loading static translation but on browser page using neurotranslation which is in most causes is much better.

**Comment by gravydevsupreme** [comment]
I cannot explain the issue that you are seeing here.

The static translation provided in the plugin are simply common manual translation to prevent the plugin from going online in some very specific games from a very specific company.

When accessing the translation API's it uses the exact same API's as the websites, which means what you see in the plugin and on the website should be the same.

I am closing this for now, but if you still think it is an issue, you can open it again with more information on the issue.
