### ISSUE TITLE
Please help me with regex

### ISSUE THREAD

**Issue by Loli-Kyn** [bbepis/XUnity.AutoTranslator#252]
Please help me with regex, otherwise I don't understand it well, I need these lines not to be repeated, only the digit changes in this line:
毒薬の瓶×1=Бутылка с ядом ×1
獲得したレッドソウル 45=Красная душа 45

**Comment by anivd84** [comment]
in the AutoTranslatorConfig.ini file, I would recommend enabling the parameters
TemplateAllNumberAway=True
ReloadTranslationsOnFileChange=True
 try it
sr:"^([\S\s]+)×(\d+)$=$1×$2
sr:"^([\S\s]+)\s(\d+)$=$1 $2

**Comment by Loli-Kyn** [comment]
> in the AutoTranslatorConfig.ini file, I would recommend enabling the parameters TemplateAllNumberAway=True ReloadTranslationsOnFileChange=True
> 
> P.S. if enable TemplateAllNumberAway=True then the strings will be converted to 毒薬の瓶×{{A}}=Бутылка с ядом ×{{A}} 獲得したレッドソウル {{A}}=Красная душа {{A}} and you can leave it like that, or try this: sr:"^([\S\s]+)×(\d+)$"=$1×$2 sr:"^([\S\s]+)\s(\d+)$"=$1 $2 there may be more templates, but the meaning is the same...

How do I add these words: 
Gold Coin = Gold
Slave=Slaves
Poison Bottle = Poison
He constantly translates these words in a new way

**Comment by Loli-Kyn** [comment]
I had an older version so the setting "TemplateAllNumberAway=True
ReloadTranslationsOnFileChange=True".
It didn't work for me
