### ISSUE TITLE
Ignore Specific Text Translation

### ISSUE THREAD

**Issue by darrevan92** [bbepis/XUnity.AutoTranslator#257]
Is there a way that translator ignore translate specific path
![translate](https://user-images.githubusercontent.com/99098548/152659159-440ac3eb-fdc3-4775-97ca-3ed6729b3998.png)
![Orginal](https://user-images.githubusercontent.com/99098548/152659218-23701f3d-d718-4d1c-ad37-6c342bb6ab88.png)
As you can see text are race specific and no valid translation is possible.
I already know path of text. thanks to runtime editor so Which Command I should add to translation folder for ignore these text to translate

**Comment by gravydevsupreme** [comment]
It is not currently possible to ignore a component by it's path, although that could certainly be added.

For now, a workaround might be to simple create a non-translation in the translation files, eg.:

```
Ignore this=Ignore this
```
