### ISSUE TITLE
What tags can I use?

### ISSUE THREAD

**Issue by orangespoons** [bbepis/XUnity.AutoTranslator#260]
Please tell me about tags that can be used in Autotranslator.
Although it is html tag style, but it seems to be quite different from general html tag.
There are only a few that I know of.

> <size%3D50%></size>
-> hmm... reduce by percent?

> <size%3D25></size>
-> It's probably a fixed font size.

> <color%3Dgrey>YAY</color>
-> change by colorname?

> <color%3D#a8a8a8>UnityEngine</color>
 -> change by colorcode?

> <space%3D0.3em><voffset%3D-0.1em><size%3D130%><sprite name%3D"jingli"><size%3D100%></voffset><space%3D0.3em>
-> wtf

Anything else besides these?
And what does the %3D after the "size" mean?
Also, does this option apply to both TextMeshPro (SDF) and TextMesh (TTF)?

I have a lot of questions. sorry.
If you give me a link with that information, I'll read it.
Thanks.

**Comment by gravydevsupreme** [comment]
%3D is just a terrible escaping decision by me made a long time ago. It just means =

The supported tags are different depending on the text framework and version. For example, I can come up with three different frameworks that all does it differently:
 * UGUI https://docs.unity3d.com/Packages/com.unity.ugui@1.0/manual/StyledText.html
 * TextMesh Pro http://digitalnativestudios.com/textmeshpro/docs/rich-text/ (probably outdated)
 * UTAGE (can't find the link at the moment, but also mostly irrelevant)

Tags cannot just be used anywhere. Only in components in which they are supported by the original game implementation.

**Comment by orangespoons** [comment]
> %3D is just a terrible escaping decision by me made a long time ago. It just means =

Oh, I understood.
Thanks for useful links.
