### ISSUE TITLE
Would it be possible to add an option where the program translates all the text of the game beforehand, instead of doing it in real time?

### ISSUE THREAD

**Issue by jos582** [bbepis/XUnity.AutoTranslator#267]
for example, the add-on "Translator3000" by user NyashniyVladya allows to translate Ren'Py games automatically, but also has an option that allows to scan and translate all the game text at once.

**Comment by gravydevsupreme** [comment]
These types of games usually has a pre-defined resource structure, allowing you to programmatically scan them for translatable texts. Unity is not the same in this regard and games resources are stored in many different ways, making this not possible.
