### ISSUE TITLE
external fonts

### ISSUE THREAD

**Issue by mem0ric** [bbepis/XUnity.AutoTranslator#27]
Is it possible to integrate external fonts in the application when translating and how to do it. I understand it is responsible for "OverrideFont=" how to use it.

**Comment by trixyl** [comment]
if u specify a font that is not supported, the plugin will print out which fonts are supported which are just the fonts installed in the OS.

i get the following list but this may not be the same for you:

`The specified override font is not available. Available fonts: Adobe Arabic, Adobe Arabic Bold, Adobe Arabic Italic, Adobe Arabic Bold Italic, Adobe Caslon Pro, Adobe Caslon Pro Bold, Adobe Caslon Pro Italic, Adobe Caslon Pro Bold Italic, Adobe Devanagari, Adobe Devanagari Bold, Adobe Devanagari Italic, Adobe Devanagari Bold Italic, Adobe Fan Heiti Std Bold, Adobe Fangsong Std, Adobe Garamond Pro, Adobe Garamond Pro Italic, Adobe Gothic Std Bold, Adobe Hebrew, Adobe Hebrew Bold, Adobe Hebrew Italic, Adobe Hebrew Bold Italic, Adobe Heiti Std, Adobe Kaiti Std, Adobe Ming Std, Adobe Myungjo Std, Adobe Naskh, Adobe Song Std, Agency FB, Agency FB Bold, Algerian, Arial, Arial Bold, Arial Italic, Arial Bold Italic, Arial Rounded MT Bold, Arial Unicode MS, Bahnschrift, Baskerville Old Face, Bauhaus 93, Bell MT, Bell MT Bold, Bell MT Italic, Berlin Sans FB, Berlin Sans FB Bold, Berlin Sans FB Demi Bold, Bernard MT Condensed, Birch Std, Blackadder ITC, Blackoak Std, Bodoni MT, Bodoni MT Bold, Bodoni MT Italic, Bodoni MT Bold Italic, Book Antiqua, Book Antiqua Bold, Book Antiqua Italic, Book Antiqua Bold Italic, Bookman Old Style, Bookman Old Style Bold, Bookman Old Style Italic, Bookman Old Style Bold Italic, Bookshelf Symbol 7, Bradley Hand ITC, Britannic Bold, Broadway, Brush Script MT Italic, Brush Script Std, Buxton Sketch, Cabin Condensed, Cabin Condensed Bold, Calibri, Calibri Bold, Calibri Italic, Calibri Bold Italic, Californian FB, Californian FB Bold, Californian FB Italic, Calisto MT, Calisto MT Bold, Calisto MT Italic, Calisto MT Bold Italic, Cambria, Cambria Bold, Cambria Italic, Cambria Bold Italic, Cambria Math, Candara, Candara Bold, Candara Italic, Candara Bold Italic, Castellar, Centaur, Century, Century Gothic, Century Gothic Bold, Century Gothic Italic, Century Gothic Bold Italic, Century Schoolbook, Century Schoolbook Bold, Century Schoolbook Italic, Century Schoolbook Bold Italic, Chaparral Pro, Chaparral Pro Bold, Chaparral Pro Italic, Chaparral Pro Bold Italic, Charlemagne Std Bold, Chiller, Colonna MT, Comic Sans MS, Comic Sans MS Bold, Comic Sans MS Italic, Comic Sans MS Bold Italic, Consolas, Consolas Bold, Consolas Italic, Consolas Bold Italic, Constantia, Constantia Bold, Constantia Italic, Constantia Bold Italic, Cooper Black, Cooper Std, Cooper Std Italic, Copperplate Gothic Bold, Copperplate Gothic Light, Corbel, Corbel Bold, Corbel Italic, Corbel Bold Italic, Courier New, Courier New Bold, Courier New Italic, Courier New Bold Italic, Curlz MT, DengXian, Ebrima, Ebrima Bold, Edwardian Script ITC, Elephant, Elephant Italic, Engravers MT, Eras Bold ITC, Eras Demi ITC, Eras Light ITC, Eras Medium ITC, Felix Titling, Footlight MT Light, Forte, Franklin Gothic Book, Franklin Gothic Book Italic, Franklin Gothic Demi, Franklin Gothic Demi Italic, Franklin Gothic Demi Cond, Franklin Gothic Heavy, Franklin Gothic Heavy Italic, Franklin Gothic Medium, Franklin Gothic Medium Italic, Franklin Gothic Medium Cond, Freestyle Script, French Script MT, Gabriola, Gadugi, Gadugi Bold, Garamond, Garamond Bold, Garamond Italic, Georgia, Georgia Bold, Georgia Italic, Georgia Bold Italic, Giddyup Std, Gigi, Gill Sans MT, Gill Sans MT Bold, Gill Sans MT Italic, Gill Sans MT Bold Italic, Gill Sans MT Condensed, Gill Sans MT Ext Condensed Bold, Gill Sans Ultra Bold, Gill Sans Ultra Bold Condensed, Gloucester MT Extra Condensed, Goudy Old Style, Goudy Old Style Bold, Goudy Old Style Italic, Goudy Stout, Haettenschweiler, Harlow Solid Italic Italic, Harrington, High Tower Text, High Tower Text Italic, Hobo Std, HoloLens MDL2 Assets, Impact, Imprint MT Shadow, Informal Roman, Ink Free, Javanese Text, Jokerman, Juice ITC, Kozuka Gothic Pr6N, Kozuka Gothic Pr6N Bold, Kozuka Gothic Pro, Kozuka Gothic Pro Bold, Kozuka Mincho Pr6N, Kozuka Mincho Pr6N Bold, Kozuka Mincho Pro, Kozuka Mincho Pro Bold, Kristen ITC, Kunstler Script, Leelawadee UI, Leelawadee UI Bold, Letter Gothic Std, Letter Gothic Std Bold, Letter Gothic Std Italic, Letter Gothic Std Bold Italic, Lithos Pro, Lithos Pro Bold, Lucida Bright, Lucida Bright Bold, Lucida Bright Italic, Lucida Bright Bold Italic, Lucida Calligraphy, Lucida Console, Lucida Fax, Lucida Fax Bold, Lucida Fax Italic, Lucida Fax Bold Italic, Lucida Handwriting, Lucida Sans, Lucida Sans Bold, Lucida Sans Italic, Lucida Sans Bold Italic, Lucida Sans Typewriter, Lucida Sans Typewriter Bold, Lucida Sans Typewriter Italic, Lucida Sans Typewriter Bold Italic, Lucida Sans Unicode, MS Gothic, MS Mincho, MS Outlook, MS PGothic, MS PMincho, MS Reference Sans Serif, MS Reference Specialty, MS UI Gothic, MT Extra, MV Boli, Magneto Bold, Maiandra GD, Malgun Gothic, Malgun Gothic Bold, Marlett, Matura MT Script Capitals, Meiryo, Meiryo Bold, Meiryo Italic, Meiryo Bold Italic, Meiryo UI, Meiryo UI Bold, Meiryo UI Italic, Meiryo UI Bold Italic, Mesquite Std, Microsoft Himalaya, Microsoft JhengHei, Microsoft JhengHei Bold, Microsoft JhengHei UI, Microsoft JhengHei UI Bold, Microsoft MHei, Microsoft MHei Bold, Microsoft NeoGothic, Microsoft NeoGothic Bold, Microsoft New Tai Lue, Microsoft New Tai Lue Bold, Microsoft PhagsPa, Microsoft PhagsPa Bold, Microsoft Sans Serif, Microsoft Tai Le, Microsoft Tai Le Bold, Microsoft YaHei, Microsoft YaHei Bold, Microsoft YaHei UI, Microsoft YaHei UI Bold, Microsoft Yi Baiti, MingLiU-ExtB, MingLiU_HKSCS-ExtB, Minion Pro, Minion Pro Bold, Minion Pro Italic, Minion Pro Bold Italic, Mistral, Modern No. 20, Mongolian Baiti, Monotype Corsiva Italic, Myanmar Text, Myanmar Text Bold, Myriad Arabic, Myriad Arabic Bold, Myriad Arabic Italic, Myriad Arabic Bold Italic, Myriad Hebrew, Myriad Hebrew Bold, Myriad Hebrew Italic, Myriad Hebrew Bold Italic, Myriad Pro, Myriad Pro Bold, Myriad Pro Italic, Myriad Pro Bold Italic, NSimSun, Niagara Engraved, Niagara Solid, Nirmala UI, Nirmala UI Bold, Nueva Std, Nueva Std Bold, Nueva Std Italic, Nueva Std Bold Italic, OCR A Extended, OCR A Std, Old English Text MT, Onyx, Orator Std, Orator Std Italic, PMingLiU-ExtB, Palace Script MT Italic, Palatino Linotype, Palatino Linotype Bold, Palatino Linotype Italic, Palatino Linotype Bold Italic, Papyrus, Parchment, Perpetua, Perpetua Bold, Perpetua Italic, Perpetua Bold Italic, Perpetua Titling MT, Perpetua Titling MT Bold, Playbill, Poor Richard, Poplar Std, Prestige Elite Std Bold, Pristina, Rage Italic, Ravie, Rockwell, Rockwell Bold, Rockwell Italic, Rockwell Bold Italic, Rockwell Condensed, Rockwell Condensed Bold, Rockwell Extra Bold, Rosewood Std, Script MT Bold, Segoe MDL2 Assets, Segoe Marker, Segoe Print, Segoe Print Bold, Segoe Script, Segoe Script Bold, Segoe UI, Segoe UI Bold, Segoe UI Italic, Segoe UI Bold Italic, Segoe UI Emoji, Segoe UI Historic, Segoe UI Symbol, Segoe WP, Segoe WP Bold, Showcard Gothic, SimSun, SimSun-ExtB, Sitka Banner, Sitka Banner Bold, Sitka Banner Italic, Sitka Banner Bold Italic, Sitka Display, Sitka Display Bold, Sitka Display Italic, Sitka Display Bold Italic, Sitka Heading, Sitka Heading Bold, Sitka Heading Italic, Sitka Heading Bold Italic, Sitka Small, Sitka Small Bold, Sitka Small Italic, Sitka Small Bold Italic, Sitka Subheading, Sitka Subheading Bold, Sitka Subheading Italic, Sitka Subheading Bold Italic, Sitka Text, Sitka Text Bold, Sitka Text Italic, Sitka Text Bold Italic, SketchFlow Print, Snap ITC, Stencil, Stencil Std, Sylfaen, Symbol, Tahoma, Tahoma Bold, TeamViewer11, Tekton Pro Bold, Tekton Pro Bold Italic, Tempus Sans ITC, Times New Roman, Times New Roman Bold, Times New Roman Italic, Times New Roman Bold Italic, Trajan Pro, Trajan Pro Bold, Trebuchet MS, Trebuchet MS Bold, Trebuchet MS Italic, Trebuchet MS Bold Italic, Tw Cen MT, Tw Cen MT Bold, Tw Cen MT Italic, Tw Cen MT Bold Italic, Tw Cen MT Condensed, Tw Cen MT Condensed Bold, Tw Cen MT Condensed Extra Bold, UD Digi Kyokasho N-B Bold, UD Digi Kyokasho N-R, UD Digi Kyokasho NK-B Bold, UD Digi Kyokasho NK-R, UD Digi Kyokasho NP-B Bold, UD Digi Kyokasho NP-R, Verdana, Verdana Bold, Verdana Italic, Verdana Bold Italic, Viner Hand ITC, Vivaldi Italic, Vladimir Script, Webdings, Wide Latin, Wingdings, Wingdings 2, Wingdings 3, Yu Gothic, Yu Gothic Bold, Yu Gothic UI, Yu Gothic UI Bold, Yu Mincho, Yu Mincho Bold, g_comickoin_free-Reguler`

i tried some of these fonts and it seems to work just fine

**Comment by mem0ric** [comment]
I could not get. ((  You can write which plugin was used and where the font was changed. I used ReiPatcher and changed "OverrideFont =" in the file "{GameDirectory} /AutoTranslator/Config.ini"

**Comment by mem0ric** [comment]
I figured it out thanks for the clarification.
