### ISSUE TITLE
New problems occared when trying to translate Ja to zh

### ISSUE THREAD

**Issue by jodan911212** [bbepis/XUnity.AutoTranslator#274]
Just like what I’ve described on the above,something happened when I was trying to translate the game"交錯のブバルディア～精液を集めて世界を救う剣士と魔術師."I firstly got everything settled and started translating,and some of the text became口口口.I looked up for the solutions here and tried changing the font and it worked,the text became normal.But right at the moment I click on the memory scene in the gallery this pops out.
![螢幕擷取畫面 (25)](https://user-images.githubusercontent.com/102900572/161424990-1ab58431-f591-47d4-bebb-597efb94173a.png)

is there anyway to solve this problem?Haven’t seen problems like this happen before so don’t know how to deal with it.
May not be able to understand what I am talking about due to my terrible English,and I apologize for that and thank you all for your attention.
撰寫內容給

**Comment by gravydevsupreme** [comment]
Are you using `OverrideFontTextMeshPro` or `FallbackFontTextMeshPro`?

If you are using `OverrideFontTextMeshPro` then you should use `FallbackFontTextMeshPro` instead. `OverrideFontTextMeshPro` is deprecated because it easily causes glitches and issues.
