### ISSUE TITLE
Is it possible to encrypt the translated text?

### ISSUE THREAD

**Issue by Gedevan-Aleksizde** [bbepis/XUnity.AutoTranslator#276]
I want to redistribute the translated text but the file contains the original text as plaintext. Is it possible to encrypt, binarize, or do other method to obfuscate the file so as to avoid spoiler?

**Comment by gravydevsupreme** [comment]
This is not possible, no. Not really in the cards to make it either. If it's to avoid spoilers I would say that people are pretty much begging for it if they open the translation files. If it is to avoid people modifying it or similar I would say it goes against the principles of the plugin itself.

**Comment by Gedevan-Aleksizde** [comment]
OK. Primaly, I want to respect the developer's right as far as possible.  I assume a situation that I publish the translation files in my github repo or other open sites. I want to published the translated text and I want anyone to modify it. However, in this case, the all of the developer's original text is also opened and can be found by Google search. I meant that I want to hide only the original text.

**Comment by Gedevan-Aleksizde** [comment]
Of course there are some feasible solutions to hide the original text, but I just asked for such features on its own.

**Comment by gravydevsupreme** [comment]
If I were to add something like that it would likely have to be applied as some sort of "packaging"/distribution step that would be applied to the translations files right before redistribution. But that would not be particularly helpful to hide the sources in a repository. But that would not be particularly helpful to your scenario.

**Comment by Gedevan-Aleksizde** [comment]
thank you for your responce. I will tackle this problem by myself.
