### ISSUE TITLE
MelonLoader installing problem

### ISSUE THREAD

**Issue by hranthakobian** [bbepis/XUnity.AutoTranslator#303]
Can you please check if I did everything correctly or not?
![image](https://user-images.githubusercontent.com/21078676/181351069-462bd12e-a292-41c7-a676-0e4a89cd7f66.png)
![image](https://user-images.githubusercontent.com/21078676/181351090-022b98e3-23b5-4a6d-87b2-52826e983483.png)
![image](https://user-images.githubusercontent.com/21078676/181351138-e7bf888c-7dac-4dff-849d-4efdeae209fc.png)

**Comment by Atamg1994** [comment]
https://github.com/bbepis/XUnity.AutoTranslator/issues/299

**Comment by gravydevsupreme** [comment]
I would not expect ReiPatcher to work with Genshin impact at all. I have not tried, however.

I would highly suggest using BepInEx of MelonLoader if they support this type of game.
