### ISSUE TITLE
Font Problem

### ISSUE THREAD

**Issue by hranthakobian** [bbepis/XUnity.AutoTranslator#304]
Hello dear

I am translating Among Us into Armenian, but why does it not understand TMP files for Armenian?

Arial has Armenian

![image](https://user-images.githubusercontent.com/21078676/181490676-791a6d4a-6a80-42e3-add5-e218c4b65386.png)
![image](https://user-images.githubusercontent.com/21078676/181491094-04971188-cc71-47e7-b12b-3d4b28be4119.png)
![image](https://user-images.githubusercontent.com/21078676/181490851-70fba88b-1df3-44a4-8705-107fcfa9e254.png)

**Comment by Atamg1994** [comment]
> Arial has Armenian
there is no Armenian in the generated template

try this mod, it will generate missing symbols in the game on the go
https://github.com/bbepis/XUnity.AutoTranslator/issues/287#issuecomment-1158891109

**Comment by hranthakobian** [comment]
Hello
Thanks a lot for your answer

I just looked and realized that I am getting this error
 
![image](https://user-images.githubusercontent.com/21078676/181695237-553bf017-e5b9-4358-ae3d-5aaaff208a2c.png)

Also, the mod you gave me I don't understand, I'm using it incorrectly. or not working?

**Comment by hranthakobian** [comment]
Hello
Thanks a lot for your answer

I just looked and realized that I am getting this error
 
![image](https://user-images.githubusercontent.com/21078676/181695237-553bf017-e5b9-4358-ae3d-5aaaff208a2c.png)

Also, the mod you gave me I don't understand, I'm using it incorrectly. or not working?

> > Arial has Armenian
> 
> there is no Armenian in the generated template try this mod, it will generate missing symbols in the game on the go [#287 (comment)](https://github.com/bbepis/XUnity.AutoTranslator/issues/287#issuecomment-1158891109)

**Comment by hranthakobian** [comment]
[10:01:21.466] [ERROR] An error occurred while setting up UI.
System.TypeInitializationException: The type initializer for 'XUnity.AutoTranslator.Plugin.Core.UI.GUIUtil' threw an exception. ---> System.MissingMethodException: void UnityEngine.RectOffset..ctor(int,int,int,int)
   --- End of inner exception stack trace ---
  at XUnity.AutoTranslator.Plugin.Core.UI.ToggleViewModel..ctor (System.String text, System.String enabledTooltip, System.String disabledTooltip, System.Action onToggled, System.Func`1[TResult] isToggled, System.Boolean enabled) [0x00006] in <4d3ff0c19f0c45d7922e30f1b20fd02d>:0
  at XUnity.AutoTranslator.Plugin.Core.AutoTranslationPlugin.CreateXuaViewModel () [0x00005] in <4d3ff0c19f0c45d7922e30f1b20fd02d>:0
  at XUnity.AutoTranslator.Plugin.Core.AutoTranslationPlugin.InitializeGUI () [0x00015] in <4d3ff0c19f0c45d7922e30f1b20fd02d>:0
WARNING: get eos sdk handle
WARNING: get eos sdk handle

**Comment by hranthakobian** [comment]
Everything worked already

Thank you very much

**Comment by Atamg1994** [comment]
> 10:01:21.466] [ERROR] An error occurred while setting up UI.
> System.TypeInitializationException: The type initializer for 'XUnity.AutoTranslator.Plugin.Core.UI.GUIUtil' threw an exception. ---> System.MissingMethodException: void UnityEngine.RectOffset..ctor(int,int,int,int)
> --- End of inner exception stack trace ---

the translator has its own settings menu and that’s exactly what it doesn’t work for you, it doesn’t work for me either, but it’s not a problem, it will translate the text and the mod that I threw off should add characters

**Comment by hranthakobian** [comment]
OK, thanks for the answer. Everything works now

But one question, I made the font Among Us in my language, but there are many places where there is only one Arial, how can I put two fonts and indicate where it should be used

**Comment by hranthakobian** [comment]
> > 10:01:21.466] [ERROR] An error occurred while setting up UI.
> > System.TypeInitializationException: The type initializer for 'XUnity.AutoTranslator.Plugin.Core.UI.GUIUtil' threw an exception. ---> System.MissingMethodException: void UnityEngine.RectOffset..ctor(int,int,int,int)
> > --- End of inner exception stack trace ---
> 
> the translator has its own settings menu and that’s exactly what it doesn’t work for you, it doesn’t work for me either, but it’s not a problem, it will translate the text and the mod that I threw off should add characters

OK, thanks for the answer. Everything works now

But one question, I made the font Among Us in my language, but there are many places where there is only one Arial, how can I put two fonts and indicate where it should be used

**Comment by Atamg1994** [comment]
> But one question, I made the font Among Us in my language, but there are many places where there is only one Arial, how can I put two fonts and indicate where it should be used

This mod replaces all fonts with one there is no support for two fonts

**Comment by hranthakobian** [comment]
> > But one question, I made the font Among Us in my language, but there are many places where there is only one Arial, how can I put two fonts and indicate where it should be used
> 
> This mod replaces all fonts with one there is no support for two fonts

And you can't say another mod?

**Comment by Atamg1994** [comment]
> And you can't say another mod?

I have no idea
