### ISSUE TITLE
Doing Manual translation before using substitution file 

### ISSUE THREAD

**Issue by Aceship** [bbepis/XUnity.AutoTranslator#307]
is there any way to have some of the manual translation to run before doing substitution ?
like placing it on a specific folder ?

in this case when the translation was made before having the substitution file, making the text that need to be translated is different , so it would be a lot of work to change the translation that already translated

**Comment by gravydevsupreme** [comment]
No, this is not possible. 

I would generally suggest avoiding substitutions and make use of regexes instead if possible in the situation.
