### ISSUE TITLE
the newest realease doesn't work foe me!

### ISSUE THREAD

**Issue by qaz1314520qaz** [bbepis/XUnity.AutoTranslator#31]
the version of 2.18 is well,but above 3.0,it doesn't work anymore for auto translate, i used googletranslate,but when i changed to manual,it goes well.what's the problem of me ?

**Comment by gravydevsupreme** [comment]
Greetings, and apologies for not having responded to this earlier.

I currently have no way of helping you as you have provided no details on the issue you are facing.

I can only guess that it may be related to a bad installation path that includes the '#' character in the path. The earlier versions of 3.x.x had issues with this, but it has been resolved in the later versions.

So I can only recommend that you update to a newer version.

If it still is not working for you, please re-open the issue and provide additional details on the issue you are facing.

**Comment by qaz1314520qaz** [comment]
Thanks for your replay.sadly!the newest is not work.so strange.version 2.8 is ok
