### ISSUE TITLE
Translated texts are replaced in wrong encoding 

### ISSUE THREAD

**Issue by Gedevan-Aleksizde** [bbepis/XUnity.AutoTranslator#313]
The AutoTranslator appends new translated text in correct encoding but also seems to overwrite existing texts in wrong encoding. the new text is in UTF-8, but the old text is overwritten in UTF-16. This issue sometimes happens but I dont't exactly know when it happens.

I used v5.1.0 for MelonLoader and I changed the default settings like the following:

```
[Service]
Endpoint=GoogleTranslate

[General]
Language=ja
FromLanguage=en

[Behaviour]
MaxCharactersPerTranslation=300
MaxClipboardCopyCharacters=1500
```

**Comment by gravydevsupreme** [comment]
I would definitely need steps to reproduce this behavior, as I've never experienced this before and it sounds extremely odd.

**Comment by Gedevan-Aleksizde** [comment]
very sorry. it's not a bug. I found my script caused this error.
