### ISSUE TITLE
old autotranslator problem

### ISSUE THREAD

**Issue by dima245** [bbepis/XUnity.AutoTranslator#314]
after translation, the text from the table view is merged into a single text. It's been such a problem for a long time.
![пукпеукп](https://user-images.githubusercontent.com/58454276/192486049-b1300703-2ca8-45e8-8006-f9b4547506ba.jpg)
![ыпаыпывп](https://user-images.githubusercontent.com/58454276/192486063-1ff9205a-126e-4567-b139-78d40826416b.jpg)

**Comment by gravydevsupreme** [comment]
You can set `IgnoreWhitespaceInDialogue=False`, but it may (or may not) reduce translation quality in other situations.

**Comment by dima245** [comment]
Thanks. helped.
another trouble.
how do i block some of the text た回数? when translating "Количество раз" takes up a lot of space. and additional lines appear.

![пурыр](https://user-images.githubusercontent.com/58454276/192832435-ad06448d-da38-4588-a954-c4e9bfed64d1.jpg)
