### ISSUE TITLE
Chinese Translations

### ISSUE THREAD

**Issue by Crownphoenix** [bbepis/XUnity.AutoTranslator#32]
Does this even support Chinese translations? 

In the config file i changed the fromlanguage code from ja to zh but all the translators are greyed out

-XUnity.AutoTranslator-ReiPatcher-3.5.0

**Comment by maksfrai** [comment]
You should use zh-CN or zh-TW flags instead.

**Comment by Crownphoenix** [comment]
Thanks that's was it
