### ISSUE TITLE
BepInEx-IL2CPP version needs to query BepInEx for the unhollowed path

### ISSUE THREAD

**Issue by GeBo1** [bbepis/XUnity.AutoTranslator#320]
The correct path might not always be `BepInEx\unhollower`, but you should be able to get the path from `BepInEx.IL2CPP.Preloader.IL2CPPUnhollowedPath`.

To reproduce set this in `BepInEx.cfg`:
```
UnhollowedAssembliesPath={BepInEx}\{ProcessName}
```

**Comment by gravydevsupreme** [comment]
Alright. I will update the plugin to use this path instead.

**Comment by gravydevsupreme** [comment]
Fix released now in 5.2.0
