### ISSUE TITLE
Way to override auto-translation of character names/proper nouns?

### ISSUE THREAD

**Issue by purposelycryptic** [bbepis/XUnity.AutoTranslator#33]
Pretty much as the title says: Is there currently any option to define certain sets of characters to always be substituted for the same string, overriding anything coming from the web-translation services? 

A lot of the older, "classic" systems like TA, AGTH (I believe), and whatever combination of voodoo was tied together to make VNR let you set up some sort of dictionary file which would always supersede the automated systems and just swap the Japanese string for whatever other string you had set it to.

My reason for asking is that I'm currently playing a game with two main female characters by the names of 音瑚 (Neko) and 兎萌 (Tomoe), and the former is, seemingly at random, referred to as either _Koutaro, Otome, Oto, Otoko_, or _Sound_ (Nothing like seeing a young girl referred to as Oto-chan (a 'u' short of 'Dad'), Koutaro (definitely a guys name) or Otoko (which just straight up means 'Man')), while the latter is always called _Rabbit Moe_, which is at least fitting, given that she is a bunny girl at a hostess club (and likely deliberate by the devs), and is the direct translation of those Kanji, but definitely not her name.

The specific combination of Kanji making up their names is rare enough to seemingly not show up anywhere in the rest of the script (They are not exactly the most common way of writing Neko or Tomoe), so this would be a perfect use-case for a simple replacement system... But, as far as I can tell, there isn't one. 

I retroactively made a custom translation file that fixes their names, but that only helps for textfield labels and other instances where the string matches _exactly_, not for instances of it being a sub-string of a line of dialogue. Am I just missing something obvious, or is this simply not something implemented in the XUnity.AutoTranslator? 

Because other than that, it seems like an almost perfect implementation of a machine-translation system for Unity games, lightyears ahead of what older systems with similar objectives could do. It's just so smoothly integrated.

**Comment by spiritov0d** [comment]
It doesn't implemented yet, but theoretically it's possible for sure. If you're using google translation, try to replace  AutoTranslator\Translators\GoogleTranslate.dll with [this](https://drive.google.com/file/d/1lHx42E0M_NNYL3bzqL9Yl4k8Il0BKq92/view?usp=sharing) and check in-game text for two mentioned names.

**Comment by purposelycryptic** [comment]
Awesome, thanks a ton!
 
I feel slightly silly now for spending several hours manually correcting lines from the _AutoGeneratedTranslations.en.txt and putting them in a custom translation text file, but as I ended up correcting a lot of other weird translations as well while I was at it, I suppose it wasn't a total loss.

Thanks again, really appreciate it:-)

**Comment by gravydevsupreme** [comment]
Closing this issue, as it has been replaced by #34
