### ISSUE TITLE
What Shall I Do to Make a Game's Font Support More Characters?

### ISSUE THREAD

**Issue by future93** [bbepis/XUnity.AutoTranslator#330]
I'm trying to translate an Unity game which already has AutoTranslator translated EN language into my mother tongue. However the game's font only has very limited characters within, and thus all the characters not supported can only be displayed as something like □.

I think that maybe I should replace the game's font with another one that support my language's characters, and possibly through the XUnity.ResourceRedirector. I've checked the related issues to find out how to do so, but since my knowledge on Unity is quite poor, still I cannot make a solution on my own.

The game is Unity Mono, with BepInEX 5.4 installed. Any detailed guide or document can be useful.

**Comment by Atamg1994** [comment]
https://github.com/bbepis/XUnity.AutoTranslator/issues/290
https://github.com/bbepis/XUnity.AutoTranslator/issues/287
