### ISSUE TITLE
Is this game based on Unity?

### ISSUE THREAD

**Issue by K14Mua** [bbepis/XUnity.AutoTranslator#333]
I came across a strange game, I can’t understand what engine it is on. There are three subfolders in the root of the game, "locales" in which there are a lot of *.pak files. "resources" subfolder with just one app.asar file per 300 megabytes. And a "swiftshader" subfolder with two files, libEGL.dll and libGLESv2.dll

Is this a unity game?

**Comment by TokcDK** [comment]
No app.asar is from other engine.
Unity game have exe and exe_Data folder

If you got an answer you can close the issue.

**Comment by K14Mua** [comment]
It looks like you are right. This game on TyranoBuilder

**Comment by K14Mua** [comment]
It looks like you are right. This game on TyranoBuilder
