### ISSUE TITLE
Substitution mechanics doesn't look right

### ISSUE THREAD

**Issue by spiritov0d** [bbepis/XUnity.AutoTranslator#34]
Thank you for implementing that feature, but now it doesn't look right. Because in AutoGeneratedTranslations file we now have both original and translated versions of a substituition as {{A}}, so it's very hard to manually edit the translation afterward (because you don't know what exactly substitution is being used in every case), only in real time. It will be better to create a static translation, for example:
In substitutions file: えっま=Emma
In translations file: 私わえっま=My name is Emma
instead of current: 私わ{{A}}=My name is {{A}}

Thanks in advance.

**Comment by gravydevsupreme** [comment]
New version (3.6.1) includes an option (GenerateStaticSubstitutionTranslations) to indicate there should be no variables in substituted translations. Console output will still indicate variable names, but that is only because only a single translation is actually performed.

**Comment by spiritov0d** [comment]
Thank you, it's perfect now o/
