### ISSUE TITLE
textmesh pro fonts do not work at all

### ISSUE THREAD

**Issue by I0lOl0I** [bbepis/XUnity.AutoTranslator#351]
everything disappeared when I tried to use this plugin(XUnity.AutoTranslator-BepInEx-5.2.0) to translate, 
I put the plugin for BepInEx (BepInEx_x64_5.4.21.0) in game directory then start the game,
but it doesn't display any characters (only numbers), I thought it was the font problem, so I add 2 fonts in config files, 
one was in the OverrideFontTextMeshPro, the other is the callback font(arialuni_sdf_u2018 and the 2019), 
however, it only gets worse, I can't see any characters anymore.

the auto-translating seems work fine, it does generate translation and capture strings to _AutoGeneratedTranslations file.
the game is The Pioneers: surviving desolation, I was trying to translate the game from en(english) to zh-CN(simplified chinese).
the UnityPlayer.dll file version is 2021.3.16.5719, product version is 2021.3.16.f1 (4016570cf34f)
![no text](https://user-images.githubusercontent.com/79507221/216811705-a125733e-db27-4565-a77f-b1d113a36a11.jpg)
[https://imgur.com/a/GXN5Fhp](url)
here is my config

> [Service]
> Endpoint=GoogleTranslateV2
> FallbackEndpoint=PapagoTranslate
> 
> [General]
> Language=zh-CN
> FromLanguage=en
> 
> [Files]
> Directory=Translation\{Lang}\Text
> OutputFile=Translation\{Lang}\Text\_AutoGeneratedTranslations.txt
> SubstitutionFile=Translation\{Lang}\Text\_Substitutions.txt
> PreprocessorsFile=Translation\{Lang}\Text\_Preprocessors.txt
> PostprocessorsFile=Translation\{Lang}\Text\_Postprocessors.txt
> 
> [TextFrameworks]
> EnableIMGUI=False
> EnableUGUI=True
> EnableNGUI=True
> EnableTextMeshPro=True
> EnableTextMesh=False
> EnableFairyGUI=True
> 
> [Behaviour]
> MaxCharactersPerTranslation=1000
> IgnoreWhitespaceInDialogue=True
> MinDialogueChars=20
> ForceSplitTextAfterCharacters=0
> CopyToClipboard=False
> MaxClipboardCopyCharacters=2500
> ClipboardDebounceTime=1.25
> EnableUIResizing=True
> EnableBatching=True
> UseStaticTranslations=True
> OverrideFont=
> OverrideFontSize=
> OverrideFontTextMeshPro=BepInEx\font\arialuni_sdf_u2019
> FallbackFontTextMeshPro=BepInEx\font\arialuni_sdf_u2018
> ResizeUILineSpacingScale=
> ForceUIResizing=False
> IgnoreTextStartingWith=\u180e;\u0030;\u0031;\u0032;\u0033;\u0034;\u0035;\u0036;\u0037;\u0038;\u0039;
> TextGetterCompatibilityMode=False
> GameLogTextPaths=
> RomajiPostProcessing=ReplaceMacronWithCircumflex;RemoveApostrophes;ReplaceHtmlEntities
> TranslationPostProcessing=ReplaceMacronWithCircumflex;ReplaceHtmlEntities
> RegexPostProcessing=
> CacheRegexPatternResults=False
> CacheRegexLookups=False
> CacheWhitespaceDifferences=False
> GenerateStaticSubstitutionTranslations=False
> GeneratePartialTranslations=False
> EnableTranslationScoping=True
> EnableSilentMode=True
> BlacklistedIMGUIPlugins=
> EnableTextPathLogging=False
> OutputUntranslatableText=False
> IgnoreVirtualTextSetterCallingRules=False
> MaxTextParserRecursion=1
> HtmlEntityPreprocessing=True
> HandleRichText=True
> EnableTranslationHelper=False
> ForceMonoModHooks=False
> InitializeHarmonyDetourBridge=False
> RedirectedResourceDetectionStrategy=AppendMongolianVowelSeparatorAndRemoveAll
> OutputTooLongText=False
> TemplateAllNumberAway=False
> ReloadTranslationsOnFileChange=False
> DisableTextMeshProScrollInEffects=False
> CacheParsedTranslations=False
> 
> [Texture]
> TextureDirectory=Translation\{Lang}\Texture
> EnableTextureTranslation=False
> EnableTextureDumping=False
> EnableTextureToggling=False
> EnableTextureScanOnSceneLoad=False
> EnableSpriteRendererHooking=False
> LoadUnmodifiedTextures=False
> DetectDuplicateTextureNames=False
> DuplicateTextureNames=
> EnableLegacyTextureLoading=False
> TextureHashGenerationStrategy=FromImageName
> CacheTexturesInMemory=True
> EnableSpriteHooking=False
> 
> [ResourceRedirector]
> PreferredStoragePath=Translation\{Lang}\RedirectedResources
> EnableTextAssetRedirector=False
> LogAllLoadedResources=False
> EnableDumping=False
> CacheMetadataForAllFiles=True
> 
> [Http]
> UserAgent=
> DisableCertificateValidation=True
> 
> [TranslationAggregator]
> Width=400
> Height=100
> EnabledTranslators=
> 
> [Debug]
> EnableConsole=False
> 
> [Migrations]
> Enable=True
> Tag=5.2.0
> 
> [Baidu]
> BaiduAppId=
> BaiduAppSecret=
> DelaySeconds=1
> 
> [BingLegitimate]
> OcpApimSubscriptionKey=
> 
> [Custom]
> Url=
> 
> [DeepL]
> ExecutableLocation=
> MinDelaySeconds=2
> MaxDelaySeconds=6
> 
> [DeepLLegitimate]
> ExecutableLocation=
> ApiKey=
> Free=False
> 
> [ezTrans]
> InstallationPath=
> 
> [Google]
> ServiceUrl=
> 
> [GoogleV2]
> ServiceUrl=
> RPCID=MkEWBc
> VERSION=boq_translate-webserver_20210323.10_p0
> UseSimplest=False
> 
> [GoogleLegitimate]
> GoogleAPIKey=
> 
> [LecPowerTranslator15]
> InstallationPath=
> 
> [LingoCloud]
> LingoCloudToken=
> 
> [Watson]
> Url=
> Key=
> 
> [Yandex]
> YandexAPIKey=
> 

and here is the output log

> [Message:   BepInEx] BepInEx 5.4.21.0 - The Pioneers (1/28/2023 10:59:25 AM)
> [Info   :   BepInEx] Running under Unity v2021.3.16.4200023
> [Info   :   BepInEx] CLR runtime version: 4.0.30319.42000
> [Info   :   BepInEx] Supports SRE: True
> [Info   :   BepInEx] System platform: Bits64, Windows
> [Message:   BepInEx] Preloader started
> [Info   :   BepInEx] Loaded 1 patcher method from [BepInEx.Preloader 5.4.21.0]
> [Info   :   BepInEx] 1 patcher plugin loaded
> [Info   :   BepInEx] Patching [UnityEngine.CoreModule] with [BepInEx.Chainloader]
> [Message:   BepInEx] Preloader finished
> [Message:   BepInEx] Chainloader ready
> [Message:   BepInEx] Chainloader started
> [Info   :   BepInEx] 2 plugins to load
> [Info   :   BepInEx] Loading [XUnity Auto Translator 5.2.0]
> [Info   :XUnity.AutoTranslator] Version of TextMesh Pro: 1.4.0.
> [Warning:  HarmonyX] AccessTools.Method: Could not find method for type TMPro.TMP_Text and name SetCharArray and parameters (int[], int, int)
> [Warning:XUnity.AutoTranslator] Could not hook 'TMP_Text_SetCharArray_Hook3'. Likely due differences between different versions of the engine or text framework.
> [Info   :XUnity.AutoTranslator] Attempting to load TextMesh Pro font from asset bundle.
> [Info   :XUnity.AutoTranslator] Loaded TextMesh Pro font uses version: Unknown
> [Warning:XUnity.AutoTranslator] TextMesh Pro version mismatch. Font asset version: Unknown, TextMesh Pro version: 1.4.0
> [Info   :XUnity.AutoTranslator] Loaded fallback font for TextMesh Pro: BepInEx\font\arialuni_sdf_u2018
> [Info   :XUnity.AutoTranslator] Loaded XUnity.AutoTranslator into Unity [2021.3.16f1] game.
> [Info   :   BepInEx] Loading [XUnity Resource Redirector 2.0.0]
> [Message:   BepInEx] Chainloader startup complete
> [Info   :XUnity.AutoTranslator] Attempting to load TextMesh Pro font from asset bundle.
> [Info   :XUnity.AutoTranslator] Loaded TextMesh Pro font uses version: Unknown
> [Warning:XUnity.AutoTranslator] TextMesh Pro version mismatch. Font asset version: Unknown, TextMesh Pro version: 1.4.0
> [Warning:XUnity.AutoTranslator] An error occurred while handling the UI discovery.
> System.NullReferenceException: Object reference not set to an instance of an object
>   at TMPro.TMP_FontAsset.ReadFontAssetDefinition () [0x0013b] in <3d8a79b88bf0484f8d56f49feeab1ca5>:0 
>   at TMPro.TMP_FontAsset.get_characterLookupTable () [0x00008] in <3d8a79b88bf0484f8d56f49feeab1ca5>:0 
>   at TMPro.TextMeshProUGUI.LoadFontAsset () [0x00087] in <3d8a79b88bf0484f8d56f49feeab1ca5>:0 
>   at TMPro.TMP_Text.set_font (TMPro.TMP_FontAsset value) [0x00016] in <3d8a79b88bf0484f8d56f49feeab1ca5>:0 
>   at (wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.FastReflection<TMPro.TMP_Text.set_font>(object,object[])
>   at XUnity.Common.Utilities.CachedProperty.Set (System.Object instance, System.Object arg1) [0x00012] in <1122b42a80884eb0b3ba56da0d8efe94>:0 
>   at XUnity.AutoTranslator.Plugin.Core.TextTranslationInfo.ChangeFont (System.Object ui) [0x0015f] in <04658fc57931491dbb3fb58d885aa820>:0 
>   at XUnity.AutoTranslator.Plugin.Core.AutoTranslationPlugin.DiscoverComponent (System.Object ui, XUnity.AutoTranslator.Plugin.Core.TextTranslationInfo info) [0x00031] in <04658fc57931491dbb3fb58d885aa820>:0 
> [Warning:XUnity.AutoTranslator] An error occurred while handling the UI discovery.
> System.NullReferenceException: Object reference not set to an instance of an object
>   at TMPro.TMP_FontAsset.get_atlasTexture () [0x00015] in <3d8a79b88bf0484f8d56f49feeab1ca5>:0 
>   at TMPro.TextMeshProUGUI.LoadFontAsset () [0x000f4] in <3d8a79b88bf0484f8d56f49feeab1ca5>:0 
>   at TMPro.TMP_Text.set_font (TMPro.TMP_FontAsset value) [0x00016] in <3d8a79b88bf0484f8d56f49feeab1ca5>:0 
>   at (wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.FastReflection<TMPro.TMP_Text.set_font>(object,object[])
>   at XUnity.Common.Utilities.CachedProperty.Set (System.Object instance, System.Object arg1) [0x00012] in <1122b42a80884eb0b3ba56da0d8efe94>:0 
>   at XUnity.AutoTranslator.Plugin.Core.TextTranslationInfo.ChangeFont (System.Object ui) [0x0015f] in <04658fc57931491dbb3fb58d885aa820>:0 
>   at XUnity.AutoTranslator.Plugin.Core.AutoTranslationPlugin.DiscoverComponent (System.Object ui, XUnity.AutoTranslator.Plugin.Core.TextTranslationInfo info) [0x00031] in <04658fc57931491dbb3fb58d885aa820>:0 
> [Warning:XUnity.AutoTranslator] An error occurred while handling the UI discovery.
> System.NullReferenceException: Object reference not set to an instance of an object
>   at TMPro.TMP_FontAsset.get_atlasTexture () [0x00015] in <3d8a79b88bf0484f8d56f49feeab1ca5>:0 
>   at TMPro.TextMeshProUGUI.LoadFontAsset () [0x000f4] in <3d8a79b88bf0484f8d56f49feeab1ca5>:0 
>   at TMPro.TMP_Text.set_font (TMPro.TMP_FontAsset value) [0x00016] in <3d8a79b88bf0484f8d56f49feeab1ca5>:0 
>   at (wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.FastReflection<TMPro.TMP_Text.set_font>(object,object[])
>   at XUnity.Common.Utilities.CachedProperty.Set (System.Object instance, System.Object arg1) [0x00012] in <1122b42a80884eb0b3ba56da0d8efe94>:0 
>   at XUnity.AutoTranslator.Plugin.Core.TextTranslationInfo.ChangeFont (System.Object ui) [0x0015f] in <04658fc57931491dbb3fb58d885aa820>:0 
>   at XUnity.AutoTranslator.Plugin.Core.AutoTranslationPlugin.DiscoverComponent (System.Object ui, XUnity.AutoTranslator.Plugin.Core.TextTranslationInfo info) [0x00031] in <04658fc57931491dbb3fb58d885aa820>:0 
> [Warning:XUnity.AutoTranslator] An error occurred while handling the UI discovery.
> System.NullReferenceException: Object reference not set to an instance of an object
>   at TMPro.TMP_FontAsset.get_atlasTexture () [0x00015] in <3d8a79b88bf0484f8d56f49feeab1ca5>:0 
>   at TMPro.TextMeshProUGUI.LoadFontAsset () [0x000f4] in <3d8a79b88bf0484f8d56f49feeab1ca5>:0 
>   at TMPro.TMP_Text.set_font (TMPro.TMP_FontAsset value) [0x00016] in <3d8a79b88bf0484f8d56f49feeab1ca5>:0 
>   at (wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.FastReflection<TMPro.TMP_Text.set_font>(object,object[])
>   at XUnity.Common.Utilities.CachedProperty.Set (System.Object instance, System.Object arg1) [0x00012] in <1122b42a80884eb0b3ba56da0d8efe94>:0 
>   at XUnity.AutoTranslator.Plugin.Core.TextTranslationInfo.ChangeFont (System.Object ui) [0x0015f] in <04658fc57931491dbb3fb58d885aa820>:0 
>   at XUnity.AutoTranslator.Plugin.Core.AutoTranslationPlugin.DiscoverComponent (System.Object ui, XUnity.AutoTranslator.Plugin.Core.TextTranslationInfo info) [0x00031] in <04658fc57931491dbb3fb58d885aa820>:0 
> [Warning:XUnity.AutoTranslator] An error occurred while handling the UI discovery.
> System.NullReferenceException: Object reference not set to an instance of an object
>   at TMPro.TMP_FontAsset.get_atlasTexture () [0x00015] in <3d8a79b88bf0484f8d56f49feeab1ca5>:0 
>   at TMPro.TextMeshProUGUI.LoadFontAsset () [0x000f4] in <3d8a79b88bf0484f8d56f49feeab1ca5>:0 
>   at TMPro.TMP_Text.set_font (TMPro.TMP_FontAsset value) [0x00016] in <3d8a79b88bf0484f8d56f49feeab1ca5>:0 
>   at (wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.FastReflection<TMPro.TMP_Text.set_font>(object,object[])
>   at XUnity.Common.Utilities.CachedProperty.Set (System.Object instance, System.Object arg1) [0x00012] in <1122b42a80884eb0b3ba56da0d8efe94>:0 
>   at XUnity.AutoTranslator.Plugin.Core.TextTranslationInfo.ChangeFont (System.Object ui) [0x0015f] in <04658fc57931491dbb3fb58d885aa820>:0 
>   at XUnity.AutoTranslator.Plugin.Core.AutoTranslationPlugin.DiscoverComponent (System.Object ui, XUnity.AutoTranslator.Plugin.Core.TextTranslationInfo info) [0x00031] in <04658fc57931491dbb3fb58d885aa820>:0 
> [Warning:XUnity.AutoTranslator] An error occurred while handling the UI discovery.
> System.NullReferenceException: Object reference not set to an instance of an object
>   at TMPro.TMP_FontAsset.get_atlasTexture () [0x00015] in <3d8a79b88bf0484f8d56f49feeab1ca5>:0 
>   at TMPro.TextMeshProUGUI.LoadFontAsset () [0x000f4] in <3d8a79b88bf0484f8d56f49feeab1ca5>:0 
>   at TMPro.TMP_Text.set_font (TMPro.TMP_FontAsset value) [0x00016] in <3d8a79b88bf0484f8d56f49feeab1ca5>:0 
>   at (wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.FastReflection<TMPro.TMP_Text.set_font>(object,object[])
>   at XUnity.Common.Utilities.CachedProperty.Set (System.Object instance, System.Object arg1) [0x00012] in <1122b42a80884eb0b3ba56da0d8efe94>:0 
>   at XUnity.AutoTranslator.Plugin.Core.TextTranslationInfo.ChangeFont (System.Object ui) [0x0015f] in <04658fc57931491dbb3fb58d885aa820>:0 
>   at XUnity.AutoTranslator.Plugin.Core.AutoTranslationPlugin.DiscoverComponent (System.Object ui, XUnity.AutoTranslator.Plugin.Core.TextTranslationInfo info) [0x00031] in <04658fc57931491dbb3fb58d885aa820>:0 
> [Warning:XUnity.AutoTranslator] An error occurred while handling the UI discovery.
> System.NullReferenceException: Object reference not set to an instance of an object
>   at TMPro.TMP_FontAsset.get_atlasTexture () [0x00015] in <3d8a79b88bf0484f8d56f49feeab1ca5>:0 
>   at TMPro.TextMeshProUGUI.LoadFontAsset () [0x000f4] in <3d8a79b88bf0484f8d56f49feeab1ca5>:0 
>   at TMPro.TMP_Text.set_font (TMPro.TMP_FontAsset value) [0x00016] in <3d8a79b88bf0484f8d56f49feeab1ca5>:0 
>   at (wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.FastReflection<TMPro.TMP_Text.set_font>(object,object[])
>   at XUnity.Common.Utilities.CachedProperty.Set (System.Object instance, System.Object arg1) [0x00012] in <1122b42a80884eb0b3ba56da0d8efe94>:0 
>   at XUnity.AutoTranslator.Plugin.Core.TextTranslationInfo.ChangeFont (System.Object ui) [0x0015f] in <04658fc57931491dbb3fb58d885aa820>:0 
>   at XUnity.AutoTranslator.Plugin.Core.AutoTranslationPlugin.DiscoverComponent (System.Object ui, XUnity.AutoTranslator.Plugin.Core.TextTranslationInfo info) [0x00031] in <04658fc57931491dbb3fb58d885aa820>:0 
> [Warning:XUnity.AutoTranslator] An error occurred while handling the UI discovery.
> System.NullReferenceException: Object reference not set to an instance of an object
>   at TMPro.TMP_FontAsset.get_atlasTexture () [0x00015] in <3d8a79b88bf0484f8d56f49feeab1ca5>:0 
>   at TMPro.TextMeshProUGUI.LoadFontAsset () [0x000f4] in <3d8a79b88bf0484f8d56f49feeab1ca5>:0 
>   at TMPro.TMP_Text.set_font (TMPro.TMP_FontAsset value) [0x00016] in <3d8a79b88bf0484f8d56f49feeab1ca5>:0 
>   at (wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.FastReflection<TMPro.TMP_Text.set_font>(object,object[])
>   at XUnity.Common.Utilities.CachedProperty.Set (System.Object instance, System.Object arg1) [0x00012] in <1122b42a80884eb0b3ba56da0d8efe94>:0 
>   at XUnity.AutoTranslator.Plugin.Core.TextTranslationInfo.ChangeFont (System.Object ui) [0x0015f] in <04658fc57931491dbb3fb58d885aa820>:0 
>   at XUnity.AutoTranslator.Plugin.Core.AutoTranslationPlugin.DiscoverComponent (System.Object ui, XUnity.AutoTranslator.Plugin.Core.TextTranslationInfo info) [0x00031] in <04658fc57931491dbb3fb58d885aa820>:0 
> [Warning:XUnity.AutoTranslator] An error occurred while handling the UI discovery.
> System.NullReferenceException: Object reference not set to an instance of an object
>   at TMPro.TMP_FontAsset.get_atlasTexture () [0x00015] in <3d8a79b88bf0484f8d56f49feeab1ca5>:0 
>   at TMPro.TextMeshProUGUI.LoadFontAsset () [0x000f4] in <3d8a79b88bf0484f8d56f49feeab1ca5>:0 
>   at TMPro.TMP_Text.set_font (TMPro.TMP_FontAsset value) [0x00016] in <3d8a79b88bf0484f8d56f49feeab1ca5>:0 
>   at (wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.FastReflection<TMPro.TMP_Text.set_font>(object,object[])
>   at XUnity.Common.Utilities.CachedProperty.Set (System.Object instance, System.Object arg1) [0x00012] in <1122b42a80884eb0b3ba56da0d8efe94>:0 
>   at XUnity.AutoTranslator.Plugin.Core.TextTranslationInfo.ChangeFont (System.Object ui) [0x0015f] in <04658fc57931491dbb3fb58d885aa820>:0 
>   at XUnity.AutoTranslator.Plugin.Core.AutoTranslationPlugin.DiscoverComponent (System.Object ui, XUnity.AutoTranslator.Plugin.Core.TextTranslationInfo info) [0x00031] in <04658fc57931491dbb3fb58d885aa820>:0 
> [Info   :XUnity.AutoTranslator] Skipping plugin scan because no plugin-specific translations has been registered.
> [Error  :XUnity.AutoTranslator] Batch operation received incorrect number of translations.
> [Error  :XUnity.AutoTranslator] Failed: 'Thank you for purchasing The Pioneers. Your support is necessary for us to continue the development of the game.
> 
> In this early build, you may experience bugs and missing features.
> Be sure that we are fully commited to improve your overall playing experience. Please check the latest patch notes.'
> [Error  :XUnity.AutoTranslator] Failed: '
> 
> Reworked machine installation shaders. The visual effect has now a clear and clean look
> Reworked machine installation hitbox. It is now easier to click on the desired slot
> 
> Fixed a critical bug on station modules that could cause some crashes and performance issues
> Fixed a few bugs that prevented old saves from loading
> Fixed starting loots that were reset when the game loaded
> 
> '
> [Error  :XUnity.AutoTranslator] Failed: '
> 
> Reworked pathfinding to prevent a lot of navigation bugs
> 
> Fixed "lie down in the medipod" action
> Fixed a bug that allowed to heal a character outside the medipod
> Fixed a bug that prevented fracture healing
> Fixed various bugs on oxygen sharing action
> Fixed a bug that prevented mining large ore veins
> Fixed automatic wake-up feature
> 
> '
> [Error  :XUnity.AutoTranslator] Failed: '
> 
> Added new personal item events
> Added a teaser event for the next character
> Updated game credits
> 
> Added a safety feature to prevent some loading errors
> 
> Fixed a major bug that could cause characters to freeze when using different machines such as treadmills
> Fixed personal items that did not always apply the bonus correctly
> Fixed interaction with satellites
> Fixed a bug on mining actions that sometimes prevented the character from interacting with the ore
> Fixed a discussion that sometimes caused an animation loop
> Fixed saving when a character is exhausted
> Fixed notifications that displayed more than one confirmation button
> Fixed in-game roadmap not always displaying correctly
> Fixed the tooltip for sulphur chimneys
> Fixed station inventory tooltip
> Fixed the timer in the communication machine
> Fixed various small save/load bugs
> Fixed a conflict between the main menu panels
> Fixed some other missing or wrong locations
> 
> Reduced the heat emitted by sulphur wells when they are active
> 
> '
> [Error  :XUnity.AutoTranslator] Failed: '
> 
> • Added some restrictions on climbing actions to prevent major bugs
> • Added the ability to jump to/from the drilling station
> • Added a save name to the continue/load menu
> • Added a patch notes message in the main menu
> 
> • Fixed a major bug that could cause a character to get stuck in a wall
> • Fixed saves not working when the time zone is different from the user's
> • Fixed a bug on saves that would erase the last autosave instead of the last save
> • Fixed saving when a character climbs
> • Fixed the medikit item. Using a medikit should no longer freeze a character
> • Fixed a conflict between the "toggle roof" and "speed" keys
> • Fixed various tooltips
> 
> • Balanced some game design values to offer more challenge
> 
> '
> [Error  :XUnity.AutoTranslator] Failed: '
> 
> • Added auto-save feature (yeah!)
> • Added a confirmation box before quitting a mission or leaving the game.
> • Added character model in closed life pods
> • Added tooltip on mining action
> 
> • Fixed the medical pod. A character can no longer exit the pod before being healed.
> • Fixed the healing action that often blocked a character after healing.
> • Fixed the Continue button in the main menu that was clickable even if you had no save.
> • Fixed a conflict between the TAB and Y keys in the key mapping menu.
> • Fixed SFX and UI alerts not stopping after a seism ends.
> • Fixed a bug in the save system that caused problems with the main station airlock.
> • Fixed a bug that changed the location status of a character
> • Fixed a collision bug on ore resources
> • Fixed a collision bug between the character's ragdolls and the station surface
> • Fixed various visual bugs
> • Fixed various localizations
> 
> '
> [Error  :XUnity.AutoTranslator] Failed: '
> 
> • Implemented a safety feature that prevent a character from deviating his curve when climbing
> • Maggie can no longer shut down while the roof is opening which was an major source of bugs
> 
> • Fixed a sound bug that occured when your pioneers were eating (Nom Nom Nom loop)
> • Fixed alarms that were not connected to the air management system
> • Fixed a visual bug that displayed machines upgrades that have not been installed
> • Fixed a bug that prevented some UI to be closed after loading a game
> • Fixed some localizations
> • Fixed Discord link'
> [Error  :XUnity.AutoTranslator] Failed: 'patch notes'
> [Error  :XUnity.AutoTranslator] Failed: 'Continue'
> [Error  :XUnity.AutoTranslator] Failed: 'new game'
> [Error  :XUnity.AutoTranslator] A batch operation failed. Disabling batching and restarting failed jobs.

if this is a game side problem, how can I suggest the dev to fix it or at least make it compatible to different fonts?
thank you.

**Comment by Atamg1994** [comment]
https://github.com/bbepis/XUnity.AutoTranslator/issues/290
https://github.com/bbepis/XUnity.AutoTranslator/issues/287

**Comment by I0lOl0I** [comment]
> #290 #287

I have read those, but doesn't work at all

**Comment by Atamg1994** [comment]
> > #290 #287
> 
> I have read those and tried the files in #290 but doesn't work at all
> 
> > [17:30:07.949] ------------------------------
> > [17:30:07.950] MelonLoader v0.5.7 Open-Beta
> > [17:30:07.950] OS: Windows 10
> > [17:30:07.951] Hash Code: 49999848531024954985654485098975250521005157544948501005510199495356
> > [17:30:07.951] ------------------------------
> > [17:30:07.951] Game Type: MonoBleedingEdge
> > [17:30:07.952] Game Arch: x64
> > [17:30:07.952] ------------------------------
> > [17:30:07.952] Core::BasePath = E:\Games\The Pioneers surviving desolation
> > [17:30:07.953] Game::BasePath = E:\Games\The Pioneers surviving desolation
> > [17:30:07.953] Game::DataPath = E:\Games\The Pioneers surviving desolation\The Pioneers_Data
> > [17:30:07.953] Game::ApplicationPath = E:\Games\The Pioneers surviving desolation\The Pioneers.exe
> > [17:30:08.303] ------------------------------
> > [17:30:08.303] Game Name: The Pioneers
> > [17:30:08.303] Game Developer: Supercube
> > [17:30:08.307] Unity Version: 2021.3.16f1
> > [17:30:08.307] Game Version: UNKNOWN
> > [17:30:08.308] ------------------------------
> > [17:30:08.654] Preferences Loaded!
> > [17:30:08.687] Loading Plugins from 'E:\Games\The Pioneers surviving desolation\Plugins'...
> > [17:30:08.689] 0 Plugins loaded.
> > ﻿﻿
> > [17:30:09.441] [MelonStartScreen] Initializing...
> > [17:30:09.471] [MelonStartScreen] Using Start Screen Theme: "Default"
> > [17:30:10.669] [MelonStartScreen] [ERROR] Exception while rendering: System.NullReferenceException: Object reference not set to an instance of an object
> > at MelonLoader.MelonStartScreen.UI.Objects.UI_Text.Render (System.Int32 x, System.Int32 y) [0x00014] in <458ba450aca74195b4ba3d1c13011f5d>:0
> > at MelonLoader.MelonStartScreen.UI.Objects.UI_Text.Render () [0x00000] in <458ba450aca74195b4ba3d1c13011f5d>:0
> > at MelonLoader.MelonStartScreen.UI.Objects.UI_ProgressBar.Render () [0x0016c] in <458ba450aca74195b4ba3d1c13011f5d>:0
> > at MelonLoader.MelonStartScreen.UI.UI_Style.Render () [0x0001e] in <458ba450aca74195b4ba3d1c13011f5d>:0
> > at MelonLoader.MelonStartScreen.ScreenRenderer.Render () [0x00014] in <458ba450aca74195b4ba3d1c13011f5d>:0
> > [17:30:10.701] Loading Mods from 'E:\Games\The Pioneers surviving desolation\Mods'...
> > [17:30:10.734] ------------------------------
> > [17:30:10.741] Melon Assembly loaded: '.\Mods\FontOverride.dll'
> > [17:30:10.742] SHA256 Hash: 'f98089af8985d210765c684bc79bc4a8ee63485b44422728e8e7e8d0b93e838b'
> > [17:30:10.743] Melon Assembly loaded: '.\Mods\XUnity.AutoTranslator.Plugin.MelonMod.dll'
> > [17:30:10.744] SHA256 Hash: 'f0c8689a5bd0d16f4c40a7cef5a2923698570345d69fe45fe166be64a3fd0637'
> > [17:30:10.784] [WARNING] Some Melons are missing dependencies, which you may have to install.
> > If these are optional dependencies, mark them as optional using the MelonOptionalDependencies attribute.
> > This warning will turn into an error and Melons with missing dependencies will not be loaded in the next version of MelonLoader.
> > 
> > * 'FontOverride' is missing the following dependencies:
> >   
> >   * 'UnityEngine.TextCoreModule' v0.0.0.0
> >     [17:30:10.794] ------------------------------
> >     [17:30:10.794] FontOverride v0.0.1
> >     [17:30:10.795] by rfcclub
> >     [17:30:10.797] Assembly: FontOverride.dll
> >     [17:30:10.797] ------------------------------
> >     [17:30:10.798] ------------------------------
> >     [17:30:10.798] XUnity Auto Translator v5.1.0
> >     [17:30:10.799] by gravydevsupreme
> >     [17:30:10.800] Assembly: XUnity.AutoTranslator.Plugin.MelonMod.dll
> >     [17:30:10.801] ------------------------------
> >     [17:30:10.801] ------------------------------
> >     [17:30:10.802] 2 Mods loaded.
> > 
> > [17:30:10.811] Support Module Loaded: E:\Games\The Pioneers surviving desolation\MelonLoader\Dependencies\SupportModules\Mono.dll
> > [17:30:19.939] [FontOverride] -------------method found SetText
> > [17:30:19.951] [FontOverride] -------------method found SetTranslatedText
> > [17:30:19.953] [FontOverride] -------------method found GetOrCreateOverrideFontTextMeshPro
> > [17:30:20.005] Screen resolution determine to be: 1920x1080
> > [17:30:20.006] Version of TextMesh Pro: 1.4.0.
> > [17:30:20.079] Hooked UnityEngine.UI.Text.set_text through Harmony hooks.
> > [17:30:20.081] Hooked UnityEngine.UI.Text.OnEnable through Harmony hooks.
> > [17:30:20.084] Hooked TMPro.TextMeshProUGUI.OnEnable through Harmony hooks.
> > [17:30:20.087] Hooked TMPro.TextMeshPro.OnEnable through Harmony hooks.
> > [17:30:20.090] Hooked TMPro.TMP_Text.set_text through Harmony hooks.
> > [17:30:20.092] Hooked TMPro.TMP_Text.SetText through Harmony hooks.
> > [17:30:20.095] Hooked TMPro.TMP_Text.SetText through Harmony hooks.
> > [17:30:20.097] Hooked TMPro.TMP_Text.SetText through Harmony hooks.
> > [17:30:20.100] Hooked TMPro.TMP_Text.SetCharArray through Harmony hooks.
> > [17:30:20.108] Hooked TMPro.TMP_Text.SetCharArray through Harmony hooks.
> > [17:30:20.109] [WARNING] Could not hook 'TMP_Text_SetCharArray_Hook3'. Likely due differences between different versions of the engine or text framework.
> > [17:30:20.172] Disabling certificate checks for endpoints because of configuration.
> > [17:30:20.176] Probing whether OnLevelWasLoaded or SceneManager is supported in this version of Unity. Any warnings related to OnLevelWasLoaded coming from Unity can safely be ignored.
> > [17:30:20.177] SceneManager is supported in this version of Unity.
> > [17:30:20.181] Loaded resize command text files.
> > [17:30:20.187] --- Loading Global Translations ---
> > [17:30:20.193] Loaded translation text files (took 0 seconds)
> > [17:30:20.195] Created variation translations (took 0 seconds)
> > [17:30:20.195] Created token translations (took 0 seconds)
> > [17:30:20.197] Loaded XUnity.AutoTranslator into Unity [2021.3.16f1] game.
> > [17:30:20.271] [FontOverride] Modify TMP Setting
> > [17:30:20.279] [FontOverride] Modify TMP Setting
> > [17:30:20.288] [FontOverride] Modify TMP Setting
> > [17:30:20.289] [FontOverride] Modify TMP Setting
> > [17:30:20.290] [FontOverride] Modify TMP Setting
> > [17:30:20.291] [FontOverride] Modify TMP Setting
> > [17:30:20.293] [FontOverride] Modify TMP Setting
> > [17:30:20.294] [FontOverride] Modify TMP Setting
> > [17:30:20.296] [FontOverride] Modify TMP Setting
> > [17:30:20.297] [FontOverride] Modify TMP Setting
> > [17:30:20.299] [FontOverride] Modify TMP Setting
> > [17:30:20.320] [FontOverride] Modify TMP Setting
> > [17:30:20.996] Skipping plugin scan because no plugin-specific translations has been registered.

bro I found time for you and did it if necessary
https://mega.nz/file/XEBGGDTa#d3AAcAnhe9iHGzkCvZkCQVH07XdCvyW00rJVqMgwVWE



![Screenshot_1](https://user-images.githubusercontent.com/57526178/219982373-b9003a5a-569d-4d7f-a937-575b3ac9d8e0.png)
![Screenshot_2](https://user-images.githubusercontent.com/57526178/219982374-8274e2e1-136c-4bd5-b7ee-b084024c973e.png)
![Screenshot_3](https://user-images.githubusercontent.com/57526178/219982376-3748f729-c29e-4bdd-8728-9d8fa4443cb5.png)
![Screenshot_23](https://user-images.githubusercontent.com/57526178/219982390-4347fd38-a7d7-4a1b-9516-cc97a5279dc4.png)

**Comment by Atamg1994** [comment]
[Config.zip](https://github.com/bbepis/XUnity.AutoTranslator/files/10778277/Config.zip)

**Comment by I0lOl0I** [comment]
> bro I found time for you and did it if necessary

thank you, very appreciated.
you are the best!
