### ISSUE TITLE
---

### ISSUE THREAD

**Issue by ghost** [bbepis/XUnity.AutoTranslator#357]
---

**Comment by I0lOl0I** [comment]
what if you manually input the cut-off texts?
does it still not show in the dialogue box?

you can try to resize the elements to fit the text field.
https://github.com/bbepis/XUnity.AutoTranslator#ui-resizing
https://github.com/bbepis/XUnity.AutoTranslator#ui-font-resizing

**Comment by ManlyMarco** [comment]
OP blanked the post out so I'm closing it
