### ISSUE TITLE
System.InvalidOperationException: You are trying to read Input using the UnityEngine.Input class

### ISSUE THREAD

**Issue by Atamg1994** [bbepis/XUnity.AutoTranslator#373]
Game Type: MonoBleedingEdge
Game Arch: x64
 ------------------------------
Game Name: The Scarlet Tower
Game Developer: Pyxeralia
Unity Version: 2022.1.18f1
Game Version: 0.9.0.1

System.InvalidOperationException: You are trying to read Input using the UnityEngine.Input class, but you have switched active Input handling to Input System package in Player Settings.

  at (wrapper managed-to-native) UnityEngine.Input.GetKeyInt(UnityEngine.KeyCode)

  at UnityEngine.Input.GetKey (UnityEngine.KeyCode key) [0x00001] in <8e515d8231a348b6922b4e00671d9710>:0 

  at XUnity.AutoTranslator.Plugin.Core.AutoTranslationPlugin.HandleInput () [0x00000] in <04658fc57931491dbb3fb58d885aa820>:0 

  at XUnity.AutoTranslator.Plugin.Core.AutoTranslationPlugin.HandleInputSafe () [0x00007] in <04658fc57931491dbb3fb58d885aa820>:0 

  at XUnity.AutoTranslator.Plugin.Core.AutoTranslationPlugin.Update () [0x000b3] in <04658fc57931491dbb3fb58d885aa820>:0 
[03:11:33.311] [ERROR] An error occurred in Update callback. 

Any ideas how to fix this?

does not interfere with the translation
does not interfere with play
keyboard shortcuts not working
Key Mapping
The following key inputs are mapped:

ALT + 0: Toggle XUnity AutoTranslator UI. (That's a zero, not an O)
ALT + 1: Toggle Translation Aggregator UI.
ALT + T: Alternate between translated and untranslated versions of all texts provided by this plugin.
ALT + R: Reload translation files. Useful if you change the text and texture files on the fly. Not guaranteed to work for all textures.
ALT + U: Manual hooking. The default hooks wont always pick up texts. This will attempt to make lookups manually. Will not hook text components from frameworks not enabled.
ALT + F: If OverrideFont is configured, will toggle between overridden and default font.
ALT + Q: Reboot the plugin if it was shutdown. This will only work if the plugin was shut down due to consecutive errors towards the translation endpoint. Should only be used if you have reason to believe you have remedied the problem (such as changed VPN endpoint etc.) otherwise it will just shut down again.
Debugging-only keys:

CTRL + ALT + NP9: Simulate synchronous errors
CTRL + ALT + NP8: Simulate asynchronous errors delayed by one second
CTRL + ALT + NP7: Print out loaded scene names and ids to console
CTRL + ALT + NP6: Print out entire GameObject hierarchy to file hierarchy.txt

**Comment by xlifi** [comment]
same issue with lethal company

**Comment by stdcall0** [comment]
this issue still presents in Lethal Company, are there any workarounds for this? (prehaps adding a config for key binds)

**Comment by Atamg1994** [comment]
> this issue still presents in Lethal Company, are there any workarounds for this? (prehaps adding a config for key binds)
> 
> Though the gameplay is unaffected, there can be a significant hit on game performance because the console and log file is spammed with this error.

for the Lethal company, I partially solved this problem in my font replacement mod, there is also a code that you can insert manually and also partially solve the problem There is still a problem with calling the interface.. here in  instructions and a link


https://mega.nz/file/Xd4GEBwK#6t5XgNFUU1UiV3JnikQP7LLFjI0vIojaSZg88gZ0-Sk
before starting the game, launch
Lethal Company\node_GoogleTranslator_server\start.cmd
This is a server for caching translations and correcting html markup
or install any other translator in the config

For example, change Endpoint=CustomTranslateBanch to Endpoint=GoogleTranslateV2
to disable the caching server and use standard tools


Or Code , check this link 

https://github.com/bbepis/XUnity.AutoTranslator/issues/443

**Comment by stdcall0** [comment]
Thanks for your quick response! I tried to compile your code with dnSpy but I can't figure out how to solve the missing assembly. Could you kindly help by uploading a compiled version?
(Actually I don't want to put keyboard shortcuts to work, I'm trying to disable the input handling to prevent the flooding error in console)

**Comment by Atamg1994** [comment]
> Thanks for your quick response! I tried to compile your code with dnSpy but I can't figure out how to solve the missing assembly. Could you kindly help by uploading a compiled version? (Actually I don't want to put keyboard shortcuts to work, I'm trying to disable the input handling to prevent the flooding error in console)

then download the archive above! and there either use a standard translator for it, it needs to be registered in the config, or use a translator for the js server node, which I use, but before the game it needs to be launched manually In general, the archive above is for you! Just install the config and you will get the "bepinex loader" package with a mod that loads mods from the "melon loader". This kit is needed because the mod, which fixes the input and fonts, was originally written for the “melon loader” and I didn’t want to remake it for Bepinex.

**Comment by ManlyMarco** [comment]
Fixed by #531
