### ISSUE TITLE
Translation sometimes swallows text and line breaks(\n)

### ISSUE THREAD

**Issue by iG8R** [bbepis/XUnity.AutoTranslator#386]
The title says for itself.
Game: 觅长生 (Immortal Way of Life)
Is it possible to somehow fix it?
Also, is there an exception list that prevents XUnityAutoTranslator to translate selected by the user or already translated text?

```
Pill to enhance physique. An extremely rare Pill among sixth grade Pills, has the effect of refining the body and improving ones physique.\n已有:91=Pill to enhance physique. An extremely rare pill among simth grade pills, have the effect of refining the body and improve one's Physique.
A pill that increases speed. After taking it, there will be a breeze all over the body, increasing the speed.\n已有:76=A piece that increases spey. After taking it, there would be a bree all over the body, increasing the spey.
获得精元1680000\n闭关70年0月后，可将精元凝练为210血量上限=After obtaining Jingyuan 1680000 retreat 70 years, you can condense the essence to a 210 blood volume upper limit
```

Original text:
![Immortal-befor-translation-01-2023-05-31_123718](https://github.com/bbepis/XUnity.AutoTranslator/assets/11407417/f1297ff9-6966-4f52-9f1d-cfe80b42ee1e)
![Immortal-befor-translation-02-2023-05-31_123852](https://github.com/bbepis/XUnity.AutoTranslator/assets/11407417/f1fe2f68-42de-46fa-abbd-d24f13bb4f67)
![Immortal-befor-translation-03-2023-05-31_125419](https://github.com/bbepis/XUnity.AutoTranslator/assets/11407417/e4e9a71a-025b-4fd1-8eac-ea660c1b168f)

Translated text:
![Immortal-after-translation-01-2023-05-31_125043](https://github.com/bbepis/XUnity.AutoTranslator/assets/11407417/5893b95b-b188-44ce-81e8-ec97dc53350e)
![Immortal-after-translation-02-2023-05-31_125155](https://github.com/bbepis/XUnity.AutoTranslator/assets/11407417/0a99b9aa-adcb-4238-a343-8c7bd5d41afe)
![Immortal-after-translation-03-2023-05-31_125536](https://github.com/bbepis/XUnity.AutoTranslator/assets/11407417/82e173c6-dafe-42e8-9d89-391bc74b3086)

**Comment by Atamg1994** [comment]
setup this in you config

Endpoint=GoogleTranslateCompat
and
FromLanguage=auto
and
TemplateAllNumberAway=True
and clear the old translation

maybe this will fix your problems
