### ISSUE TITLE
Add support for ATLAS translator?

### ISSUE THREAD

**Issue by kouji71** [bbepis/XUnity.AutoTranslator#4]
Would it be possible to add support for ATLAS translator? I personally think it's translations are better than google translate's.

**Comment by gravydevsupreme** [comment]
Apologies for not having responded to this issue earlier.

I've taken a look at ATLAS and I currently feel it would be too much effort to support it, given the interest.

Keeping the issue open to gauge any potential additional interest.

**Comment by jasonmbrown** [comment]
I would appreciate Any method of offline translation. Atlas is usually my goto although its quality isn't near googles, its usually much faster.

**Comment by gravydevsupreme** [comment]
Going to close this. For English there are far better alternatives for offline translation with [this](https://github.com/Vin-meido/XUnity-AutoTranslator-SugoiOfflineTranslatorEndpoint).
