### ISSUE TITLE
Add Support for Systran Translate.

### ISSUE THREAD

**Issue by Terell2018** [bbepis/XUnity.AutoTranslator#42]
i found this translate call systran translate.
Link:https://translate.systran.net/translationTools/text

**Comment by gravydevsupreme** [comment]
Greetings,

Is this translator specifically good a some languages, making it a better choice than the currently implemented plugins?

**Comment by Terell2018** [comment]
i was trying to create SystranTranslate.dll but i don't have no skill.

**Comment by Terell2018** [comment]
Could you add systran translate.dll on next version. thank you. i don't have no skill.
