### ISSUE TITLE
DeepL endpoint missing

### ISSUE THREAD

**Issue by Vorked** [bbepis/XUnity.AutoTranslator#431]
Being on previous versions of XUnity and BepInEx, I had come across an issue where DeepL stopped outputting. The translations received have gotten exponentially worse. So I decided up upgrade and moved to the newest stable versions of each, but it's still causing this issue. 

Everyone using my mod is also reporting this exact issue with DeepL. Is there a fix or a way around this?

![image](https://github.com/bbepis/XUnity.AutoTranslator/assets/4886720/10335675-c36b-49a7-b3e6-9b41ce779fe4)
![image](https://github.com/bbepis/XUnity.AutoTranslator/assets/4886720/72fa5ae1-0ac2-43f0-ae0d-bea9eff48191)

**Comment by Vorked** [comment]
![image](https://github.com/bbepis/XUnity.AutoTranslator/assets/4886720/98c46f30-dee8-49a7-9f8e-ad8528ab8fd7)
A little more proof that this isn't on my end.

**Comment by Vin-meido** [comment]
Looks like deepl changed the call for getClientState for their web client. The old url does not seem to work anymore and inspecting the website, the url seems to be different.

The pull request above changes the url being used as well as the method of the request to fix the problem. Verified working on 2 instances, though further test/checking might be required to confirm the fix.
![image](https://github.com/bbepis/XUnity.AutoTranslator/assets/86288831/0c40fba2-4a16-4add-a7e1-01cf2a0ef078)

**Comment by Vorked** [comment]
> Looks like deepl changed the call for getClientState for their web client. The old url does not seem to work anymore and inspecting the website, the url seems to be different.
> 
> The pull request above changes the url being used as well as the method of the request to fix the problem. Verified working on 2 instances, though further test/checking might be required to confirm the fix. ![image](https://user-images.githubusercontent.com/86288831/278848055-0c40fba2-4a16-4add-a7e1-01cf2a0ef078.png)

Thanks for this, it's a big help. Due to my smooth brain, I'm going to see if someone can compile the changes for me.

**Comment by ertup0** [comment]
> Looks like deepl changed the call for getClientState for their web client. The old url does not seem to work anymore and inspecting the website, the url seems to be different.
> 
> The pull request above changes the url being used as well as the method of the request to fix the problem. Verified working on 2 instances, though further test/checking might be required to confirm the fix. ![image](https://user-images.githubusercontent.com/86288831/278848055-0c40fba2-4a16-4add-a7e1-01cf2a0ef078.png)

Can you please compile this version I don't think this will be merged anytime soon

**Comment by Vin-meido** [comment]
I would be wary to accept dlls from non-known project maintainers, but there is indeed quite a lot of issue backlog atm, and the build could use more users to confirm if it fixes the problem for them...

Here you go. Find DeepLTranslate.ExtProtocol.dll and replace it with the file in the zip package.

[DeepLTranslate.ExtProtocol.zip](https://github.com/bbepis/XUnity.AutoTranslator/files/13260155/DeepLTranslate.ExtProtocol.zip)

**Comment by ertup0** [comment]
> I would be wary to accept dlls from non-known project maintainers, but there is indeed quite a lot of issue backlog atm, and the build could use more users to confirm if it fixes the problem for them...
> 
> Here you go. Find DeepLTranslate.ExtProtocol.dll and replace it with the file in the zip package.
> 
> [DeepLTranslate.ExtProtocol.zip](https://github.com/bbepis/XUnity.AutoTranslator/files/13260155/DeepLTranslate.ExtProtocol.zip)

From my testing deepl now works and translation quality is very good, but it shutdowns after 100-150, strings and to fix it i have to change my ip(turn on vpn) or restart the game

**Comment by Vin-meido** [comment]
> From my testing deepl now works and translation quality is very good, but it shutdowns after 100-150, strings and to fix it i have to change my ip(turn on vpn) or restart the game

Works fine for me even up to 200 strings. Are there any error messages in the console?

**Comment by Vin-meido** [comment]
Test with this one and see if the problem still occures.

[DeepLTranslate.ExtProtocol.dll.zip](https://github.com/bbepis/XUnity.AutoTranslator/files/14018306/DeepLTranslate.ExtProtocol.dll.zip)
