### ISSUE TITLE
Only want to hook Text but not Translate

### ISSUE THREAD

**Issue by bianzhidie** [bbepis/XUnity.AutoTranslator#434]
My English is not good.I only want to get text from game (output sample like: "I am human=I am human") .I tried do something.If I dont chose any translator,it dont output anything.If I set config.ini  ([General] Language=en FromLanguage=en),it also dont work.Someone can help me?What should I do?

**Comment by I0lOl0I** [comment]
input translator endpoint service as Passthrough

**Comment by bianzhidie** [comment]
> input translator endpoint service as Passthrough
Thank you very much for your response. I can now successfully get text, but only menu and similar texts are get correctly. When get dialogue text, it repeats the extraction and includes the [00] field multiple times. I would like to know what the issue might be.
![0THX }4E8G N8AHDNUA}4I2](https://github.com/bbepis/XUnity.AutoTranslator/assets/74587700/140e02dc-3624-4785-97f8-bc3c74271561)
![P6T5D@{W H2%3U6B{7GR1IY](https://github.com/bbepis/XUnity.AutoTranslator/assets/74587700/26f8a7dd-cc6e-46f0-a763-0ed3832afa50)

**Comment by I0lOl0I** [comment]
there is no issue, that's the typing effect(Typewriter Effect) the game used.
you either wait till the effect goes off and display the whole sentence, or just live with what you have in hands.
