### ISSUE TITLE
Extract text without applying translations

### ISSUE THREAD

**Issue by ItsukaShiroInfinity** [bbepis/XUnity.AutoTranslator#435]
Because the game I need to translate needs advanced requirements, I have to play it on my desktop PC but I don't have Internet, on the laptop I can get Internet but it doesn't meet the requirements, that's why I need an option to be able to extract the texts without Internet. The idea is to maintain the original phrase by adding a symbol at the beginning to know what was extracted:
hello = >hello

**Comment by I0lOl0I** [comment]
input translator endpoint service as Passthrough

**Comment by ItsukaShiroInfinity** [comment]
Passthrough: Will this extract the phrase without translating it?

**Comment by I0lOl0I** [comment]
> Passthrough: Will this extract the phrase without translating it?

#434
