### ISSUE TITLE
regular expressions have become uncomfortable

### ISSUE THREAD

**Issue by Loli-Kyn** [bbepis/XUnity.AutoTranslator#463]
The other day I was trying to make regular expressions for digits and I had to kill AutoTranlator. I couldn't make regular expressions for digits, but I got an unexpected bonus (not for me).
If I used to put a word and its translation in "_Substitutions", then in "_AutoGeneratedTranslations" it looked like this 1. But after it became like this 2.
Example:
Before
1. "_Substitutions"-回攻撃=Name. → "_AutoGeneratedTranslations" -Name.=Name.
After the update.
2. "_Substitutions"-回攻撃=Name. → "_AutoGeneratedTranslations" - {{A}}.
It turns out that instead of missing digits I got a peculiar code, which I cannot edit in case of errors.

How do I get the old look back and how do I skip numbers. I have gone through all the open and closed topics on this subject but never understood the principle of sr or r. I will be glad if you can show me on my example
"7ダメ\n<脱力3>\n<爆裂矢>\n英知12/2=7ダメ\n<Off Force 3>\n<Burst Arrow>\nHidechi 12/2."

![1.](https://github.com/bbepis/XUnity.AutoTranslator/assets/52761837/eb71979f-0ef9-4fd3-a197-ff5f31415e6b)
![2.](https://github.com/bbepis/XUnity.AutoTranslator/assets/52761837/4996a93a-9120-4833-9b6a-42a479bc68fc)

**Comment by TokcDK** [comment]
{{A}},{{B}}...{{Z}} and other will be replaced with any name from _Substitutions for cause when character name can be different but the other text is identical.

It cant look like "Name.=Name." if he Name was added in _Substitutions.txt, it will look like "{{A}}.={{A}}.". It was so from the first day when _Substitutions feature was added.
_Substitutions work only with normal text and not related to regex.



Вижу какой язык перевода и напишу на нем тоже, заменители всегда работали так, как сейчас, ничего не поменялось. В кеше перевода, в текстовых файлах, заменитель {{A}} всегда будет относиться к одной записи из файла _Substitutions.txt , где к примеру для строки _Substitutions "Ivan=Иван" в переводе с английского на русский плагин будет искать в английской строке "Ivan is eating. Ivan is enjoying." все совпадения по слову Ivan, потом изменит строку на "{{A}} is eating. {{A}} is enjoying the food." и будет искать её в кеше, если найдет, тогда в переводе вроде "{{A}} кушает. {{A}} наслаждается едой." заменит {{A}} на перевод "Иван", отобразив перевод "Иван кушает. Иван наслаждается едой." , поэтому в строке "{{A}} is eating. {{A}} is enjoying the food." {{A}} может быть любым именем.

**Comment by TokcDK** [comment]
Все строки в файле _Substitutions.txt также являются и кешем перевода, поэтому определенное имя будет взято оттуда вместо общего кеша.

**Comment by Loli-Kyn** [comment]
> {{A}},{{B}}...{{Z}} и другие будут заменены любым именем из _Substitutions, если имя символа может отличаться, но остальной текст идентичен.
> 
> Оно не может выглядеть как «Имя.=Имя». если его имя было добавлено в _Substitutions.txt, оно будет выглядеть как "{{A}}.={{A}}.". Так было с первого дня, когда была добавлена ​​функция _Substitutions. _Замены работают только с обычным текстом и не связаны с регулярными выражениями.
> 
> Вижу какой язык перевода и напишу на нем тоже, заменители всегда работали так, как сейчас, ничего не поменялось. В кеше перевода, в текстовых файлах, заменитель {{A}} всегда будет относиться к одной записи из файла _Substitutions.txt , где к примеру для строки _Substitutions "Ivan=Иван" в переводе с английского на русский плагин будет искать в английской строке "Ivan is eating. Ivan is enjoying." все совпадения по слову Ivan, потом изменит строку на "{{A}} is eating. {{A}} is enjoying the food." и будет искать её в кеше, если найдет, тогда в переводе вроде "{{A}} кушает. {{A}} наслаждается едой." заменит {{A}} на перевод "Иван", отобразив перевод "Иван кушает. Иван наслаждается едой." , поэтому в строке "{{A}} is eating. {{A}} is enjoying the food." {{A}} может быть любым именем.

Then why did it used to take a word from _Substitutions and throw it in as a whole word "Ivan is eating=Ivan is eating"?
If it's a bug, I liked it a lot, because I could edit the text and see where it came from in the game.

**Comment by TokcDK** [comment]
> > {{A}},{{B}}...{{Z}} и другие будут заменены любым именем из _Substitutions, если имя символа может отличаться, но остальной текст идентичен.
> > Оно не может выглядеть как «Имя.=Имя». если его имя было добавлено в _Substitutions.txt, оно будет выглядеть как "{{A}}.={{A}}.". Так было с первого дня, когда была добавлена ​​функция _Substitutions. _Замены работают только с обычным текстом и не связаны с регулярными выражениями.
> > Вижу какой язык перевода и напишу на нем тоже, заменители всегда работали так, как сейчас, ничего не поменялось. В кеше перевода, в текстовых файлах, заменитель {{A}} всегда будет относиться к одной записи из файла _Substitutions.txt , где к примеру для строки _Substitutions "Ivan=Иван" в переводе с английского на русский плагин будет искать в английской строке "Ivan is eating. Ivan is enjoying." все совпадения по слову Ivan, потом изменит строку на "{{A}} is eating. {{A}} is enjoying the food." и будет искать её в кеше, если найдет, тогда в переводе вроде "{{A}} кушает. {{A}} наслаждается едой." заменит {{A}} на перевод "Иван", отобразив перевод "Иван кушает. Иван наслаждается едой." , поэтому в строке "{{A}} is eating. {{A}} is enjoying the food." {{A}} может быть любым именем.
> 
> Then why did it used to take a word from _Substitutions and throw it in as a In the first screenshot of your first message I see russian to russian text in cache and substitutions will not find "атаки" in source line(before '=' char) if it is not presented as source text in substitutions. Something wrong there because in your case there must be japanese source text.

In your second picture is version with a bug when strings "zzdz" or kind of was appearing in translation cache in some cases. It was fixed in XUA 5.3 .

**Comment by TokcDK** [comment]
And your example line "7ダメ\n<脱力3>\n<爆裂矢>\n英知12/2=7ダメ\n<Off Force 3>\n\nHidechi 12/2." can be parsed by regex like this:
sr:([0-9]+)ダメ\n<([^0-9]+)([0-9]+)>\n<([^>]+)>\n([^0-9]+)([0-9]+)/([0-9]+)=$1ダメ\n<$2 $3>\n$4\n$5 $6/$7.

many kind of line can be parsed using [regex](https://github.com/bbepis/XUnity.AutoTranslator?tab=readme-ov-file#regex-usage).

**Comment by Loli-Kyn** [comment]
> > Тогда почему он брал слово из _Substitutions и добавлял его как
> 
> На первом скриншоте вашего первого сообщения я вижу текст с русского на русский в кеше, и замены не найдут "атаки" в исходной строке (перед символом '='), если он не представлен как исходный текст в заменах. Что-то здесь не так, потому что в вашем случае должен быть исходный текст на японском языке.
> 
> На второй картинке представлена ​​версия с ошибкой, когда в некоторых случаях в кеше перевода появлялись строки «zzdz» или что-то в этом роде. Это было исправлено в XUA 5.3.
I don't know why, but the translator immediately showed the translated text from _Substitutions in _AutoGeneratedTranslations instead of the original text and I liked it. Maybe it's because I didn't have a new version?

**Comment by Loli-Kyn** [comment]
If I add this expression 
"{{C}}ダメ<抵抗矢>\n<{{D}}回攻撃><カオス刺突耐性-{{E}}>\n{{A}}{{F}} {{B}}{{G}}}.=tranlate"  
в 
"_Substitutions"
Will it be invariable if the numbers change?

**Comment by Atamg1994** [comment]
install node google translate server, he also does other things,
https://github.com/bbepis/XUnity.AutoTranslator/issues/396 
 it will do exactly what you are talking about.  removes tags and then puts them back in place
