### ISSUE TITLE
 dont work with pathfinder kingmaker

### ISSUE THREAD

**Issue by ziomik** [bbepis/XUnity.AutoTranslator#49]

**Comment by ziomik** [comment]
in debug I see the queue but there is no translation. No help for me? Thank you
```
[DEBUG][XUnity.AutoTranslator]:  Queued: 'Language'
[DEBUG][XUnity.AutoTranslator]:  Queued: 'English'
[DEBUG][XUnity.AutoTranslator]:  Queued: 'Allow sending the game statistics'
[DEBUG][XUnity.AutoTranslator]:  Queued: 'Option A'
[DEBUG][XUnity.AutoTranslator]:  Queued: 'Allow sending the saved games'
[DEBUG][XUnity.AutoTranslator]:  Queued: 'Improved kingdom loading times'
[DEBUG][XUnity.AutoTranslator]:  Queued: 'AI doesn't use expendable spells'
[DEBUG][XUnity.AutoTranslator]:  Queued: 'Action bar slots auto-fill'
[DEBUG][XUnity.AutoTranslator]:  Queued: 'Enable looting during combat'
[DEBUG][XUnity.AutoTranslator]:  Queued: 'Tutorial messages'
[DEBUG][XUnity.AutoTranslator]:  Queued: 'Only short tips'
[DEBUG][XUnity.AutoTranslator]:  Queued: 'Font size'
[DEBUG][XUnity.AutoTranslator]:  Queued: 'Quick movement'
```

**Comment by ziomik** [comment]
I update by saying that it works by putting the API key (I used the IBM WatsonTranslate)

**Comment by gravydevsupreme** [comment]
Thanks for this report. 

This type of issue is usually the product of something blocking the specific API that is used to make request by this plugin.

Watson works because it uses a different API.

Currently the only way to fix this issue is to spin up a different process to make the translation request. This is something I am working on supporting.

**Comment by efonte** [comment]
Try to change this:
```ini
[Http]
DisableCertificateValidation=True
```

**Comment by ziomik** [comment]
Oh yes, so Google works too !! Thanks

**Comment by gravydevsupreme** [comment]
Interesting.

Given the behaviour I was convinced this was facing the same issue as that Zombotron game.

I will probably terminate this certificate validation behaviour permanently, or at least always have it OFF by default.
