### ISSUE TITLE
xUnity beplnex method error

### ISSUE THREAD

**Issue by michigetne** [bbepis/XUnity.AutoTranslator#490]
The following error appears

Error log
-------------------------------------------------------------------------------------------------------------------------------------------------
[Message: Preloader] BepInEx 6.0.0-be.682 - DECOY獰ㅹ쓵??춸也?
[Message: Preloader] Built from commit 910844a982dbb126d0c6544847424bc42fb7849c
[Info   :   BepInEx] System platform: Windows 10 64-bit
[Info   :   BepInEx] Process bitness: 64-bit (x64)
[Info   :   BepInEx] Running under Unity 2022.3.16f1
[Info   :   BepInEx] Runtime version: 6.0.7
[Info   :   BepInEx] Runtime information: .NET 6.0.7
[Info   : Preloader] 0 patcher plugins loaded
[Info   : Preloader] 0 assemblies discovered
[Message:AssemblyPatcher] Executing 0 patch(es)
[Message:   BepInEx] Chainloader initialized
[Warning:Il2CppInterop] Class::Init signatures have been exhausted, using a substitute!
[Info   :Il2CppInterop] Registered mono type Il2CppInterop.Runtime.DelegateSupport+Il2CppToMonoDelegateReference in il2cpp domain
[Info   :   BepInEx] 3 plugins to load
[Info   :   BepInEx] Loading [Texture_Replacer_il2cpp_net6 1.0.6]
[Info   :Il2CppInterop] Registered mono type Texture_Replacer_il2cpp_net6.Texture_Replacer_il2cpp in il2cpp domain
[Info   :   BepInEx] Loading [XUnity Auto Translator 5.3.0]
[Info   :Il2CppInterop] Registered mono type XUnity.AutoTranslator.Plugin.Core.PluginLoader+AutoTranslatorProxyBehaviour in il2cpp domain
[Info   :   BepInEx] Loading [XUnity Resource Redirector 2.1.0]
[Message:   BepInEx] Chainloader startup complete
[Message:     Unity] ?녈깯?녈깋?묆꺖?듐꺖?앮쐿??
[Info   :XUnity.AutoTranslator] Force loading ALL proxy assemblies.
[Warning:XUnity.AutoTranslator] Failed creating fast reflection delegate through with cecil. Retrying with reflection emit...
System.ArgumentException: FieldInfo type does not match return type.
   at XUnity.Common.Utilities.CecilFastReflectionHelper.CreateFastFieldGetter[T,F](FieldInfo fieldInfo)
   at XUnity.Common.Utilities.CustomFastReflectionHelper.CreateFastFieldGetterForCecil[T,F](FieldInfo fieldInfo)
[Warning:XUnity.AutoTranslator] Failed creating fast reflection delegate through with reflection emit. Falling back to standard reflection...
System.ArgumentException: FieldInfo type does not match return type.
   at XUnity.Common.Utilities.ReflectionEmitFastReflectionHelper.CreateFastFieldGetter[T,F](FieldInfo fieldInfo)
   at XUnity.Common.Utilities.CustomFastReflectionHelper.CreateFastFieldGetterForCecil[T,F](FieldInfo fieldInfo)
[Warning:XUnity.AutoTranslator] Could not find 'UnityEngine.TextMesh' in IL2CPP domain even though it could be found in the managed domain.
[Warning:XUnity.AutoTranslator] Could not find 'UnityEngine.GUI+ToolbarButtonSize' in IL2CPP domain even though it could be found in the managed domain.
[Warning:XUnity.AutoTranslator] Could not find 'UnityEngine.ImageConversion' in IL2CPP domain even though it could be found in the managed domain.
[Info   :XUnity.AutoTranslator] Version of TextMesh Pro: 1.4.0.
[Warning:  HarmonyX] AccessTools.Method: Could not find method for type TMPro.TMP_Text and name SetCharArray and parameters (Il2CppInterop.Runtime.InteropTypes.Arrays.Il2CppStructArray<int>, int, int)
[Warning:XUnity.AutoTranslator] Could not hook 'TMP_Text_SetCharArray_Hook3'. Likely due differences between different versions of the engine or text framework.
[Info   :XUnity.AutoTranslator] Attempting to load TextMesh Pro font from asset bundle.
[Info   :XUnity.AutoTranslator] Loaded TextMesh Pro font uses version: 1.1.0
[Warning:XUnity.AutoTranslator] TextMesh Pro version mismatch. Font asset version: 1.1.0, TextMesh Pro version: 1.4.0
[Info   :XUnity.AutoTranslator] Loaded fallback font for TextMesh Pro: arialuni_sdf_u2019
[Info   :XUnity.AutoTranslator] Loaded XUnity.AutoTranslator into Unity [2022.3.16f1] game.
[Info   :Il2CppInterop] Registered mono type XUnity.AutoTranslator.Plugin.Core.Il2CppManagedEnumerator in il2cpp domain
[Warning:XUnity.AutoTranslator] Input API is not available!
System.TypeLoadException: Could not load type 'UnityEngine.Input' from assembly 'UnityEngine.CoreModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at XUnity.AutoTranslator.Plugin.Core.AutoTranslationPlugin.HandleInput()
   at XUnity.AutoTranslator.Plugin.Core.AutoTranslationPlugin.HandleInputSafe()
[Info   :XUnity.AutoTranslator] Skipping plugin scan because no plugin-specific translations has been registered.
[Info   :XUnity.AutoTranslator] Attempting to load TextMesh Pro font from asset bundle.
[Error  :     Unity] The AssetBundle 'C:\Users\pokem\Downloads\Version_B\DECOY獰ㅹ쓵??춸也쿣er1.02\arialuni_sdf_u2019' can't be loaded because another AssetBundle with the same files is already loaded.
[Warning:XUnity.AutoTranslator] Could not load asset bundle while loading font: C:\Users\pokem\Downloads\Version_B\DECOY獰ㅹ쓵??춸也쿣er1.02\arialuni_sdf_u2019
[Message:     Unity] TitleGameMode(Clone) (StrayCatLab.Game.TitleGameMode)?뚣궩?껁깉?뺛굦?얇걮??
[Message:     Unity] TitleGameMode(Clone) (StrayCatLab.Game.TitleGameMode)destroyed
[Message:     Unity] GameMode(Clone) (StrayCatLab.Game.MainGameMode)?뚣궩?껁깉?뺛굦?얇걮??
[Error  :XUnity.AutoTranslator] An unexpected error occurred during maintenance.
System.MissingMethodException: Method not found: 'IntPtr Il2CppInterop.Runtime.IL2CPP.il2cpp_gchandle_get_target(UInt32)'.
   at XUnity.Common.Extensions.ObjectExtensions.IsCollected(Il2CppObjectBase that)
   at XUnity.Common.Utilities.ExtensionDataHelper.Cull()
   at XUnity.Common.Utilities.MaintenanceHelper.MaintenanceLoop(Object state)
-------------------------------------------------------------------------------------------------------------------------------------------------
[Error  :XUnity.AutoTranslator] An unexpected error occurred during maintenance.
System.MissingMethodException: Method not found: 'IntPtr Il2CppInterop.Runtime.IL2CPP.il2cpp_gchandle_get_target(UInt32)'.
   at XUnity.Common.Extensions.ObjectExtensions.IsCollected(Il2CppObjectBase that)
   at XUnity.Common.Utilities.ExtensionDataHelper.Cull()
   at XUnity.Common.Utilities.MaintenanceHelper.MaintenanceLoop(Object state)
[Message:     Unity] GameMode(Clone) ([StrayCatLab.Game](https://oo.pe/http://StrayCatLab.Game).MainGameMode)destroyed
[Message:     Unity] TitleGameMode(Clone) ([StrayCatLab.Game](https://oo.pe/http://StrayCatLab.Game).TitleGameMode)?뚣궩?껁깉?뺛굦?얇걮??
[Message:     Unity] TitleGameMode(Clone) ([StrayCatLab.Game](https://oo.pe/http://StrayCatLab.Game).TitleGameMode)destroyed
[Message:     Unity] GameMode(Clone) ([StrayCatLab.Game](https://oo.pe/http://StrayCatLab.Game).MainGameMode)?뚣궩?껁깉?뺛굦?얇걮??
[Error  :XUnity.AutoTranslator] An unexpected error occurred during maintenance.
System.MissingMethodException: Method not found: 'IntPtr Il2CppInterop.Runtime.IL2CPP.il2cpp_gchandle_get_target(UInt32)'.
   at XUnity.Common.Extensions.ObjectExtensions.IsCollected(Il2CppObjectBase that)
   at XUnity.Common.Utilities.ExtensionDataHelper.Cull()
   at XUnity.Common.Utilities.MaintenanceHelper.MaintenanceLoop(Object state)

**Comment by ManlyMarco** [comment]
The input error was fixed in https://github.com/bbepis/XUnity.AutoTranslator/pull/467
Other errors can be safely ignored.
