### ISSUE TITLE
 The font problem when translating game Digimon World Next Order

### ISSUE THREAD

**Issue by W1K43536** [bbepis/XUnity.AutoTranslator#499]
Game Digimon World Next Order (on IL2CPP) Problem with Cyrillic font upon launching the game, it's completely absent even when setting arialuni_sdf_u2018 or arialuni_sdf_u2019.
I've tried both BepInEx and MelonMod versions. 
Posts #290 and #287 yielded no results. 
It seems like the game refuses to accept the font and attempts to use its own exclusively.
(Sorry for my English) 
![1](https://github.com/bbepis/XUnity.AutoTranslator/assets/160611894/eeec4d5d-49d9-4201-b938-8085b9d531a3)
![2](https://github.com/bbepis/XUnity.AutoTranslator/assets/160611894/89538e0b-f049-41c8-a7c3-0d4407c63aec)

**Comment by Atamg1994** [comment]
Install Melon loader version 0.5.7
Install [XUnity.AutoTranslator-MelonMod-IL2CPP-5.2.0.zip]

After installation, put two files from the archive into the mods folder
[Mods.zip](https://github.com/bbepis/XUnity.AutoTranslator/files/14456413/Mods.zip)


(https://github.com/bbepis/XUnity.AutoTranslator/releases/download/v5.2.0/XUnity.AutoTranslator-MelonMod-IL2CPP-5.2.0.zip)
then unzip the folders from the archive into the game server
![image](https://github.com/bbepis/XUnity.AutoTranslator/assets/57526178/7bf0e31a-32ff-4dba-9e02-4a57e738a8ea)
![image](https://github.com/bbepis/XUnity.AutoTranslator/assets/57526178/208b6dfc-607e-41bb-aa9f-d212ffc7f212)
![image](https://github.com/bbepis/XUnity.AutoTranslator/assets/57526178/47b1fd19-deed-439d-91c6-f1b270a7ee46)
![image](https://github.com/bbepis/XUnity.AutoTranslator/assets/57526178/afb5faea-f076-477d-a190-454f1245da39)

**Comment by W1K43536** [comment]
> Установка загрузчика Melon версии 0.5.7 Установка [XUnity.AutoTranslator-MelonMod-IL2CPP-5.2.0.zip] (https://github.com/bbepis/XUnity.AutoTranslator/releases/download/v5.2.0/XUnity.AutoTranslator-MelonMod-IL2CPP-5.2.0.zip) После установки поместите два файла из архива в папку mods [Mods.zip](https://github.com/bbepis/XUnity.AutoTranslator/files/14456413/Mods.zip)
> 
> ![image](https://private-user-images.githubusercontent.com/57526178/309142393-7bf0e31a-32ff-4dba-9e02-4a57e738a8ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyNzczMDUsIm5iZiI6MTcwOTI3NzAwNSwicGF0aCI6Ii81NzUyNjE3OC8zMDkxNDIzOTMtN2JmMGUzMWEtMzJmZi00ZGJhLTllMDItNGE1N2U3MzhhOGVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAxVDA3MTAwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBjZGMwNjRmYmVjMWZiMzNjYmY4YmE1MDQxMTRlMGNkMGQ1MzM4ZjMxMzFlNTk3MTFhNTJhNzExYjgyMjM0YmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.I1NNLNKEi0vhRhEK0zBmTQeNyUIuHSq-dedYf-_xHKQ) ![image](https://private-user-images.githubusercontent.com/57526178/309146509-208b6dfc-607e-41bb-aa9f-d212ffc7f212.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyNzczMDUsIm5iZiI6MTcwOTI3NzAwNSwicGF0aCI6Ii81NzUyNjE3OC8zMDkxNDY1MDktMjA4YjZkZmMtNjA3ZS00MWJiLWFhOWYtZDIxMmZmYzdmMjEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAxVDA3MTAwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJjMjc0Y2JkOGE1YzVkMzVlNDcyZjJmNGE5NWRlM2NjZTA4MDdlZmI4Mjc4NjI2YzBmYzFiYmE0NDk0NDY3MjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ozq8Ndr5wbWdKGhfckSNdE76GW8pQuPs4y2FrDBlp3w) ![image](https://private-user-images.githubusercontent.com/57526178/309146538-47b1fd19-deed-439d-91c6-f1b270a7ee46.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyNzczMDUsIm5iZiI6MTcwOTI3NzAwNSwicGF0aCI6Ii81NzUyNjE3OC8zMDkxNDY1MzgtNDdiMWZkMTktZGVlZC00MzlkLTkxYzYtZjFiMjcwYTdlZTQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAxVDA3MTAwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1M2YxMDA4NTE5ODY0MmRhZGY2NDg5NTkxOTY2MDZhZWE2YjM2ZDAxNWEyYzdmM2U5OGQ5MmVmZDM2NDc3NzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.U9nK91vHnf7YktbxQWoc0dnTzIhW8C88wl0zJZez2DQ) ![image](https://private-user-images.githubusercontent.com/57526178/309146683-afb5faea-f076-477d-a190-454f1245da39.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyNzczMDUsIm5iZiI6MTcwOTI3NzAwNSwicGF0aCI6Ii81NzUyNjE3OC8zMDkxNDY2ODMtYWZiNWZhZWEtZjA3Ni00NzdkLWExOTAtNDU0ZjEyNDVkYTM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAxVDA3MTAwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAxNDI2NDBmZmU3Yzg3MjdjZDFiOGMxZDA3ZmFiYTgwOWU0YThkZjY3MzA4MGE4YjZhZGU3Y2YzNzYxYzQ2Y2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YrLZ2ICSJ9wKuM4ijw9XYc8COUtDQEkOD5wL2QeHkHI)

thank you very much : )

**Comment by Johntaber0007** [comment]
@Atamg1994 Can you help me create a Thai font?
