### ISSUE TITLE
How i fix it?

### ISSUE THREAD

**Issue by knightfordarx** [bbepis/XUnity.AutoTranslator#520]
[Warning:XUnity.AutoTranslator] Disabling translation scoping because the SceneManager API is not supported in this version of Unity.
[Info   :XUnity.AutoTranslator] Attempting to load TextMesh Pro font from asset bundle.
[Error  :XUnity.AutoTranslator] Could not find an appropriate asset bundle load method while loading font: D:\Download\[Thai&Eng UoU] MassageShop [v1.85]\massageshop
[Info   :XUnity.AutoTranslator] Cannot use fallback font because it is not supported in this version.
[Info   :XUnity.AutoTranslator] Loaded XUnity.AutoTranslator into Unity [2021.3.21f1] game.
[Info   :Il2CppInterop] Registered mono type XUnity.AutoTranslator.Plugin.Core.Il2CppManagedEnumerator in il2cpp domain
[Warning:XUnity.AutoTranslator] Input API is not available!
System.TypeLoadException: Could not load type 'UnityEngine.Input' from assembly 'UnityEngine.CoreModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at XUnity.AutoTranslator.Plugin.Core.AutoTranslationPlugin.HandleInput()
   at XUnity.AutoTranslator.Plugin.Core.AutoTranslationPlugin.HandleInputSafe()
[Info   :XUnity.AutoTranslator] Skipping plugin scan because no plugin-specific translations has been registered.

**Comment by ManlyMarco** [comment]
Fixed in #531
