### ISSUE TITLE
The version of BepInEx can be translated normally in the game but cannot be used to call up the UI with alt+0

### ISSUE THREAD

**Issue by swarn1** [bbepis/XUnity.AutoTranslator#527]
Why do I use the BepInEx version, which can translate normally in the game, but alt+0 cannot call up the interface, and I can only change the translator through config file.

**Comment by swarn1** [comment]
Looking through the debug log, I only saw this error [Error  :XUnity.AutoTranslator] An error occurred in Update callback. 
System.InvalidOperationException: You are trying to read Input using the UnityEngine.Input class, but you have switched active Input handling to Input System package in Player Settings.

**Comment by Leowolf93** [comment]
save question.

**Comment by ManlyMarco** [comment]
Duplicate of #329
