### ISSUE TITLE
Corpse Party - Blood Drive

### ISSUE THREAD

**Issue by SmilingVLADISLAV** [bbepis/XUnity.AutoTranslator#53]
Help to configure. In the game, the text looks like squares, but if you press Atl+1 (Translation Aggregator), the translation is normal, what could be the problem? Help please.
![Image 018](https://user-images.githubusercontent.com/56461225/66693178-0284a900-ecf2-11e9-993e-464ad016144e.png)
![Image 019](https://user-images.githubusercontent.com/56461225/66693188-19c39680-ecf2-11e9-9043-dfd9ce051345.png)

**Comment by SmilingVLADISLAV** [comment]
AI The Somnium Files. Again.
![Image 020](https://user-images.githubusercontent.com/56461225/66695023-8c8b3c80-ed07-11e9-87da-598ec6f1620f.png)

**Comment by gravydevsupreme** [comment]
These issues occur when the font used in the game does not support the character set used in a language.

You can try setting the following configuration:
 * `OverrideFont=Arial`
 * `OverrideFontTextMeshPro=Fonts & Materials/ARIAL SDF`
 * `OverrideFontTextMeshPro=Fonts & Materials/LiberationSans SDF`

I can see you already tried to set OverrideFont to Arial, which suggest the game uses TextMeshPro and that requires fonts to be build specifically for a game. Often the developer will choose only the exact character set that a language needs when building the font.

Currently the only way to get around this is to hope that the game comes with a "default" font that supports more characters (the ones mentioned in configuration snippets above).

**Comment by SmilingVLADISLAV** [comment]
It's not working. But thanks for the help.

**Comment by gravydevsupreme** [comment]
Check out the following issue https://github.com/bbepis/XUnity.AutoTranslator/issues/57#issuecomment-562344581

I am closing this to keep discussion in one thread.
