### ISSUE TITLE
The Letter - Horror Visual Novel

### ISSUE THREAD

**Issue by SmilingVLADISLAV** [bbepis/XUnity.AutoTranslator#54]
Tried "The Letter-Horror Visual Novel", does not catch the text.

**Comment by gravydevsupreme** [comment]
Tried the demo available [here](https://www.kickstarter.com/projects/yangyangmobile/the-letter-2) and that seems to work just fine. Can you confirm if this demo works for you?

**Comment by SmilingVLADISLAV** [comment]
Demo Works, but in the full version of Steam does not catch the text.

**Comment by gravydevsupreme** [comment]
Sounds like the full game may be compiled with IL2CPP.

Please provide a screenshot of the files in the `The Letter_Data\Managed` folder.

**Comment by SmilingVLADISLAV** [comment]
![Image 022](https://user-images.githubusercontent.com/56461225/66714998-a745da00-ee09-11e9-97ff-fcf7ccdb7ce6.png)

**Comment by SmilingVLADISLAV** [comment]
> Sounds like the full game may be compiled with IL2CPP.
> 
> Please provide a screenshot of the files in the `The Letter_Data\Managed` folder.

![Image 022](https://user-images.githubusercontent.com/56461225/66715005-bfb5f480-ee09-11e9-8141-5b26499c9b72.png)

**Comment by gravydevsupreme** [comment]
No IL2CPP to see there. Once I obtain the game I can take a closer look.

**Comment by SmilingVLADISLAV** [comment]
> No IL2CPP to see there. Once I obtain the game I can take a closer look.

I will try to download on Yandex.Disk, in game like there is no protection. Starts with Steam off.

**Comment by gravydevsupreme** [comment]
No need. Already tried it out now.

The issue is the same as https://github.com/bbepis/XUnity.AutoTranslator/issues/49

Apparently there is a certificate validation issue in this Mono Runtime.

Set config:
```ini
[Http]
DisableCertificateValidation=True
```

I may disable these stupid checks permanently.

**Comment by SmilingVLADISLAV** [comment]
> No need. Already tried it out now.
> 
> The issue is the same as #49
> 
> Apparently there is a certificate validation issue in this Mono Runtime.
> 
> Set config:
> 
> ```ini
> [Http]
> DisableCertificateValidation=True
> ```
> 
> I may disable these stupid checks permanently.

It helped, thank you very much.
