### ISSUE TITLE
[Message:    NullReferenceException: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by astef89** [bbepis/XUnity.AutoTranslator#541]
Hi everyone...I open this discussion....to ask you for help on this...the game in question is PC bunding simualor 2 translated with the Italian translation...the game translates well...but when I do the tutorial, every tutorial gives me the damn error...
[Message: Unity] Loading a case with customization data version: 0
[Warning:XUnity.AutoTranslator] Input API is not available!
System.TypeLoadException: Could not load type 'UnityEngine.Input' from assembly 'UnityEngine.CoreModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
at XUnity.AutoTranslator.Plugin.Core.AutoTranslationPlugin.HandleInput()
at XUnity.AutoTranslator.Plugin.Core.AutoTranslationPlugin.HandleInputSafe()
[Info :XUnity.AutoTranslator] Skipping plugin scan because no plugin-specific translations has been registered.
[Error :XUnity.AutoTranslator] Error occurred during translation.
System.NullReferenceException: Object reference not set to an instance of an object.

and the game freezes...please help me..is it a plugin error? Is there a way to resolve the situation? and since May 25th I've been trying to resolve...
I need to put something in the config file, can you enlighten me? Thanks in advance
[LogOutput.log](https://github.com/user-attachments/files/15517877/LogOutput.log)
I attach the log file..
after I try the tutorial the game doesn't progress and I have to close the game

**Comment by ManlyMarco** [comment]
Fixed in #531
