### ISSUE TITLE
New translator not detected

### ISSUE THREAD

**Issue by ammarpvl29** [bbepis/XUnity.AutoTranslator#544]
I tried to add new translator into XUnity called LibreTranslate (open-source API translation but i selfhosted it on my device) added the correspond LibreTranslate.dll into the Translators folder and new line to the config
[Service]
Endpoint=LibreTranslate
FallbackEndpoint=GoogleTranslateV2
...
[LibreTranslate]
Url=http://localhost:5000/

but when i launched the game that i want to translate, XUnity did not detect LibreTranslate, tried alt+0 and on Endpoint it shows blank, but FallbackEndpoint still shows GoogleTranslateV2. Maybe someone here can give some insights? ty in advance

**Comment by Atamg1994** [comment]
> I tried to add new translator into XUnity called LibreTranslate (open-source API translation but i selfhosted it on my device) added the correspond LibreTranslate.dll into the Translators folder and new line to the config [Service] Endpoint=LibreTranslate FallbackEndpoint=GoogleTranslateV2 ... [LibreTranslate] Url=http://localhost:5000/
> 
> but when i launched the game that i want to translate, XUnity did not detect LibreTranslate, tried alt+0 and on Endpoint it shows blank, but FallbackEndpoint still shows GoogleTranslateV2. Maybe someone here can give some insights? ty in advance


You say the source code is open. .. but the code itself is not provided... Everything works for me.. I have a custom translator that sends requests to the node js server and everything works... no problems.. That's why you have a problem in the code of all things

**Comment by ammarpvl29** [comment]
well if you are talking about the code of libre endpoint, this is it
`using System;
using System.Collections.Generic;
using System.Text;
using XUnity.AutoTranslator.Plugin.Core.Endpoints.Http;
using XUnity.AutoTranslator.Plugin.Core.Endpoints;
using XUnity.AutoTranslator.Plugin.Core.Web;
using Newtonsoft.Json;
using HtmlAgilityPack;

namespace LibreTranslate
{
    internal class LibreTranslateEndpoint : HttpEndpoint
    {
        private const string ApiUrl = "http://localhost:5000/";

        public override string Id => "LibreTranslate";
        public override string FriendlyName => "LibreTranslate";

        public override void Initialize(IInitializationContext context)
        {

        }

        public override void OnCreateRequest(IHttpRequestCreationContext context)
        {
            var requestBody = new
            {
                q = context.UntranslatedText,
                source = context.SourceLanguage,
                target = context.DestinationLanguage
            };
            var jsonData = JsonConvert.SerializeObject(requestBody);
            var encodedData = System.Uri.EscapeDataString(jsonData);

            var requestUri = new Uri($"http://localhost:5000/{encodedData}");
            var request = new XUnityWebRequest(requestUri.ToString(), "POST");

            context.Complete(request);
        }

        public override void OnExtractTranslation(IHttpTranslationExtractionContext context)
        {
            var responseData = context.Response.Data;
            var responseObject = JsonConvert.DeserializeObject<LibreTranslateResponse>(responseData);

            if (!string.IsNullOrEmpty(responseObject.translatedText))
            {
                context.Complete(responseObject.translatedText);
            }
            else
            {
                context.Fail("No translation received from LibreTranslate API.");
            }
        }

        private class LibreTranslateResponse
        {
            public string translatedText;
        }
    }
}
`

**Comment by Atamg1994** [comment]
> public override void Initialize(IInitializationContext context)
>     {
> 
>     }


my example

```
using System;
using System.Collections.Generic;
using XUnity.AutoTranslator.Plugin.Core.Endpoints;
using XUnity.AutoTranslator.Plugin.Core.Endpoints.Http;
using XUnity.AutoTranslator.Plugin.Core.Web;

namespace CustomTranslateBanch
{
	// Token: 0x02000002 RID: 2
	internal class CustomTranslateBanchEndpoint : global::XUnity.AutoTranslator.Plugin.Core.Endpoints.Http.HttpEndpoint
	{
		// Token: 0x06000001 RID: 1 RVA: 0x00002050 File Offset: 0x00000250
		public CustomTranslateBanchEndpoint()
		{
			this._friendlyName = "Custom";
		}

		// Token: 0x17000001 RID: 1
		// (get) Token: 0x06000002 RID: 2 RVA: 0x00002063 File Offset: 0x00000263
		public override string Id
		{
			get
			{
				return "CustomTranslateBanch";
			}
		}

		// Token: 0x17000002 RID: 2
		// (get) Token: 0x06000003 RID: 3 RVA: 0x0000206A File Offset: 0x0000026A
		public override string FriendlyName
		{
			get
			{
				return this._friendlyName;
			}
		}

		// Token: 0x06000004 RID: 4 RVA: 0x00002080 File Offset: 0x00000280
		public override void Initialize(global::XUnity.AutoTranslator.Plugin.Core.Endpoints.IInitializationContext context)
		{
			this._endpoint = context.GetOrCreateSetting<string>("CustomTranslateBanch", "Url", "");
			if (string.IsNullOrEmpty(this._endpoint))
			{
				throw new global::XUnity.AutoTranslator.Plugin.Core.Endpoints.EndpointInitializationException("The custom endpoint requires a url which has not been provided.");
			}
			global::System.Uri uri = new global::System.Uri(this._endpoint);
			context.DisableCertificateChecksFor(new string[]
			{
				uri.Host
			});
			this._friendlyName = this._friendlyName + " (" + uri.Host + ")";
		}

		// Token: 0x06000005 RID: 5 RVA: 0x00002104 File Offset: 0x00000304
		public override void OnCreateRequest(global::XUnity.AutoTranslator.Plugin.Core.Endpoints.Http.IHttpRequestCreationContext context)
		{
			string stringToEscape = string.Join("\n", context.UntranslatedTexts);
			global::XUnity.AutoTranslator.Plugin.Core.Web.XUnityWebRequest xunityWebRequest = new global::XUnity.AutoTranslator.Plugin.Core.Web.XUnityWebRequest(string.Format(global::CustomTranslateBanch.CustomTranslateBanchEndpoint.ServicePointTemplateUrl, new object[]
			{
				this._endpoint,
				context.SourceLanguage,
				context.DestinationLanguage,
				global::System.Uri.EscapeDataString(stringToEscape)
			}));
			context.Complete(xunityWebRequest);
		}

		// Token: 0x06000006 RID: 6 RVA: 0x00002164 File Offset: 0x00000364
		public override void OnExtractTranslation(global::XUnity.AutoTranslator.Plugin.Core.Endpoints.Http.IHttpTranslationExtractionContext context)
		{
			string data = context.Response.Data;
			if (string.IsNullOrEmpty(data))
			{
				context.Complete(context.UntranslatedText);
				return;
			}
			if (context.UntranslatedTexts.Length == 1)
			{
				context.Complete(data);
				return;
			}
			string[] array = data.Split(new char[]
			{
				'\n'
			});
			global::System.Collections.Generic.List<string> list = new global::System.Collections.Generic.List<string>();
			int num = 0;
			string[] untranslatedTexts = context.UntranslatedTexts;
			for (int i = 0; i < untranslatedTexts.Length; i++)
			{
				int num2 = untranslatedTexts[i].Split(new char[]
				{
					'\n'
				}).Length;
				string text = string.Empty;
				for (int j = 0; j < num2; j++)
				{
					if (num >= array.Length)
					{
						context.Fail("Batch operation received incorrect number of translations.");
					}
					string str = array[num++];
					text += str;
					if (j != num2 - 1)
					{
						text += "\n";
					}
				}
				list.Add(text);
			}
			if (num != array.Length)
			{
				context.Fail("Batch operation received incorrect number of translations.");
			}
			context.Complete(list.ToArray());
		}

		// Token: 0x06000007 RID: 7 RVA: 0x00002072 File Offset: 0x00000272
		static CustomTranslateBanchEndpoint()
		{
		}

		// Token: 0x04000001 RID: 1
		private static readonly string ServicePointTemplateUrl = "{0}?from={1}&to={2}&text={3}";

		// Token: 0x04000002 RID: 2
		private string _endpoint;

		// Token: 0x04000003 RID: 3
		private string _friendlyName;
	}
}
```

**Comment by Atamg1994** [comment]
this._friendlyName  = // field stores the name of the translator in the selection menu

**Comment by Atamg1994** [comment]
and generally take the utility 
https://github.com/dnSpy/dnSpy

and if something is not clear with the help of this utility, you look at how the standard translators that come with the kit are written...

and I assure you.. you will no longer create such topics... 
because there is no need.
and if something is not clear in the code, there is ChatGPT

**Comment by ammarpvl29** [comment]
awesome, thank you for the insights it worked! also gpt is my last resort if someone did not answer this issue but you are here!!! thank you again

**Comment by Atamg1994** [comment]
у вас клас 

> awesome, thank you for the insights it worked! also gpt is my last resort if someone did not answer this issue but you are here!!! thank you again

that’s the bad thing... you essentially don’t value people...
GPT chat should be in first place since this is a machine bot 
and it just needs to be used to the fullest

and the last resort is to contact people...

**Comment by Atamg1994** [comment]
> awesome, thank you for the insights it worked! also gpt is my last resort if someone did not answer this issue but you are here!!! thank you again

close the topic if everything is resolved.. 
don’t waste the admin’s time checking and closing
