### ISSUE TITLE
[ERROR] Could not find the configured endpoint (custom translation)

### ISSUE THREAD

**Issue by ammarpvl29** [bbepis/XUnity.AutoTranslator#545]
Hey, need some insights again. Was trying with gpt but could not find any answers.
Basically my problem was like when i used 

[Service]
Endpoint=LibreTranslate
FallbackEndpoint=GoogleTranslateV2
This did not work but when i changed it into

[Service]
Endpoint=CustomTranslate
FallbackEndpoint=GoogleTranslateV2
it worked but the translation felt off, i can still see the debugging on my screen like the doctype html etc

i thought the issue might be related to the naming and configuration of the endpoint. since CustomTranslate worked but LibreTranslate did not, there could be a discrepancy between the configuration and the implementation.

still, i ensure configuration file (AutoTranslatorConfig.ini) matches the settings expected by the implementation. and i also place the generated LibreTranslate.dll in the Translators folder of XUnity Auto Translator.

but it still didn't work! is there something i overlook here?

**Comment by Atamg1994** [comment]
> Hey, need some insights again. Was trying with gpt but could not find any answers. Basically my problem was like when i used
> 
> [Service] Endpoint=LibreTranslate FallbackEndpoint=GoogleTranslateV2 This did not work but when i changed it into
> 
> [Service] Endpoint=CustomTranslate FallbackEndpoint=GoogleTranslateV2 it worked but the translation felt off, i can still see the debugging on my screen like the doctype html etc
> 
> i thought the issue might be related to the naming and configuration of the endpoint. since CustomTranslate worked but LibreTranslate did not, there could be a discrepancy between the configuration and the implementation.
> 
> still, i ensure configuration file (AutoTranslatorConfig.ini) matches the settings expected by the implementation. and i also place the generated LibreTranslate.dll in the Translators folder of XUnity Auto Translator.
> 
> but it still didn't work! is there something i overlook here?

code ?

**Comment by ammarpvl29** [comment]
ah my bad! i changed it similar to the sourcecode of CustomTranslate.cs
using System;
using System.Collections.Generic;
using XUnity.AutoTranslator.Plugin.Core.Endpoints;
using XUnity.AutoTranslator.Plugin.Core.Endpoints.Http;
using XUnity.AutoTranslator.Plugin.Core.Web;
using Newtonsoft.Json;

namespace LibreTranslate
{
    internal class LibreTranslateEndpoint : HttpEndpoint
    {
        private static readonly string ServicePointTemplateUrl = "http://localhost:5000/?source=zh&target=en&q=";
        private string _endpoint;
        private string _friendlyName;

        public LibreTranslateEndpoint()
        {
            _friendlyName = "LibreTranslate";
        }

        public override string Id => "LibreTranslate";

        public override string FriendlyName => _friendlyName;

        public override void Initialize(IInitializationContext context)
        {
            _endpoint = context.GetOrCreateSetting<string>("LibreTranslate", "Url", ServicePointTemplateUrl);
            if (string.IsNullOrEmpty(_endpoint))
            {
                throw new EndpointInitializationException("The LibreTranslate endpoint requires a URL which has not been provided.");
            }

            var uri = new Uri(_endpoint);
            context.DisableCertificateChecksFor(uri.Host);
            _friendlyName += $" ({uri.Host})";
        }

        public override void OnCreateRequest(IHttpRequestCreationContext context)
        {
            string untranslatedText = string.Join("\n", context.UntranslatedTexts);
            string requestUri = string.Format(ServicePointTemplateUrl, _endpoint, context.SourceLanguage, context.DestinationLanguage, Uri.EscapeDataString(untranslatedText));
            var request = new XUnityWebRequest(requestUri);

            context.Complete(request);
        }

        public override void OnExtractTranslation(IHttpTranslationExtractionContext context)
        {
            string data = context.Response.Data;
            if (string.IsNullOrEmpty(data))
            {
                context.Complete(context.UntranslatedText);
                return;
            }

            var responseObject = JsonConvert.DeserializeObject<LibreTranslateResponse>(data);
            if (context.UntranslatedTexts.Length == 1)
            {
                context.Complete(responseObject.translatedText);
            }
            else
            {
                string[] translatedTexts = responseObject.translatedText.Split('\n');
                var translatedList = new List<string>();

                int index = 0;
                foreach (var untranslatedText in context.UntranslatedTexts)
                {
                    int numLines = untranslatedText.Split('\n').Length;
                    string translation = string.Join("\n", translatedTexts, index, numLines);
                    index += numLines;
                    translatedList.Add(translation);
                }

                if (index != translatedTexts.Length)
                {
                    context.Fail("Batch operation received incorrect number of translations.");
                }

                context.Complete(translatedList.ToArray());
            }
        }

        private class LibreTranslateResponse
        {
            public string translatedText { get; set; }
        }
    }
}

**Comment by Atamg1994** [comment]
Are there any errors in the console??

does the request reach your_endpoint?

**Comment by ammarpvl29** [comment]
That is the jest of this issue, when i used 
Endpoint = Custom... it worked
Enpoint = LibreTranslate it did not

i tested both for the url
[Custom]
Url=http://localhost:5000/?source=zh&target=en&q= -> worked
[LibreTranslate]
Url=http://localhost:5000/?source=zh&target=en&q= -> did not worked

**Comment by Atamg1994** [comment]
listen dude to the console logs!!! Do you understand what logs are??

Maybe your text is coming in the wrong format in the response and you have lost some logs??

**Comment by ammarpvl29** [comment]
Ah my bad, i checked and the only error Error (active)	CS5001	Program does not contain a static 'Main' method suitable for an entry point	cause it's a class library
now my library consists of:
XUnity.AutoTranslator.Plugin.Core.dll
C:\Users\user\.nuget\packages\htmlagilitypack\1.11.61\
C:\Users\user\.nuget\packages\netstandard.library\2.0.3\
C:\Users\user\.nuget\packages\newtonsoft.json\13.0.3\

**Comment by Atamg1994** [comment]
try this
I'm too lazy to understand your code, here's my example of a link 
local translation cache server, what is not found in the cache is obtained using the Google API
[Service]
Endpoint=CustomTranslateBanch
FallbackEndpoint=


[CustomTranslateBanch]
Url=http://localhost:4000/translate_batch_app

put this in translators
for melomn loader UserLibs\Translators
fod bepinex  find it yourself I don’t remember where his files are
[CustomTranslateBanch.zip](https://github.com/user-attachments/files/15913547/CustomTranslateBanch.zip)

you need node js installed

here run the installation once 
and then start it GoogleTranslator_server.cmd
[node_GoogleTranslator_server.zip](https://github.com/user-attachments/files/15913549/node_GoogleTranslator_server.zip)

**Comment by ammarpvl29** [comment]
damn, oki then i will try. also i was using netstandard 2.0 but based on the documentation its not a must to use net35 right

**Comment by Atamg1994** [comment]
> try this I'm too lazy to understand your code, here's my example of a link local translation cache server, what is not found in the cache is obtained using the Google API
> 
> ```
> [Service]
> Endpoint=CustomTranslateBanch
> FallbackEndpoint=
> 
> 
> [CustomTranslateBanch]
> Url=http://localhost:4000/translate_batch_app
> ```
> 
> put this in translators for melomn loader UserLibs\Translators fod bepinex find it yourself I don’t remember where his files are [CustomTranslateBanch.zip](https://github.com/user-attachments/files/15913547/CustomTranslateBanch.zip)
> 
> you need node js installed
> 
> here run the installation once and then start it GoogleTranslator_server.cmd [node_GoogleTranslator_server.zip](https://github.com/user-attachments/files/15913549/node_GoogleTranslator_server.zip)

The purpose of this server is mainly to use Google less and to pull up translations from the cache 

and fixing html markup Google sometimes likes to break it, so when translating we exclude markup from translation for the duration of translation
and then we restore 

(This helped me save item icons in some games..)

**Comment by ammarpvl29** [comment]
hmm maybe worth it to setting up server with express js and then make a request to my local web server. It then returns the translated text to XUnity.AutoTranslator
