### ISSUE TITLE
Removing translation text after first \n symbol

### ISSUE THREAD

**Issue by TokcDK** [bbepis/XUnity.AutoTranslator#55]
Details:
Noticing not in first time. Sometime part of translation just removing.
For example in generated file was added line:
`「なにか必要なものでもあるのか？\n　だったらルージットに言って取り寄せてもいいが」\n=“Is there anything that I need?\n`
Second part after new line symbol `\n` just was removed and nothing there but there must be second part of translation. 
It is happening quite long time from older versions and still happens in v.4.4.

If will be need I will share game name and savegame right before this line.

**Comment by gravydevsupreme** [comment]
Please do share.

**Comment by TokcDK** [comment]
<details>
  <summary>game</summary>

[Astronauts] Guildmaster
[アストロノーツ・シリウス] ギルドマスター
version 1.08 ([patches](http://www.astronauts.co.jp/sirius/gildmaster/support.html))
  
</details>

<details>
  <summary>savegame made in dialog right before described line line</summary>
  
[Astronauts_Sirius.zip](https://github.com/bbepis/XUnity.AutoTranslator/files/3721471/Astronauts_Sirius.zip)

Astronauts_Sirius savegames folder located in Documents.
</details>

<details>
  <summary>additionally</summary>

Actually I just tested regex rule for jp quotes for the [issue](https://github.com/bbepis/XUnity.AutoTranslator/issues/46) and there also strange things happens with it because for example I noticed this lines in generated cache:
```
少しくらい特別扱いをしたところで、\n誰からも文句は出ないだろう。=No one will be complaining about the special treatment.
少しくらい特別扱いをしたところで、\n誰からも文句は出ないだろう。\n=No one will be complaining about the special treatment.\n
```
here just was added two variants of same dialog line and only difference in `\n` appeared in second line. Looks like `\n` on line end appearing for some lines sometimes and sometimes not and splitter rule `sr:"^「(.+)」$"=「$1」` sometimes working and sometimes not. I also added `sr:"^「(.+)」\\n"=「$1」\n` to handle second variants where appearing `\n` on the end but it seems it not working but I not tested enough it and maybe just need to modify rule or it is just multiline values which is not matching the regex and I making rules for lines which is adding in generated file. 
Strange things with `\n` on the end of line can be also linked with the issue and because I described the here also.
</details>

**Comment by gravydevsupreme** [comment]
I'll take a look. Do I need to apply all these patches in sequence?

About the regex: It looks fairly flawed to me. 
 * The dot does not catch whitespace.
 * I'm not sure whether or not that is the correct way to handle surrounding whitespace.

Could try this: `sr:"^([\s]*)「([\S\s]+)」([\s]*)$"=$1「$2」$3`

Also, I think this regex `sr:"^「(.+)」\\n"=「$1」\n` might actually be the cause of the issue your are seeing because it matches the texts partially because it has a whitespace in the middle and does not specify the end of string rule '$'.

**Comment by TokcDK** [comment]
I shared patches link in case if game will not load savegame and will need to update. As I know this is not full patches and each requires previous.

About effect of splitter regex rules to the issue. The issue was apeearing before any rules was added and was also in previous versions. 
<details>
  <summary>Made several tests with rules and got next results: (spoiler)</summary>

Dialog from test savegame: `「なにか必要なものでもあるのか？\n　だったらルージットに言って取り寄せてもいいが」\n`
1. No any regex rules and no any substitutions. Result: The issue appeared. Added line  `「なにか必要なものでもあるのか？\n　だったらルージットに言って取り寄せてもいいが」\n=“Is there anything that I need?\n`
2. Added `sr:"^「(.+)」\\n"=「$1」\n` . Result: The rule is not matching. Same result as in first variant.
3. Removed `sr:"^「(.+)」\\n"=「$1」\n`. Added substitution `ルージット=Rugita` to Substitrutions file because it is name of one game characters. Result: The issue disappeared and line was parsed right. Added line `「なにか必要なものでもあるのか？\n　だったら{{A}}に言って取り寄せてもいいが」\n=“Is there anything I need? You can ask {{A}} to order it.”\n`
4. Removed substitution`ルージット=Rugita`. Added rule `sr:"^([\s]*)「([\S\s]+)」([\s]*)$"=$1「$2」$3` .  Result: The issue disappeared. Added line: `なにか必要なものでもあるのか？\n　だったらルージットに言って取り寄せてもいいが=Is there anything necessary? Then you can ask Rugit to order it.`
5. Added substitution`ルージット=Rugita` and rule `sr:"^([\s]*)「([\S\s]+)」([\s]*)$"=$1「$2」$3` not removed. Result: No issue. Added line: `なにか必要なものでもあるのか？\n　だったら{{A}}に言って取り寄せてもいいが=Is there anything necessary? Then you can tell {{A}}`

Notes and result: 
Added line was removed from generated txt before each test step and then used alt+R and test savegame load. 
Test 3. Added substitution fixed the issue and line was parsed with no problem. 
Test 4. Your offered regex rule also fixed the problem and as we already discussed in issue #46 when query without quotes returned translation is more correct.
Test 5. After substitution was added back result translation was changed again.
</details>

**Comment by TokcDK** [comment]
Just noticed also result for lines which was parsed with regex rule `sr:"^([\s]*)「([\S\s]+)」([\s]*)$"=$1「$2」$3` contains no any `\n` symbols(see added line in test 4). And same things when processed substitutions(see added line in test 3).

**Comment by gravydevsupreme** [comment]
Got it working, without locale emulator. No patches applied.

Can reproduce.

But the issue only really seem to appear with Google Translate. Here's an example generated with Bing (no substitutions, regexes).

```
「なにか必要なものでもあるのか？\n　だったらルージットに言って取り寄せてもいいが」\n=Do you need anything? Then I could tell Lujit and order it."\n
```

I'll see if I can track down the potential source.

About no newlines appearing at edges with my regex: The regex essentially strips off that whitespace and "translates" it seperately. But you cannot translate whitespace, so no translations are generated for it.

**Comment by gravydevsupreme** [comment]
Probably found the source of the issue. Which is the google service itself. The service is changed all the time and it can be difficult to know which parameters use.

[GoogleTranslate.zip](https://github.com/bbepis/XUnity.AutoTranslator/files/3721840/GoogleTranslate.zip)

This version adds some new parameters when it makes translation calls that apparently seems to fix it.

**Comment by TokcDK** [comment]
> Here's an example generated with Bing (no substitutions, regexes).

I noticed there also removed \n in the middle and Bing forgot to return first quotation mark `"` . Splitter rule will be even more useful for Bing because Bing breaking them.

> About no newlines appearing at edges with my regex: The regex essentially strips off that whitespace and "translates" it seperately. But you cannot translate whitespace, so no translations are generated for it.

Not only with regex but also happens when substitution added in substitutions and exists in the line.

Removed substitutions and regex rules, replaced dll but still same result:
`「なにか必要なものでもあるのか？\n　だったらルージットに言って取り寄せてもいいが」\n=“Is there anything that I need?\n`
Maybe I must change something and not only replace dll in translators folder?

**Comment by gravydevsupreme** [comment]
Simply replacing the DLL should fix the issue. Did for me, and also confirmed the functionality/bug directly by accessing the API manually. You can try one of these, but the above DLL really should do the trick, unless I somehow magically managed to copy the wrong file, which I really doubt.

[XUnity.AutoTranslator-ReiPatcher-4.5.0.zip](https://github.com/bbepis/XUnity.AutoTranslator/files/3722268/XUnity.AutoTranslator-ReiPatcher-4.5.0.zip)
[XUnity.AutoTranslator-BepIn-5x-4.5.0.zip](https://github.com/bbepis/XUnity.AutoTranslator/files/3722269/XUnity.AutoTranslator-BepIn-5x-4.5.0.zip)

**Comment by TokcDK** [comment]
With archive from latest comment it works and now only removes newline symbols in middle from original.

**Comment by TokcDK** [comment]
<details>
<summary>about multiline lines translation and parsing</summary>

In my programs for detect new lines I add additional line with special symbol after each line in request original like this:
```
「なにか必要なものでもあるのか？
<NEWLINESYMBOL>
　だったらルージットに言って取り寄せてもいいが」
```

then send it to translation service and the get response with translation:
`"Do you need anything? <NEWLINESYMBOL> Then I could tell Lujit and order it."`

then replacing symbol back to newline:
```
"Do you need anything?
Then I could tell Lujit and order it."
```

`<NEWLINESYMBOL>` - any unique symbol like `<XUAT>` or any abbreviation like `XUAT` which will not be touched by translation service.
In the test string Google also removed tab symbol on start of second line of original but it can be restored after by any way.
</details>

**Comment by gravydevsupreme** [comment]
With that being said, you can disable this behaviour, just set `IgnoreWhitespaceInDialogue=False`.

It might cause some translations to be better, but I would argue that the majority will be a lot worse.

**Comment by TokcDK** [comment]
I knew only about quotes make translation worse and didnt know about whitespaces and newline symbols also make translation worse.

**Comment by gravydevsupreme** [comment]
For google and JP translations, newlines are primarily a problem because each lines is generally considered separately, which means all context is lost. And it becomes extra bad if the game decides to place a newline character literally in the middle of a sentence or word. Then the translation endpoint would just return gibberish. Remove non-repeating whitespace before trying to translate a text fixes this.

**Comment by TokcDK** [comment]
Tested today several different strings in google and in some situations translation can be broken from some symbols. For example try to paste this lines to google:
`Louise Ploa"ほーらほら,この区画ごと吹っ飛ぶ魔法を放っちゃうよ～ん!!"`

Here is first word before quote means character name and it often just make translation broken. In this situation need to translate name(if it in japanese) and text between quotes separately.

Also can be broken from japanese symbold or combination of the for example this:
`Louise Ploa"ほーらほら,この区画ごと吹っ飛ぶ魔法を放っちゃうよ～ん!!"`

` `in one japan game displaying as three dots(`...`) and when they are in string and in request string they will breake google translation. In this situation need or remove them before translation or replace by what they mean `...` .
Year or more ago tried to send reports about it but nothing changed and they still breaking translation.

**Comment by gravydevsupreme** [comment]
I am well aware that in some situations remove whitespace works better than others, which is why it is controllable through configuration `IgnoreWhitespaceInDialogue=False`.

Something like that could also be fixed through splitter regexes I would say. Something like:

```
sr:"^([\S\s]+)\n"([\S\s]+)"$"=$1\n"$2"
```

(super untested!)

About the three dots (…). Could probably add some text preprocessors to handle these types of characters.

**Comment by TokcDK** [comment]
Hmm. Today checked `Louise Ploa"ほーらほら,この区画ごと吹っ飛ぶ魔法を放っちゃうよ～ん!!"` line and it no more breaking but was breaking day ago. Maybe I sent fixed variant and it was autofixed or something was changed in gtranslation service after I many times sent the sentence in correct form.
This example is still breaking:
Louise Ploa"うえ,うええぇ～ん,ご主人様がイジメるよ～,チラっ"


Also understood that non japanese punctuation marks in request string can break translation. For example `,.!?` instead of `、。！？`. Example line `アイターッ,容赦ない!容赦ないよご主人様!` will get incorrect translation `Aitut, merciless!` but line `アイターッ、容赦ない！容赦ないよご主人様！` with japanese punctuation marks will be translated as `It's unrelenting! I'm not merciful, my husband!` .

**Comment by gravydevsupreme** [comment]
I will make sure to consider these characters as well once I get around to this feature.

**Comment by TokcDK** [comment]
Ok. I just posted here the info which I knew and found in experiments because it can be useful for translation parsing improvement.

**Comment by gravydevsupreme** [comment]
The latest version of XUA (4.7.0) now has a function that allows preprocessing of text before sending it to the translator. It is a special file (like substitutions) that you can put key-value pairs into. By default the file is called `_Preprocessors.txt`.

Example values:

```
,=、
.=。
…=。。。
```

The file is empty by default, as I am very unsure about what should go into it.

**Comment by TokcDK** [comment]
Ok, understood.
