### ISSUE TITLE
Libretranslate Integration Request

### ISSUE THREAD

**Issue by Neresco** [bbepis/XUnity.AutoTranslator#564]
it is possible to add integration for Libretranslate Selfhosted and Official?
https://github.com/LibreTranslate/LibreTranslate

I have successfully managed to host my own Libretranslate instance in docker and in normal Linux.
Unfortenatly when i add the URL under "CustomTranslate" or "Http" i become garbage out or nothing.
I have read the Issues Tab and found one other human who managed to make it work with custom created dll file.
Looks like i too need to create my own .dll file.
New translator not detected https://github.com/bbepis/XUnity.AutoTranslator/issues/544
I have tried to do the same but have failed to do so.
Is i possible to create a .dll file for all users where we just enter the URL and API-Key?
Proposed solution

I can provide my instance for testing if needed.
Edit: Here is my own LibreTranslate instance:
https://translate.lunarfoundry.duckdns.org/

**Comment by Neresco** [comment]
With help from Chatgpt and later selfhosted llama3 (I do not want to pay) i have succesfully written a dll file.
I have used the base code from [Atamg1994](https://github.com/Atamg1994) under https://github.com/bbepis/XUnity.AutoTranslator/issues/544 for this.

The dll file does not make any error at the moment.
Xunity Autotranslator Log gives some errors with uri scheme.
Can someone with more insight pls help me recognize my error?

The log is:
[Message:   BepInEx] BepInEx 5.4.23.2 - My Lovely Empress (10.09.2024 21:12:51)

[Info   :   BepInEx] Running under Unity v2021.3.13.10386776
[Info   :   BepInEx] CLR runtime version: 4.0.30319.42000
[Info   :   BepInEx] Supports SRE: True
[Info   :   BepInEx] System platform: Bits64, Windows
[Message:   BepInEx] Preloader started
[Info   :   BepInEx] Loaded 1 patcher method from [BepInEx.Preloader 5.4.23.2]
[Info   :   BepInEx] 1 patcher plugin loaded
[Info   :   BepInEx] Patching [UnityEngine.CoreModule] with [BepInEx.Chainloader]
[Message:   BepInEx] Preloader finished
[Message:   BepInEx] Chainloader ready
[Message:   BepInEx] Chainloader started
[Info   :   BepInEx] 3 plugins to load
[Info   :   BepInEx] Loading [Configuration Manager 18.3]
[Info   :   BepInEx] Loading [XUnity Auto Translator 5.4.0]
[Info   :XUnity.AutoTranslator] Version of TextMesh Pro: 1.4.0.
[Warning:  HarmonyX] AccessTools.Method: Could not find method for type TMPro.TMP_Text and name SetCharArray and parameters (int[], int, int)
[Warning:XUnity.AutoTranslator] Could not hook 'TMP_Text_SetCharArray_Hook3'. Likely due differences between different versions of the engine or text framework.
[Error  :XUnity.AutoTranslator] Error occurred during the initialization of the fallback translate endpoint.
XUnity.AutoTranslator.Plugin.Core.Endpoints.EndpointInitializationException: The custom endpoint requires a url which has not been provided.
  at CustomTranslate.CustomTranslateEndpoint.Initialize (XUnity.AutoTranslator.Plugin.Core.Endpoints.IInitializationContext context) [0x00032] in <bcdea0ea85594e13a2def2fb983d2928>:0 
  at XUnity.AutoTranslator.Plugin.Core.TranslationManager.AddEndpoint (XUnity.AutoTranslator.Plugin.Core.Web.HttpSecurity httpSecurity, System.Type type) [0x0003d] in <e3c0bad3c8d74d1c9d523565b4b2ee3d>:0 
[Info   :XUnity.AutoTranslator] Loaded XUnity.AutoTranslator into Unity [2021.3.13f1] game.
[Info   :   BepInEx] Loading [XUnity Resource Redirector 2.1.0]
[Message:   BepInEx] Chainloader startup complete
[Warning:XUnity.AutoTranslator] Input API is not available!
System.InvalidOperationException: You are trying to read Input using the UnityEngine.Input class, but you have switched active Input handling to Input System package in Player Settings.
  at (wrapper managed-to-native) UnityEngine.Input.GetKeyInt(UnityEngine.KeyCode)
  at UnityEngine.Input.GetKey (UnityEngine.KeyCode key) [0x00001] in <8a351fc5ef1946309384da0ba57d1bc0>:0 
  at XUnity.AutoTranslator.Plugin.Core.AutoTranslationPlugin.HandleInput () [0x00000] in <e3c0bad3c8d74d1c9d523565b4b2ee3d>:0 
  at XUnity.AutoTranslator.Plugin.Core.AutoTranslationPlugin.HandleInputSafe () [0x00007] in <e3c0bad3c8d74d1c9d523565b4b2ee3d>:0 
[Info   :XUnity.AutoTranslator] Skipping plugin scan because no plugin-specific translations has been registered.
[Error  :XUnity.AutoTranslator] Error occurred during translation.
System.UriFormatException: Invalid URI: The URI scheme is not valid.
  at System.Uri.CreateThis (System.String uri, System.Boolean dontEscape, System.UriKind uriKind) [0x0007b] in <9fe598e1f1334abeae4ea9fbbe948c3e>:0 
  at System.Uri..ctor (System.String uriString) [0x00014] in <9fe598e1f1334abeae4ea9fbbe948c3e>:0 
  at XUnity.AutoTranslator.Plugin.Core.Web.XUnityWebRequest..ctor (System.String address) [0x00011] in <e3c0bad3c8d74d1c9d523565b4b2ee3d>:0 
  at CustomTranslateBanch.CustomTranslateBanchEndpoint.OnCreateRequest (XUnity.AutoTranslator.Plugin.Core.Endpoints.Http.IHttpRequestCreationContext context) [0x0002e] in <3041adbe99704ff1a623b929e16c5f23>:0 
  at XUnity.AutoTranslator.Plugin.Core.Endpoints.Http.HttpEndpoint+<Translate>d__13.MoveNext () [0x00084] in <e3c0bad3c8d74d1c9d523565b4b2ee3d>:0 
  at XUnity.AutoTranslator.Plugin.Core.Endpoints.TranslationEndpointManager+<Translate>d__78.MoveNext () [0x000fd] in <e3c0bad3c8d74d1c9d523565b4b2ee3d>:0 
[Error  :XUnity.AutoTranslator] Failed: 'Skip'
[Error  :XUnity.AutoTranslator] Error occurred during translation.
System.UriFormatException: Invalid URI: The URI scheme is not valid.
  at System.Uri.CreateThis (System.String uri, System.Boolean dontEscape, System.UriKind uriKind) [0x0007b] in <9fe598e1f1334abeae4ea9fbbe948c3e>:0 
  at System.Uri..ctor (System.String uriString) [0x00014] in <9fe598e1f1334abeae4ea9fbbe948c3e>:0 
  at XUnity.AutoTranslator.Plugin.Core.Web.XUnityWebRequest..ctor (System.String address) [0x00011] in <e3c0bad3c8d74d1c9d523565b4b2ee3d>:0 
  at CustomTranslateBanch.CustomTranslateBanchEndpoint.OnCreateRequest (XUnity.AutoTranslator.Plugin.Core.Endpoints.Http.IHttpRequestCreationContext context) [0x0002e] in <3041adbe99704ff1a623b929e16c5f23>:0 
  at XUnity.AutoTranslator.Plugin.Core.Endpoints.Http.HttpEndpoint+<Translate>d__13.MoveNext () [0x00084] in <e3c0bad3c8d74d1c9d523565b4b2ee3d>:0 
  at XUnity.AutoTranslator.Plugin.Core.Endpoints.TranslationEndpointManager+<Translate>d__78.MoveNext () [0x000fd] in <e3c0bad3c8d74d1c9d523565b4b2ee3d>:0 
[Error  :XUnity.AutoTranslator] Failed: 'Trigger Warning
 
My Lovely Empress contains scenes and imagery some players may find emotionally disturbing.

Player discretion is advised.
[Error  :XUnity.AutoTranslator] Error occurred during translation.
System.UriFormatException: Invalid URI: The URI scheme is not valid.
  at System.Uri.CreateThis (System.String uri, System.Boolean dontEscape, System.UriKind uriKind) [0x0007b] in <9fe598e1f1334abeae4ea9fbbe948c3e>:0 
  at System.Uri..ctor (System.String uriString) [0x00014] in <9fe598e1f1334abeae4ea9fbbe948c3e>:0 
  at XUnity.AutoTranslator.Plugin.Core.Web.XUnityWebRequest..ctor (System.String address) [0x00011] in <e3c0bad3c8d74d1c9d523565b4b2ee3d>:0 
  at CustomTranslateBanch.CustomTranslateBanchEndpoint.OnCreateRequest (XUnity.AutoTranslator.Plugin.Core.Endpoints.Http.IHttpRequestCreationContext context) [0x0002e] in <3041adbe99704ff1a623b929e16c5f23>:0 
  at XUnity.AutoTranslator.Plugin.Core.Endpoints.Http.HttpEndpoint+<Translate>d__13.MoveNext () [0x00084] in <e3c0bad3c8d74d1c9d523565b4b2ee3d>:0 
  at XUnity.AutoTranslator.Plugin.Core.Endpoints.TranslationEndpointManager+<Translate>d__78.MoveNext () [0x000fd] in <e3c0bad3c8d74d1c9d523565b4b2ee3d>:0 
[Error  :XUnity.AutoTranslator] Failed: 'English'
[Error  :XUnity.AutoTranslator] Error occurred during translation.
System.UriFormatException: Invalid URI: The URI scheme is not valid.
  at System.Uri.CreateThis (System.String uri, System.Boolean dontEscape, System.UriKind uriKind) [0x0007b] in <9fe598e1f1334abeae4ea9fbbe948c3e>:0 
  at System.Uri..ctor (System.String uriString) [0x00014] in <9fe598e1f1334abeae4ea9fbbe948c3e>:0 
  at XUnity.AutoTranslator.Plugin.Core.Web.XUnityWebRequest..ctor (System.String address) [0x00011] in <e3c0bad3c8d74d1c9d523565b4b2ee3d>:0 
  at CustomTranslateBanch.CustomTranslateBanchEndpoint.OnCreateRequest (XUnity.AutoTranslator.Plugin.Core.Endpoints.Http.IHttpRequestCreationContext context) [0x0002e] in <3041adbe99704ff1a623b929e16c5f23>:0 
  at XUnity.AutoTranslator.Plugin.Core.Endpoints.Http.HttpEndpoint+<Translate>d__13.MoveNext () [0x00084] in <e3c0bad3c8d74d1c9d523565b4b2ee3d>:0 
  at XUnity.AutoTranslator.Plugin.Core.Endpoints.TranslationEndpointManager+<Translate>d__78.MoveNext () [0x000fd] in <e3c0bad3c8d74d1c9d523565b4b2ee3d>:0 
[Error  :XUnity.AutoTranslator] Failed: 'Language'
[Error  :XUnity.AutoTranslator] Error occurred during translation.
System.UriFormatException: Invalid URI: The URI scheme is not valid.
  at System.Uri.CreateThis (System.String uri, System.Boolean dontEscape, System.UriKind uriKind) [0x0007b] in <9fe598e1f1334abeae4ea9fbbe948c3e>:0 
  at System.Uri..ctor (System.String uriString) [0x00014] in <9fe598e1f1334abeae4ea9fbbe948c3e>:0 
  at XUnity.AutoTranslator.Plugin.Core.Web.XUnityWebRequest..ctor (System.String address) [0x00011] in <e3c0bad3c8d74d1c9d523565b4b2ee3d>:0 
  at CustomTranslateBanch.CustomTranslateBanchEndpoint.OnCreateRequest (XUnity.AutoTranslator.Plugin.Core.Endpoints.Http.IHttpRequestCreationContext context) [0x0002e] in <3041adbe99704ff1a623b929e16c5f23>:0 
  at XUnity.AutoTranslator.Plugin.Core.Endpoints.Http.HttpEndpoint+<Translate>d__13.MoveNext () [0x00084] in <e3c0bad3c8d74d1c9d523565b4b2ee3d>:0 
  at XUnity.AutoTranslator.Plugin.Core.Endpoints.TranslationEndpointManager+<Translate>d__78.MoveNext () [0x000fd] in <e3c0bad3c8d74d1c9d523565b4b2ee3d>:0 
[Error  :XUnity.AutoTranslator] Failed: 'Confirm'
[Error  :XUnity.AutoTranslator] 5 or more consecutive errors occurred. Shutting down translator endpoint.

The Code for the .dll file is:

using System;
using System.Collections.Generic;
using XUnity.AutoTranslator.Plugin.Core.Endpoints;
using XUnity.AutoTranslator.Plugin.Core.Endpoints.Http;
using XUnity.AutoTranslator.Plugin.Core.Web;
using Newtonsoft.Json;

namespace CustomTranslateBanch
{
    internal class CustomTranslateBanchEndpoint : HttpEndpoint
    {
        public CustomTranslateBanchEndpoint()
        {
            _friendlyName = "CustomTranslate";
        }

        public override string Id
        {
            get { return "CustomTranslateBanch"; }
        }

        public override string FriendlyName
        {
            get { return this._friendlyName; }
        }

        public override void Initialize(IInitializationContext context)
        {
            _endpoint = context.GetOrCreateSetting<string>("CustomTranslateBanch", "Url", "");
            if (string.IsNullOrEmpty(_endpoint))
            {
                throw new EndpointInitializationException("The custom endpoint requires a url which has not been provided.");
            }
            // No need to disable certificate checks for LibreTranslate
        }

        public override void OnCreateRequest(IHttpRequestCreationContext context)
        {
            string stringToEscape = string.Join("\n", context.UntranslatedTexts);
            XUnityWebRequest xunityWebRequest = new XUnityWebRequest(string.Format("{0}?api-key=YOUR_API_KEY&lang={1}&format=json&txt={2}", _endpoint, context.SourceLanguage, global::System.Uri.EscapeDataString(stringToEscape)));
            context.Complete(xunityWebRequest);
        }

        public override void OnExtractTranslation(IHttpTranslationExtractionContext context)
        {
            string data = context.Response.Data;
            if (string.IsNullOrEmpty(data))
            {
                context.Complete(context.UntranslatedText);
                return;
            }

            // Parse the JSON response from LibreTranslate
            TranslationResult translationResult;

            try
            {
                translationResult = JsonConvert.DeserializeObject<TranslationResult>(data);

                if (translationResult.TranslatedText != null)
                {
                    // Extract the translated text from the JSON result
                    string translationResultString = translationResult.TranslatedText;
                    context.Complete(new[] { translationResultString });
                }
                else
                {
                    // Handle cases where LibreTranslate returns an empty or invalid response
                    context.Complete(new[] { "Error: Invalid response from LibreTranslate" });
                }
            }
            catch (JsonReaderException ex)
            {
                // Handle JSON parsing errors
                Console.WriteLine("JSON parsing error: " + ex.Message);
                context.Complete(new[] { "Error: Failed to parse JSON response from LibreTranslate" });
            }
        }

        static CustomTranslateBanchEndpoint()
        {
        }

        private string _endpoint;

        private string _friendlyName;
    }

    public class TranslationResult
    {
        public string TranslatedText { get; set; }
    }
}

The Config File is:

[Service]
Endpoint=CustomTranslateBanch
FallbackEndpoint=CustomTranslate

[General]
Language=de
FromLanguage=en

[Files]
Directory=Translation\{Lang}\Text
OutputFile=Translation\{Lang}\Text\_AutoGeneratedTranslations.txt
SubstitutionFile=Translation\{Lang}\Text\_Substitutions.txt
PreprocessorsFile=Translation\{Lang}\Text\_Preprocessors.txt
PostprocessorsFile=Translation\{Lang}\Text\_Postprocessors.txt

[TextFrameworks]
EnableIMGUI=False
EnableUGUI=True
EnableNGUI=True
EnableTextMeshPro=True
EnableTextMesh=False
EnableFairyGUI=True

[Behaviour]
MaxCharactersPerTranslation=200
IgnoreWhitespaceInDialogue=True
MinDialogueChars=20
ForceSplitTextAfterCharacters=0
CopyToClipboard=False
MaxClipboardCopyCharacters=2500
ClipboardDebounceTime=1.25
EnableUIResizing=True
EnableBatching=True
UseStaticTranslations=True
OverrideFont=
OverrideFontSize=
OverrideFontTextMeshPro=
FallbackFontTextMeshPro=
ResizeUILineSpacingScale=
ForceUIResizing=False
IgnoreTextStartingWith=\u180e;
TextGetterCompatibilityMode=False
GameLogTextPaths=
RomajiPostProcessing=ReplaceMacronWithCircumflex;RemoveApostrophes;ReplaceHtmlEntities
TranslationPostProcessing=ReplaceMacronWithCircumflex;ReplaceHtmlEntities
RegexPostProcessing=
CacheRegexPatternResults=False
PersistRichTextMode=Final
CacheRegexLookups=False
CacheWhitespaceDifferences=False
GenerateStaticSubstitutionTranslations=False
GeneratePartialTranslations=False
EnableTranslationScoping=True
EnableSilentMode=True
BlacklistedIMGUIPlugins=
EnableTextPathLogging=False
OutputUntranslatableText=False
IgnoreVirtualTextSetterCallingRules=False
MaxTextParserRecursion=1
HtmlEntityPreprocessing=True
HandleRichText=True
EnableTranslationHelper=False
ForceMonoModHooks=False
InitializeHarmonyDetourBridge=False
RedirectedResourceDetectionStrategy=AppendMongolianVowelSeparatorAndRemoveAll
OutputTooLongText=False
TemplateAllNumberAway=False
ReloadTranslationsOnFileChange=False
DisableTextMeshProScrollInEffects=False
CacheParsedTranslations=False

[Texture]
TextureDirectory=Translation\{Lang}\Texture
EnableTextureTranslation=False
EnableTextureDumping=False
EnableTextureToggling=False
EnableTextureScanOnSceneLoad=False
EnableSpriteRendererHooking=False
LoadUnmodifiedTextures=False
DetectDuplicateTextureNames=False
DuplicateTextureNames=
EnableLegacyTextureLoading=False
TextureHashGenerationStrategy=FromImageName
CacheTexturesInMemory=True
EnableSpriteHooking=False

[ResourceRedirector]
PreferredStoragePath=Translation\{Lang}\RedirectedResources
EnableTextAssetRedirector=False
LogAllLoadedResources=False
EnableDumping=False
CacheMetadataForAllFiles=True

[Http]
UserAgent=
DisableCertificateValidation=True

[TranslationAggregator]
Width=400
Height=100
EnabledTranslators=

[Debug]
EnableConsole=False

[Migrations]
Enable=True
Tag=5.4.0

[Baidu]
BaiduAppId=
BaiduAppSecret=
DelaySeconds=1

[BingLegitimate]
OcpApimSubscriptionKey=

[Custom]
Url=

[DeepL]
ExecutableLocation=
MinDelaySeconds=2
MaxDelaySeconds=6

[DeepLLegitimate]
ExecutableLocation=
ApiKey=
Free=False

[ezTrans]
InstallationPath=

[Google]
ServiceUrl=

[GoogleV2]
ServiceUrl=
RPCID=MkEWBc
VERSION=boq_translate-webserver_20210323.10_p0
UseSimplest=False

[GoogleLegitimate]
GoogleAPIKey=

[LecPowerTranslator15]
InstallationPath=

[LingoCloud]
LingoCloudToken=

[Watson]
Url=
Key=

[Yandex]
YandexAPIKey=

[CustomTranslate]
Url="http://192.168.1.250:5000/translate"

[CustomTranslateBanch]
Url="http://192.168.1.250:5000/translate"

**Comment by Neresco** [comment]
Here is the .dll file.

[Libretranslatenew.zip](https://github.com/user-attachments/files/16958874/Libretranslatenew.zip)
Here ist the conversation with my own Chatbot.
https://lunartube.spdns.eu/s/e07dfd97-d229-401b-bb83-c54191113d02
If somone want to vaerify

https://lunartube.spdns.eu/
testuser@testgpt.com
Testuser1234#!

**Comment by ManlyMarco** [comment]
Well, as the exception's stack trace shows you are making a malformed URI string in your OnCreateRequest. I have no way of knowing how it looks like at runtime, you have to either attach a debugger and break on the exception, or write things to log and check the sources until you can find the issue.

**Comment by Neresco** [comment]
Ok it functions now:
I have set Net Framework 4.6.1 as Target

Here Is the code:
using System;
using System.Collections.Generic;
using System.Net;
using XUnity.AutoTranslator.Plugin.Core.Endpoints;
using XUnity.AutoTranslator.Plugin.Core.Endpoints.Http;
using XUnity.AutoTranslator.Plugin.Core.Web;
using Newtonsoft.Json;

namespace CustomTranslate
{
    internal class CustomTranslateEndpoint : HttpEndpoint
    {
        public CustomTranslateEndpoint()
        {
            _friendlyName = "CustomTranslate";
        }

        public override string Id
        {
            get { return "CustomTranslate"; }
        }

        public override string FriendlyName
        {
            get { return this._friendlyName; }
        }

        public override void Initialize(IInitializationContext context)
        {
            // URL aus der Konfigurationsdatei lesen
            _endpoint = context.GetOrCreateSetting<string>("CustomTranslate", "Url", "");
            if (string.IsNullOrEmpty(_endpoint))
            {
                throw new EndpointInitializationException("The custom endpoint requires a url which has not been provided.");
            }
            // No need to disable certificate checks for LibreTranslate
        }

        public override void OnCreateRequest(IHttpRequestCreationContext context)
        {
            string stringToEscape = string.Join("\n", context.UntranslatedTexts);

            var postData = new
            {
                q = stringToEscape,
                source = context.SourceLanguage,
                target = context.DestinationLanguage,
                format = "text", // oder "html" je nach Bedarf
                api_key = "YOUR_API_KEY" // Falls erforderlich
            };

            string jsonPostData = JsonConvert.SerializeObject(postData);

            XUnityWebRequest xunityWebRequest = new XUnityWebRequest("POST", _endpoint, jsonPostData);
            xunityWebRequest.Headers.Add("Content-Type", "application/json");

            context.Complete(xunityWebRequest);
        }

        public override void OnExtractTranslation(IHttpTranslationExtractionContext context)
        {
            string data = context.Response.Data;
            if (string.IsNullOrEmpty(data))
            {
                context.Complete(context.UntranslatedText);
                return;
            }

            // Parse the JSON response from LibreTranslate
            TranslationResult translationResult;

            try
            {
                translationResult = JsonConvert.DeserializeObject<TranslationResult>(data);

                if (translationResult.TranslatedText != null)
                {
                    // Extract the translated text from the JSON result
                    string translationResultString = translationResult.TranslatedText;
                    context.Complete(new[] { translationResultString });
                }
                else
                {
                    // Handle cases where LibreTranslate returns an empty or invalid response
                    context.Complete(new[] { "Error: Invalid response from LibreTranslate" });
                }
            }
            catch (JsonReaderException ex)
            {
                // Handle JSON parsing errors
                Console.WriteLine("JSON parsing error: " + ex.Message);
                context.Complete(new[] { "Error: Failed to parse JSON response from LibreTranslate" });
            }
        }

        static CustomTranslateEndpoint()
        {
        }

        private string _endpoint;

        private string _friendlyName;
    }

    public class TranslationResult
    {
        public string TranslatedText { get; set; }
    }
}
Here is the DLL File:
[LibreTranslate.zip](https://github.com/user-attachments/files/16988823/LibreTranslate.zip)
Here is the Config to use in AutoTranslatorConfig.ini:

[Service]
Endpoint=CustomTranslate
FallbackEndpoint=

[CustomTranslate]
Url=https://your own libretranslate.webpage/translate
api_key=your api key if set (I have set one
<img width="947" alt="libre1" src="https://github.com/user-attachments/assets/0fda45e3-b1f8-43d3-a05e-22a95bb57c3c">

Pls use this and Implement it in Xunityautotranslator, i think it will help many people.

Many respect for programmers i am not one, just normal it Administrator.
At the End i even dreamed of this stuff haha.
