### ISSUE TITLE
can i ignore translate some element without IMGUI?

### ISSUE THREAD

**Issue by modabada** [bbepis/XUnity.AutoTranslator#567]
In the game I play. 
There's an element that's always used as a history, 
and it's always present in the scene, so whenever a history is added, it sends a translation request
Then, it will shut down for the following reasons and the LogOutput.log file shows the following
https://github.com/bbepis/XUnity.AutoTranslator/blob/d31d141bd90ecb3f6f481b2d0f4750f19ab04d8c/README.md?plain=1#L261

> _"SPAM DETECTED: Text that is 'scrolling in' is being translated. Disable that feature. Shutting down plug-in."_ 

I don't need to translate that element, so I want to turn off the translation function for that element only. Is it possible?

**Comment by ManlyMarco** [comment]
https://github.com/bbepis/XUnity.AutoTranslator?tab=readme-ov-file#implementing-a-component-that-the-auto-translator-should-not-interfere-with

**Comment by modabada** [comment]
From what I understood, after checking the heirarchy through 'Ctrl + Alt + Num 6', I understood that if you include 'XUAGNORE' in the GameObject name you want to exclude, you can ignore it
But, my game dosen`t support mod. so i can`t rename GameObject`s name

**Comment by modabada** [comment]
@ManlyMarco
From what I understood, after checking the heirarchy through 'Ctrl + Alt + Num 6', I understood that if you include 'XUAGNORE' in the GameObject name you want to exclude, you can ignore it
But, my game dosent support mod. so i cant rename GameObject\`s name

**Comment by ManlyMarco** [comment]
@modabada Read closer, the section I linked is for IMGUI. It requires you to patch the offending OnGUI method.

**Comment by modabada** [comment]
@ManlyMarco 
Honestly, at first, I didn't understand why they recommended using IMGUI. 
But after thinking about it in detail, I finally focused on being able to find `___XUnityAutoTranslator` elements in IMGUI's example because I already know the hierarchy of elements I want to exclude, 
and it was solved by adding `XUAIGNORE` to the name of the object I found.
Thank you.

here is result of my dumbass try
``` C#
public void OnGUI()
{
    if (!_lookedForXua)
    {
        _lookedForXua = true;
        _xua = GameObject.Find("Scroll View/Viewport/Content/Text (TMP)");
        _xua.name += "XUAIGNORE";
    }

    try
    {
        _xua?.SendMessage("DisableAutoTranslator");
    }
    finally
    {
        _xua?.SendMessage("EnableAutoTranslator");
    }
}
```
