### ISSUE TITLE
All il2cpp games cannot be translated in version 5.4.0.

### ISSUE THREAD

**Issue by Leowolf93** [bbepis/XUnity.AutoTranslator#582]
Dear Developer,

I have been using versions 5.3.0 and 5.3.1, and all games ran smoothly. The methods I have used include ReiPatcher, BepInEx, and the Edge version of BepInEx in conjunction with il2cpp for translation.

However, after updating to the latest 5.4.0 version, Mono games using ReiPatcher and BepInEx work fine, but il2cpp games, whether 32-bit or 64-bit, can no longer be translated.

Here are the steps I followed:

1.Downloaded XUnity.AutoTranslator-BepInEx-IL2CPP-5.4.0.zip.

2.Downloaded the 704 Build of BepInEx-Unity.IL2CPP-win-x86-6.0.0-be.704+6b38cee.zip and BepInEx-Unity.IL2CPP-win-x64-6.0.0-be.704+6b38cee.zip.

3.Extracted both BepInEx-Unity.IL2CPP-win-x86-6.0.0-be.704+6b38cee.zip and BepInEx-Unity.IL2CPP-win-x64-6.0.0-be.704+6b38cee.zip along with XUnity.AutoTranslator-BepInEx-IL2CPP-5.4.0.zip.

4.Copied the BepInEx folder from XUnity.AutoTranslator-BepInEx-IL2CPP-5.4.0.zip to the extracted BepInEx-Unity.IL2CPP-win-x86-6.0.0-be.704+6b38cee and BepInEx-Unity.IL2CPP-win-x64-6.0.0-be.704+6b38cee folders.

Based on whether the game is 32-bit or 64-bit, I copied the corresponding final files to the il2cpp game directory.
I am certain I followed the exact same process as I did with versions 5.3.0/5.3.1, and there were no errors, but translation is not working. The ErrorLog.log file is empty, and here is my LogOutput.log.

> [Message: Preloader] BepInEx 6.0.0-be.704 - DECOY群青の魔女
[Message: Preloader] Built from commit 6b38cee1277f4e3da5f2f685aee8b503a14d4054
[Info   :   BepInEx] System platform: Windows 10 64-bit
[Info   :   BepInEx] Process bitness: 64-bit (x64)
[Info   :   BepInEx] Running under Unity 2022.3.16f1
[Info   :   BepInEx] Runtime version: 6.0.7
[Info   :   BepInEx] Runtime information: .NET 6.0.7
[Message:InteropManager] Downloading unity base libraries
[Message:InteropManager] Extracting downloaded unity base libraries
[Message:InteropManager] Running Cpp2IL to generate dummy assemblies
[Info   :    Cpp2IL] [Library] Initializing Metadata...
[Info   :    Cpp2IL] [Library] Using actual IL2CPP Metadata version 29.1
[Info   :    Cpp2IL] [Library] Initialized Metadata in 89ms
[Info   :    Cpp2IL] [Library] Using binary type Portable Executable (from LibCpp2IL)
[Info   :    Cpp2IL] [Library] Searching Binary for Required Data...
[Info   :    Cpp2IL] [Library] Got Binary codereg: 0x1831DB7F0, metareg: 0x18392AC10 in 119ms.
[Info   :    Cpp2IL] [Library] Initializing Binary...
[Info   :    Cpp2IL] [Library] Initialized Binary in 119ms
[Info   :    Cpp2IL] [Library] Mapping pointers to Il2CppMethodDefinitions...
[Info   :    Cpp2IL] [Library] Processed 127696 OK (61ms)
[Info   :    Cpp2IL] [Program] Creating application model...
[Info   :    Cpp2IL] [Program] Application model created in 1489.8301ms
[Info   :InteropManager] Cpp2IL finished in 00:00:04.7654901
[Info   :InteropManager] Generating interop assemblies
[Info   :Il2CppInteropGen] Reading assemblies...
[Info   :Il2CppInteropGen] Done in 00:00:00.0316894
[Info   :Il2CppInteropGen] Reading unity assemblies...
[Info   :Il2CppInteropGen] Done in 00:00:00.0088181
[Info   :Il2CppInteropGen] Creating rewrite assemblies...
[Info   :Il2CppInteropGen] Done in 00:00:00.0049990
[Info   :Il2CppInteropGen] Computing renames...
[Info   :Il2CppInteropGen] Done in 00:00:00.0422143
[Info   :Il2CppInteropGen] Creating typedefs...
[Info   :Il2CppInteropGen] Done in 00:00:00.0267891
[Info   :Il2CppInteropGen] Computing struct blittability...
[Info   :Il2CppInteropGen] Done in 00:00:00.0375652
[Info   :Il2CppInteropGen] Filling typedefs...
[Info   :Il2CppInteropGen] Done in 00:00:00.0123707
[Info   :Il2CppInteropGen] Filling generic constraints...
[Info   :Il2CppInteropGen] Done in 00:00:00.0037438
[Info   :Il2CppInteropGen] Creating members...
[Info   :Il2CppInteropGen] Done in 00:00:00.7834551
[Info   :Il2CppInteropGen] Scanning method cross-references...
[Info   :Il2CppInteropGen] Done in 00:00:00.3801952
[Info   :Il2CppInteropGen] Finalizing method declarations...
[Info   :Il2CppInteropGen] Done in 00:00:01.2211849
[Info   :Il2CppInteropGen] 45 total potentially dead methods
[Info   :Il2CppInteropGen] Filling method parameters...
[Info   :Il2CppInteropGen] Done in 00:00:00.2558016
[Info   :Il2CppInteropGen] Creating static constructors...
[Info   :Il2CppInteropGen] Done in 00:00:00.3658528
[Info   :Il2CppInteropGen] Creating value type fields...
[Info   :Il2CppInteropGen] Done in 00:00:00.0498143
[Info   :Il2CppInteropGen] Creating enums...
[Info   :Il2CppInteropGen] Done in 00:00:00.0107335
[Info   :Il2CppInteropGen] Creating IntPtr constructors...
[Info   :Il2CppInteropGen] Done in 00:00:00.1125078
[Info   :Il2CppInteropGen] Creating non-blittable struct constructors...
[Info   :Il2CppInteropGen] Done in 00:00:00.0204816
[Info   :Il2CppInteropGen] Creating generic method static constructors...
[Info   :Il2CppInteropGen] Done in 00:00:00.0719150
[Info   :Il2CppInteropGen] Creating field accessors...
[Info   :Il2CppInteropGen] Done in 00:00:00.5471430
[Info   :Il2CppInteropGen] Filling methods...
[Info   :Il2CppInteropGen] Done in 00:00:02.0530852
[Info   :Il2CppInteropGen] Generating implicit conversions...
[Info   :Il2CppInteropGen] Done in 00:00:00.0100509
[Info   :Il2CppInteropGen] Creating properties...
[Info   :Il2CppInteropGen] Done in 00:00:00.0530022
[Info   :Il2CppInteropGen] Unstripping types...
[Info   :Il2CppInteropGen] Done in 00:00:00.0129863
[Info   :Il2CppInteropGen] Unstripping fields...
[Info   :Il2CppInteropGen] Restored 414 fields
[Info   :Il2CppInteropGen] Failed to restore 0 fields
[Info   :Il2CppInteropGen] Done in 00:00:00.0052519
[Info   :Il2CppInteropGen] Unstripping methods...
[Info   :Il2CppInteropGen] Restored 13402 methods
[Info   :Il2CppInteropGen] Failed to restore 905 methods
[Info   :Il2CppInteropGen] Done in 00:00:00.2211677
[Info   :Il2CppInteropGen] Unstripping method bodies...
[Info   :Il2CppInteropGen] IL unstrip statistics: 7000 successful, 1756 failed
[Info   :Il2CppInteropGen] Done in 00:00:00.2078584
[Info   :Il2CppInteropGen] Writing xref cache...
[Info   :Il2CppInteropGen] Done in 00:00:00.8042762
[Info   :Il2CppInteropGen] Writing assemblies...
[Info   :Il2CppInteropGen] Done in 00:00:00.4223556
[Info   :Il2CppInteropGen] Writing method pointer map...
[Info   :Il2CppInteropGen] Done in 00:00:00.0324553
[Info   :Il2CppInteropGen] Done!
[Info   : Preloader] 0 patcher plugins loaded
[Info   : Preloader] 0 assemblies discovered
[Message:AssemblyPatcher] Executing 0 patch(es)
[Message:   BepInEx] Chainloader initialized
[Warning:Il2CppInterop] Class::Init signatures have been exhausted, using a substitute!
[Info   :Il2CppInterop] Registered mono type Il2CppInterop.Runtime.DelegateSupport+Il2CppToMonoDelegateReference in il2cpp domain
[Info   :   BepInEx] 2 plugins to load
[Info   :   BepInEx] Loading [XUnity Auto Translator 5.4.0]
[Info   :Il2CppInterop] Registered mono type XUnity.AutoTranslator.Plugin.Core.PluginLoader+AutoTranslatorProxyBehaviour in il2cpp domain
[Info   :   BepInEx] Loading [XUnity Resource Redirector 2.1.0]
[Message:   BepInEx] Chainloader startup complete
[Info   :XUnity.AutoTranslator] Force loading ALL proxy assemblies.
[Warning:XUnity.AutoTranslator] An error occurred while resolving type: UnityEngine.TextMesh
System.ArgumentException: TextMesh does not have a corresponding IL2CPP class pointer
   at Il2CppInterop.Runtime.Il2CppType.TypeFromPointerInternal(IntPtr classPointer, String typeName, Boolean throwOnFailure) in /home/runner/work/Il2CppInterop/Il2CppInterop/Il2CppInterop.Runtime/Il2CppType.cs:line 19
   at XUnity.Common.Constants.UnityTypes.FindType(String name)
[Error  :Il2CppInterop] Nested type ToolbarButtonSize on GUI not found!
[Warning:XUnity.AutoTranslator] An error occurred while resolving type: UnityEngine.GUI+ToolbarButtonSize
System.ArgumentException: ToolbarButtonSize does not have a corresponding IL2CPP class pointer
   at Il2CppInterop.Runtime.Il2CppType.TypeFromPointerInternal(IntPtr classPointer, String typeName, Boolean throwOnFailure) in /home/runner/work/Il2CppInterop/Il2CppInterop/Il2CppInterop.Runtime/Il2CppType.cs:line 19
   at XUnity.Common.Constants.UnityTypes.FindType(String name)
[Warning:XUnity.AutoTranslator] An error occurred while resolving type: UnityEngine.ImageConversion
System.ArgumentException: ImageConversion does not have a corresponding IL2CPP class pointer
   at Il2CppInterop.Runtime.Il2CppType.TypeFromPointerInternal(IntPtr classPointer, String typeName, Boolean throwOnFailure) in /home/runner/work/Il2CppInterop/Il2CppInterop/Il2CppInterop.Runtime/Il2CppType.cs:line 19
   at XUnity.Common.Constants.UnityTypes.FindType(String name)
[Info   :XUnity.AutoTranslator] Version of TextMesh Pro: 1.4.0.
[Warning:  HarmonyX] AccessTools.Method: Could not find method for type TMPro.TMP_Text and name SetCharArray and parameters (Il2CppInterop.Runtime.InteropTypes.Arrays.Il2CppStructArray<int>, int, int)
[Warning:XUnity.AutoTranslator] Could not hook 'TMP_Text_SetCharArray_Hook3'. Likely due differences between different versions of the engine or text framework.
[Error  :XUnity.AutoTranslator] Could not find the configured endpoint 'GoogleTranslateV2'.
[Info   :XUnity.AutoTranslator] Loaded XUnity.AutoTranslator into Unity [2022.3.16f1] game.
[Info   :Il2CppInterop] Registered mono type XUnity.AutoTranslator.Plugin.Core.Il2CppManagedEnumerator in il2cpp domain
[Warning:XUnity.AutoTranslator] Input API is not available!
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> Il2CppInterop.Runtime.Il2CppException: System.InvalidOperationException: You are trying to read Input using the UnityEngine.Input class, but you have switched active Input handling to Input System package in Player Settings.
--- BEGIN IL2CPP STACK TRACE ---
System.InvalidOperationException: You are trying to read Input using the UnityEngine.Input class, but you have switched active Input handling to Input System package in Player Settings.
--- END IL2CPP STACK TRACE ---
   at Il2CppInterop.Runtime.Il2CppException.RaiseExceptionIfNecessary(IntPtr returnedException) in /home/runner/work/Il2CppInterop/Il2CppInterop/Il2CppInterop.Runtime/Il2CppException.cs:line 36
   at UnityEngine.Input.GetKey(KeyCode key)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at XUnity.AutoTranslator.Plugin.Core.Input.GetKey(KeyCode key)
   at XUnity.AutoTranslator.Plugin.Core.AutoTranslationPlugin.HandleInput()
   at XUnity.AutoTranslator.Plugin.Core.AutoTranslationPlugin.HandleInputSafe()
[Info   :XUnity.AutoTranslator] Skipping plugin scan because no plugin-specific translations has been registered.

There is one line that I find very confusing: why does it show the message "Could not find the configured endpoint 'GoogleTranslateV2' "? Even when I use other endpoints, it still displays the same error.

Could you please assist with this issue?

**Comment by Oleksandrigo** [comment]
same problem, even in the menu (alt+0 ) there are no endpoints.

**Comment by ManlyMarco** [comment]
Read the warning in the release. You have to update from the previous version to have all translators.

**Comment by ManlyMarco** [comment]
Either version works the same.
