### ISSUE TITLE
How to deal with PT-BR code on configuration?

### ISSUE THREAD

**Issue by FabioZumbi12** [bbepis/XUnity.AutoTranslator#583]
I want to translate the game to PT-BR and not only to "pt" (witch works)

The config is like this:

```[General]
Language=pt-BR
FromLanguage=en
```

I got this:
```
[Error  :XUnity.AutoTranslator] Error occurred during the initialization of the fallback translate endpoint.
XUnity.AutoTranslator.Plugin.Core.Endpoints.EndpointInitializationException: The destination language 'pt-BR' is not supported.
```

Also tryied `ptbr`m `pt_br` and only `br`.

Thanks

**Comment by ManlyMarco** [comment]
Check if the endpoint you're using supports it, e.g. https://github.com/bbepis/XUnity.AutoTranslator/blob/33bc50199b2dcefc74ec2aa53cee4d03ec5ec37b/src/Translators/DeepLTranslate/DeepLTranslate.cs#L23

**Comment by overallbit** [comment]
> Check if the endpoint you're using supports it, e.g.
> 
> https://github.com/bbepis/XUnity.AutoTranslator/blob/33bc50199b2dcefc74ec2aa53cee4d03ec5ec37b/src/Translators/DeepLTranslate/DeepLTranslate.cs#L23

This is the problem Im having on the issue post I made. I am using DeepL and pt-br just like but in game nothing is trasnlated :(

**Comment by overallbit** [comment]
> I want to translate the game to PT-BR and not only to "pt" (witch works)
> 
> The config is like this:
> 
> ```
> Language=pt-BR
> FromLanguage=en
> ```
> 
> I got this:
> 
> ```
> [Error  :XUnity.AutoTranslator] Error occurred during the initialization of the fallback translate endpoint.
> XUnity.AutoTranslator.Plugin.Core.Endpoints.EndpointInitializationException: The destination language 'pt-BR' is not supported.
> ```
> 
> Also tryied `ptbr`m `pt_br` and only `br`.
> 
> Thanks

Can you use GoogleTranslate or GoogleTranslateV2?

**Comment by FabioZumbi12** [comment]
> > I want to translate the game to PT-BR and not only to "pt" (witch works)
> > The config is like this:
> > ```
> > Language=pt-BR
> > FromLanguage=en
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I got this:
> > ```
> > [Error  :XUnity.AutoTranslator] Error occurred during the initialization of the fallback translate endpoint.
> > XUnity.AutoTranslator.Plugin.Core.Endpoints.EndpointInitializationException: The destination language 'pt-BR' is not supported.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Also tryied `ptbr`m `pt_br` and only `br`.
> > Thanks
> 
> Can you use GoogleTranslate or GoogleTranslateV2?

You is right. Google only support pt. I got in your file and looking on google cloud docs too, thank you for now 🙏🏻
