### ISSUE TITLE
When will the font problem be resolved?

### ISSUE THREAD

**Issue by makkoar** [bbepis/XUnity.AutoTranslator#602]
The issue of fonts has been a hot topic for a long time.
In the configuration it is strictly prescribed that a certain font must be used in the game. (I used the one that is in the project folder), but when I go to any game it turns out that this font does not apply, even if it is 100% in the root folder of the game.

If you go in using the console, it says it failed to apply/find the font, I don't remember exactly.

On top of that I'm having huge problems creating my own font. No matter how many times I've looked, there are no clear instructions on how to create a font that fits XUnity. Somehow I was able to create an SDF font for TM-Pro, but again it was not readable by XUnity.

When will it be possible to add .ttf fonts without the hassle of downloading Unity?

There's also a problem with fixed-size fonts, which is used in the Japanese localization. When translating to Russian, there is a huge distance between letters because the character size is fixed. When it will be possible to control this parameter, because such translations look just terrible or unreadable.

I am very interested in this topic, as I use this program to manually translate games into Russian and because of these problems not always the game is suitable for translation, as the translation is simply impossible because of the above problems.

**Comment by ManlyMarco** [comment]
It will be resolved whenever someone makes a PR to fix it. Currently there is no one regularly updating this plugin, I only maintain it.

**Comment by makkoar** [comment]
Sad, but ok
