### ISSUE TITLE
Doesn't work with "Torment Tides of Numenera"

### ISSUE THREAD

**Issue by ziomik** [bbepis/XUnity.AutoTranslator#61]
The patch starts and with ALT/0 I can see that it is working but does not translate anything. I don't even see the DOS window that I can see with other games (I can actually see the work of the program).

I think it's the same problem: https://github.com/bbepis/XUnity.AutoTranslator/issues/30

EDIT: I found the solution: You have to start the executable either in the root or in the WIN folder.
I believe that the program reads the config file in the root but "picks up" the files in the WIN folder

**Comment by gravydevsupreme** [comment]
This has been a problem in other games that uses a launcher as well. For some reason I never got around to fixing it, even though I think it should be a simple problem.

Could you tell me if this fixes the issue?

[XUnity.AutoTranslator-ReiPatcher-4.5.1-custom.zip](https://github.com/bbepis/XUnity.AutoTranslator/files/3758691/XUnity.AutoTranslator-ReiPatcher-4.5.1-custom.zip)

**Comment by ziomik** [comment]
Hello! Yes this installation works without the need to duplicate the folders in various positions !! Great!

**Comment by gravydevsupreme** [comment]
Good to hear it.
