### ISSUE TITLE
Noone sees eachothers translation boxes

### ISSUE THREAD

**Issue by AstridJASA** [bbepis/XUnity.AutoTranslator#611]
I put the mod into the server, and it works for me and everything. but i cant see anyone elses translations, the same thing is happening with everyone else.

I  was wondering if there is a actual guide on how to input the mod into a server and the correct settings or coding.

**Comment by ManlyMarco** [comment]
This is entirely client side, it can't work across network. You will have to make your own plugin to synchronize how text appears across different users.
