### ISSUE TITLE
Why I can only use 3 of the translator?

### ISSUE THREAD

**Issue by wjk199511140034** [bbepis/XUnity.AutoTranslator#63]
![未标题-1](https://user-images.githubusercontent.com/12637627/67616027-54efba80-f806-11e9-89c5-09f89609672a.jpg)
other translator was grey that cant be select

**Comment by gravydevsupreme** [comment]
https://github.com/bbepis/XUnity.AutoTranslator#translators

Only two translator implementations doesn't require some sort of user configuration, as described above.

**Comment by wjk199511140034** [comment]
> https://github.com/bbepis/XUnity.AutoTranslator#translators
> 
> Only two translator implementations doesn't require some sort of user configuration, as described above.

Thank very much, but I have a little request, I‘m begging you recompile a new GoogleTranslate.dll, and change translate.google.com to translate.google.cn, google is the most accurate and simple translatior，but, you know, because of some silly policy google.com is blocked by GOV.

**Comment by wjk199511140034** [comment]
solved, thank you!
