### ISSUE TITLE
Unity Mono Game Text Not Translating

### ISSUE THREAD

**Issue by moruma455** [bbepis/XUnity.AutoTranslator#642]
Only the dialogue in cutscenes or skill text in battle translates... Many things like menu items and headers won't translate. I thought maybe it was a texture so I enabled texture dumping and it's not generating any images with text on them... Please help.

Translates:
![image](https://github.com/user-attachments/assets/703cae2c-2261-41dd-b2a1-a2c07d32d54d)

Won't translate:
![image](https://github.com/user-attachments/assets/d37c8829-fbab-4076-912c-b36a1f49872c)
![image](https://github.com/user-attachments/assets/20d50b79-2985-4006-b50c-e6d7cd61170a)

Here is my log.
[LogOutput.log](https://github.com/user-attachments/files/18161921/LogOutput.log)

**Comment by ManlyMarco** [comment]
Images can't be translated automatically. Turn on texture translation/dumping and translate them manually.

**Comment by moruma455** [comment]
> Images can't be translated automatically. Turn on texture translation/dumping and translate them manually.

I just said that was turned on and that the images weren't generating. Didn't you read my request?

**Comment by ManlyMarco** [comment]
I did and it's still the same answer, those are images and you need to change the related dumping options until they can be dumped. If the game uses IL2CPP you may be out of luck and need to write a helper plugin to handle textures.

**Comment by moruma455** [comment]
I've tried all the options.. The game currently only generates background textures from the loading screens and the main menu. 

The other textures that have words on them are missing. Can you please confirm for me that this is actually something that a developer can't fix with a bit of tweaking?

I'm not a coder so I want to be sure, thanks.

**Comment by ManlyMarco** [comment]
It sounds like it's something custom that the game does so anyone trying to fix this would need to have the game and dig into how it works.

**Comment by moruma455** [comment]
I understand that exceptions need to be examined by having the game to investigate. It's a free to play game. 

But what I want to know is if this is something that a developer could potentially fix without a helper plugin. Since the plugin is already reading textures, do they just need to tell plugin where to look in order to capture it?
