### ISSUE TITLE
Substitutions stop work for names when online translator returned only name

### ISSUE THREAD

**Issue by TokcDK** [bbepis/XUnity.AutoTranslator#67]
Found situation when substitutions stop working when some line added in generated or custom txt.
After some time found this line.

Here this line when names of all chars which was added in substitutions stoped translating:
`{{A}}ー、入るわよー={{A}}`
The line was added from online G translator.
Checked all names and found source:
`ソフィー、入るわよ`
Gtranslator will return only `Sophie` .
If in substitutions txt was added several names then they all will stop translating if alone (single word).
```
ターニャ=Tanya
ルイス=Lewis
ソフィ=Sophie
```
After `{{A}}ー、入るわよー={{A}}` will be added in generated or custom txt all names above when alone will stop translating, `ターニャ` will stop be translated to `Tanya`, `ルイス` will stop translate to `Lewis` and all other names which will be there.

Checked several times after found the line all single names in popup or in dialog stoped translating and all is become normal if remove the line or replace it by correct where in translation not only `{{A}}` .

**Comment by gravydevsupreme** [comment]
Could you please provide a concrete example with expected behaviour / actual behaviour. I am having trouble following exactly what is going wrong.

Alternatively you can tell me which game it is happening in and provide a save file.

**Comment by TokcDK** [comment]
Checked in two games and in both apppeared same bug.
For reproduce just use any game where in`Translation\en\Text\_Substitutions.txt` added names of main characters. Then create in same folder forlder for example `bug.txt` file and add there `{{A}}ー、入るわよー={{A}}` line or instead add it in `_AutoGeneratedTranslations.txt`.
After it in game check dialogs of characters which names is in `_Substitutions.txt`. 

Substitution is working for lines like `{{A}}、諦めるのはまだ早いわよ={{A}}, it's still too early to give up` but they not working when in source string only name like `ターニャ=Tanya` and dialogs often displaying like this:
`ターニャ` - first name alone

`ルイス、諦めるのはまだ早いわよ` - and after dialog

Dialog will be translated correct but name will not be translated and be in japanese. 
It can be fixed if remove bugged line `{{A}}ー、入るわよー={{A}}` or add any text to substitution mark {{A}} or remove substitutions from txt. Bug happens when `{{A}}` alone in translation but in source `{{A}}ー、入るわよー`  not alone. Bug will no apperar with `{{A}}ー、入るわよー={{A}}, I'll enter` or with `{{A}}={{A}}` .

**Comment by gravydevsupreme** [comment]
Thanks. Hopefully I will have a chance to take a look at this sometime next week.

**Comment by TokcDK** [comment]
By the way, found another situation when text can be translated because using variable. Noticed it in game and found this line in generated txt:
`“<param%3DrewardItemName>”を手に入れた=I got “<param%3DrewardItemName>"`
On place of `<param%3DrewardItemName>` displaying item name and when displaying it replacing and apparently it replacing after XUA parsing it.

**Comment by gravydevsupreme** [comment]
Can I assume this second issue is the same as the one described here #56 ?

**Comment by TokcDK** [comment]
`<param%3DrewardItemName>` is ingame string variable on which place is displaing random quest reward item name.  And it is displaying in japanese when other part translated and in result it displaing like `I got "メガソード"` and it means it is replacing after XUA parsed it.
Maibe it looks simular like 56 if `<param%3DrewardItemName>` is substitution and `“<param%3DrewardItemName>”を手に入れた` is templated text and `I got “<param%3DrewardItemName>"` is untemplated text in output.

**Comment by gravydevsupreme** [comment]
On issue 1: Please confirm if this fixes the issue.

[XUnity.AutoTranslator-ReiPatcher-4.7.1.zip](https://github.com/bbepis/XUnity.AutoTranslator/files/3936169/XUnity.AutoTranslator-ReiPatcher-4.7.1.zip)

On issue 2: After reading the issue more carefully it is definitely not the same issue as #56 

Rather it looks like it is some special text handling of the Utage VN engine, especially as the original text name doesn't even appear.

**Comment by TokcDK** [comment]
There is working BepinEx 5 version but I temporary will move Bepinex files then and will test with ReiPatcher version.

**Comment by TokcDK** [comment]
Checked in couple games and it seems names now is translating even when bugged line in txt.

**Comment by gravydevsupreme** [comment]
The latest version (4.8.0) should have the fix applied. Please feel free to open a new issue in relation to the "parameter"-issue where you can provide some more details on the issue and how/where/what game to reproduce it in.
