### ISSUE TITLE
Translate Error??

### ISSUE THREAD

**Issue by LeePC** [bbepis/XUnity.AutoTranslator#69]
![111](https://user-images.githubusercontent.com/8704225/70016275-3928c280-15c3-11ea-9559-1bf7792f28aa.jpg)
![112](https://user-images.githubusercontent.com/8704225/70016276-3928c280-15c3-11ea-8869-ed20c0f9bbb1.jpg)
![113](https://user-images.githubusercontent.com/8704225/70016277-3928c280-15c3-11ea-98ce-ca2803e851df.jpg)

Text is broken and not translated
fix Please

**Comment by LeePC** [comment]
I used XUnity.AutoTranslator-ReiPatcher-4.7.1.zip

**Comment by gravydevsupreme** [comment]
You're going to have to provide me with some more information here.
 * Which game is it?
 * What languages are you trying to translate it to?

Without having looked at it yet, my guess would be that the problem here is that the font does not support the character set of the output language.

Potentially related issue(s): https://github.com/bbepis/XUnity.AutoTranslator/issues/57

**Comment by LeePC** [comment]
a game called resizeme
I want to translate it into Korean

**Comment by gravydevsupreme** [comment]
Took a look at the game. It is indeed the same issue as is reported in #57 

It does seem like the game recognizes the font resource `Fonts & Materials/LiberationSans SDF`, but that doesn't support Korean either.

This means that right now. There is no fix.

**Comment by gravydevsupreme** [comment]
Take a look at https://github.com/bbepis/XUnity.AutoTranslator/issues/57#issuecomment-562344581

**Comment by LeePC** [comment]
> Take a look at [#57 (comment)](https://github.com/bbepis/XUnity.AutoTranslator/issues/57#issuecomment-562344581)

Still can't translate

**Comment by gravydevsupreme** [comment]
It definitely works.

Make sure you download the auto translator version from the other issue (not official release), place the fonts in the game root and change the configuration parameter `OverrideFontTextMeshPro`, such that:

```
[Behaviour]
OverrideFontTextMeshPro=notosanscjk-regular_sdf
```

If you use ReiPatcher, make sure you run the setup file again.

**Comment by LeePC** [comment]
Still not

![114](https://user-images.githubusercontent.com/8704225/70333939-cef47400-1887-11ea-883e-4d2855f33fec.jpg)

**Comment by LeePC** [comment]
[Config.zip](https://github.com/bbepis/XUnity.AutoTranslator/files/3932831/Config.zip)

setting files

**Comment by gravydevsupreme** [comment]
Hard for me to judge what is going wrong.

Perhaps you can try with the version provided in https://github.com/bbepis/XUnity.AutoTranslator/issues/57#issuecomment-562770805 enable the console and tell me if any errors are reported.

**Comment by LeePC** [comment]
Please tell me how to fix the output_log.txt file you said

**Comment by gravydevsupreme** [comment]
Just enable to console in the Config.ini file for the auto translator. The ReiPatcher version of this plugin does not output anything to output_log.txt.

**Comment by gravydevsupreme** [comment]
Actually, he output_log.txt might also be interesting now that I think about it. You can find it here:

`C:\Users\{USERNAME}\AppData\LocalLow\MJ and Aoigai_\ResizeMe！`

**Comment by LeePC** [comment]
[output_log.txt](https://github.com/bbepis/XUnity.AutoTranslator/files/3935847/output_log.txt)

**Comment by gravydevsupreme** [comment]
Please try again with this version. I've only improved the diagnostics, but hopefully this will give me a more clear indication of what is going wrong.

[XUnity.AutoTranslator-ReiPatcher-4.7.1.zip](https://github.com/bbepis/XUnity.AutoTranslator/files/3936123/XUnity.AutoTranslator-ReiPatcher-4.7.1.zip)

**Comment by LeePC** [comment]
[output_log.txt](https://github.com/bbepis/XUnity.AutoTranslator/files/3937930/output_log.txt)

**Comment by djlaser** [comment]
Initialize engine version: 2018.3.4f1 (1d952368ca3a) plugin worker

**Comment by gravydevsupreme** [comment]
I assume you have renamed the font assetbundle to `fontasset` and placed it in the `AssetBundleData` directory.

You get the following error in the log `Unable to open archive file: AssetBundleData/fontasset`.

It indicates that it fails to load this asset bundle. I get the same error if asset bundle cannot be found.

If the font is placed there, then I really don't know what is going on. Perhaps you can send me your entire setup, game included.

**Comment by LeePC** [comment]
https://drive.google.com/open?id=1jL6mkhIhHdLT5NSZur9zQUyCbUh_bqWt


Delete this link one day later

**Comment by gravydevsupreme** [comment]
Downloaded it and removed the link.

**Comment by gravydevsupreme** [comment]
I would have loved it if you had included the way you had setup the translation plugin as well.

Anyway. After installing it in this version of the game it still works just fine for me.

Please try to copy the following zip into a **fresh copy** of the game. There should be one file conflict, and you should override that file.

https://www.mediafire.com/file/gt399ugaqrireyi/ReizeMe_Translation.zip/file

After that you can just run the game.

**Comment by LeePC** [comment]
Thank you for your help.

**Comment by gravydevsupreme** [comment]
I assume you got it working :)

In that case I will close the issue.
