### ISSUE TITLE
How I know If a game is made with Unity ?

### ISSUE THREAD

**Issue by FabioManoel1977** [bbepis/XUnity.AutoTranslator#71]
Sorry bad english

I am playing Chaos Dominas (https://vndb.org/v26508)  with XUnity.AutoTranslator and it is awesome. XUnity.AutoTranslator is a awesome software and the game runs smoothly 100% in english

Too bad only works with games made with unity 

How I know If a game is made with unity for me to use with XUnity.AutoTranslator ?

I guess this gameswas made with unity:
異世界に召喚された俺は寝取られスキル持ちだった!?
https://vndb.org/v24120

unfortunately XUnity.AutoTranslator-ReiPatcher-4.7.1 not worked, create the shortcut and all folders exactly like happened with Chaos Dominas but when I click in the shortcut, just nothing happens.

I guess https://vndb.org/v24120 is not a game made with unity unfortunatelly

Then how I know it ? exist a special dll that exist in all unity games ???

**Comment by Cerzs** [comment]
Most Unity games have a folder called _data
![imagen](https://user-images.githubusercontent.com/44489935/70347311-a85a1d00-1836-11ea-898b-05e4bb286352.png)

Inside are a lot of resources and folders, Managed and Mono are Unity default folders un most cases. 
![imagen](https://user-images.githubusercontent.com/44489935/70347414-dc354280-1836-11ea-9135-4c489cffc641.png)

**Comment by FabioManoel1977** [comment]
Thank you very much , is really easy for me from now on figure it out. Thank you very much
