### ISSUE TITLE
How do I get the text in a text box？

### ISSUE THREAD

**Issue by DogUoUo** [bbepis/XUnity.AutoTranslator#73]
hi，i'm china guy, english not good.
so sorry.
I have a problem, when I translate ai girl game, some interfaces have text boxes, but the plug-in does not get related text...
How do I fix it？
this is screenshot：https://i.niupic.com/images/2019/12/28/6cnw.PNG

**Comment by gravydevsupreme** [comment]
Greetings,

Texts that can be modified by users are generally blacklisted from translations because translating them often can result in highly undesirable and unpredictable behavior. For example:
 * Input fields getting translated while a user is typing.
 * False indication to the user of what has actually been written into an input field.

There isn't really a good solution to this that allows translating such fields while also preventing the above mentioned problems.

Let me try and answer your question with another question: Why do you believe it is important to translate such a textbox?

**Comment by DogUoUo** [comment]
Thank you, okay, I see what you mean.
I want to translate it because, in the game, some text boxes contain input prompts, maybe players can't understand the meaning of the prompts?
Or is there a better solution for longer words?
Or is it possible to translate only the input prompts, not the input text?
E.g:
Thank you, okay, I see what you mean.
I want to translate it because, in the game, some text boxes contain input prompts, maybe players can't understand the meaning of the prompts?
Or is there a better solution for longer words?
Or is it possible to translate only the input prompts, not the input text?
E.g:
![Branching](https://i.niupic.com/images/2019/12/29/6csf.PNG)

**Comment by gravydevsupreme** [comment]
If it is a placeholder text (prompt), like is the case here, and it is not translated, then I would consider that a bug. I will take a look to see if there is a way to hook just the placeholder text.

**Comment by DogUoUo** [comment]
okay。
but maybe that not a bug。
because in some where，can be get prompt。
like in ai girl game：
main menu：“new game”，then “create game”，then“world name”，there has a text input field，display english “No Name” prompt……
that “No Name” can be get with plugin…
but previous comment's image，there won't get it…
in game location is main menu：3rd menu(i forget name)，then upload or download，enter it(need japan network ip to connect)，and there show like my image…
i know my english is very very bad……
so much sorry……😂😂

**Comment by gravydevsupreme** [comment]
I made a fix to placeholder text. This is text that is displayed in a user input field that cannot be edited by the user, but disappears when the user starts typing.

I do not think there is anything reasonable that can be done about "pre-filled" input fields, though. It would be too hard to distinguish between when text should and should not be translated.

[XUnity.AutoTranslator-BepIn-5x-4.8.1-custom.zip](https://github.com/bbepis/XUnity.AutoTranslator/files/4009819/XUnity.AutoTranslator-BepIn-5x-4.8.1-custom.zip)

**Comment by DogUoUo** [comment]
it's works!
![Branching](https://i.niupic.com/images/2019/12/30/6cOE.PNG)
vey cool!
but i had another question, when i translation “Play Home”game, that game use unity 5.5.5.30182, when launch PlayHome32bit.exe into the game. and plugin only show like this:
![Branching](https://i.niupic.com/images/2019/12/30/6cOF.png)
it's always stay in "Queued translations", not doing "Server translations"...
i waiting long long time……won't change anthing.
i check AutoTranslatorConfig.ini, because if Endpoint=GoogleTranslate, it will stop.
if change to PapagoTranslate, that work fine.
at the same time copy identical AutoTranslatorConfig.ini to ai girl game or emotion creators,  still use GoogleTranslate, that work fine.
I confirmed it's not internet connection error.
i won't edit [Http] and [GoogleLegitimate] or other option. and LogOutput.log no any error message.

**Comment by DogUoUo** [comment]
by the way, i can't launch PlayHome64bit.exe to test plugin, this is my windows system with amd gpu problem……
so~ -_-!!

**Comment by gravydevsupreme** [comment]
When I try to run the 32-bit version it seems to work just fine.

I find that when translations requests never ends like this in Unity it is often related to problems with the old Mono's implementation of SSL, which causes the requests to just block forever and never complete.

Perhaps delegating the translation to a separate process might solve it. You can try one of the releases below, where I have tried to add a new endpoint (Google! Translate (Compat)).

This starts a new process to process the request instead. (Note: you may have to restart the game after changing endpoint to "unqueue" hung requests).

[XUnity.AutoTranslator-IPA-4.8.1-custom.zip](https://github.com/bbepis/XUnity.AutoTranslator/files/4010894/XUnity.AutoTranslator-IPA-4.8.1-custom.zip)
[XUnity.AutoTranslator-BepIn-5x-4.8.1-custom.zip](https://github.com/bbepis/XUnity.AutoTranslator/files/4010895/XUnity.AutoTranslator-BepIn-5x-4.8.1-custom.zip)

I don't know what your mod setup for PH is, but if you are asked whether to override 0Harmony.dll for IPA then **don't do it**.

**Comment by DogUoUo** [comment]
No, 4.8.1 bepin or ipa still not work.
i never use any mod plugin.
just download github bepin or ipa latest version, unpack and copy to game folder.
relaunch game many times...
my play home game version is 1.4, i install game from game disk, and update all official dlc and patch.
then start game, no use any other plugin……
maybe that's my computer problem? i use win10 ltsc, system install all microsoft update.
or maybe is game version problem.
 do you need my game folder PlayHome32bit_Data\Managed and Mono ect. all DLL file to copy you game folder test it's?
or you give me that folders dll file, i test it…………

**Comment by gravydevsupreme** [comment]
I have now released 4.8.1 which includes support for placeholder texts in input fields. Also includes the compatibility endpoint as it is useful in some games.
