### ISSUE TITLE
Why don't connect XunityWebclient normal http url?

### ISSUE THREAD

**Issue by dotoroi** [bbepis/XUnity.AutoTranslator#74]
I have a question about the CustomTranslate function.

The plug-in does not connect to the internal server even though all the conditions are met.

As a result of downloading and verifying the source, it was confirmed that URL was completed normally through String.Format, but no request came to the server through XunityWebRequest. It is a structure that sends a GET request to the server with untranslated sentences, but no request is made to the Python web server that accepts the connection through the web browser.

The lack of programming knowledge prevents us from verifying the Web connection.

I would like to check again with a simple Python web server to make sure the plug-in is working. Thank you.

**Comment by gravydevsupreme** [comment]
I find that the most common issue related to getting something like this working is related to Mono, which often comes with a poor implementation of SSL in older versions. Do you happen to be using https? If so this could be the issue. 

If this is not the case, I cannot say I have experienced problems getting it to work before.

Perhaps you could take look at [this](https://github.com/HelloKS/ezTransWeb), which I am told works. (NOTE: I have not tried this myself).

**Comment by dotoroi** [comment]
Thanks comment.

EzTransWeb python source I added a self-signed certificate and made the url accessible by https, and it worked.

After all, the fact that the connection by http does not work remains the same.

Thank you!
