### ISSUE TITLE
[Sands Of Salzaar] Translation not working

### ISSUE THREAD

**Issue by seelebrn** [bbepis/XUnity.AutoTranslator#75]
Hello everyone, 
I'd like to ask for your help regarding XUnity.AutoTranslator. 

I'm trying to use it with a game named Sands of Salzaar. 

I've tried the different installation methods (standalone / plugin) but none of them seem to work. BepinEx can't seem to generate a config file, ReiPatcher standalone doesn't seem to work either. 
I've read in the documentation and other messages in this Issues board that setting the parameter DisableCertificateValidation to "True" could help but the relevant config file doesn't seem to be generated. No "AutoTranslator" folder seems to be generated. Using BepinEx doesn't seem to generate a config.ini either. 

As you can probably tell, i'm a noob. I can provide any information needed.

Any help would be appreciated, and thanks for your work !

**Comment by gravydevsupreme** [comment]
Greetings

This plugin wont work in this game. Sands of Salzaar has been AOT compiled with something called IL2CPP.

Sometimes developers decide to compile their games using this strategy to gain marginal performance, but doing so comes at the cost of making it much harder to modify code at runtime, which this plugin relies on.

I am going to close this issue as there is no way this plugin will ever support IL2CPP. Sorry.

**Comment by gravydevsupreme** [comment]
This could be of interest.

https://github.com/bbepis/XUnity.AutoTranslator/issues/98
