### ISSUE TITLE
Problems with text size

### ISSUE THREAD

**Issue by DogUoUo** [bbepis/XUnity.AutoTranslator#79]
![Branching](https://i.niupic.com/images/2020/03/02/6XsQ.PNG)

**Why is the original Japanese text displayed after switching using Ctrl + T?

this is my AutoTranslatorConfig.ini：**
[Service]
Endpoint=GoogleTranslate

[General]
Language=zh-CN
FromLanguage=ja

[Files]
Directory=Translation\Text
OutputFile=Translation\Text\Generated.txt
SubstitutionFile=Translation\Text\Substitutions.txt
PreprocessorsFile=Translation\Text\Preprocessors.txt

[TextFrameworks]
EnableIMGUI=False
EnableUGUI=True
EnableNGUI=True
EnableTextMeshPro=True
EnableTextMesh=True
AllowPluginHookOverride=False

[Behaviour]
MaxCharactersPerTranslation=1000
IgnoreWhitespaceInDialogue=True
IgnoreWhitespaceInNGUI=True
MinDialogueChars=20
ForceSplitTextAfterCharacters=0
CopyToClipboard=False
MaxClipboardCopyCharacters=1000
EnableUIResizing=False
EnableBatching=True
UseStaticTranslations=False
OverrideFont=Microsoft YaHei
OverrideFontTextMeshPro=BepInEx\Translation\Font\chs2018221
ResizeUILineSpacingScale=
ForceUIResizing=False
IgnoreTextStartingWith=\u180e;
TextGetterCompatibilityMode=False
GameLogTextPaths=
RomajiPostProcessing=ReplaceMacronWithCircumflex;RemoveApostrophes
TranslationPostProcessing=ReplaceMacronWithCircumflex
ForceMonoModHooks=False
CacheRegexPatternResults=False
CacheRegexLookups=False
CacheWhitespaceDifferences=False
GenerateStaticSubstitutionTranslations=False
GeneratePartialTranslations=False
EnableTranslationScoping=False
EnableSilentMode=True
BlacklistedIMGUIPlugins=
EnableTextPathLogging=False
OutputUntranslatableText=False
IgnoreVirtualTextSetterCallingRules=False

[Texture]
TextureDirectory=Translation\Texture
EnableTextureTranslation=False
EnableTextureDumping=False
EnableTextureToggling=False
EnableTextureScanOnSceneLoad=False
EnableSpriteRendererHooking=False
LoadUnmodifiedTextures=False
DetectDuplicateTextureNames=False
DuplicateTextureNames=
EnableLegacyTextureLoading=False
TextureHashGenerationStrategy=FromImageName
CacheTexturesInMemory=True

[ResourceRedirector]
PreferredStoragePath=Translation\RedirectedResources
EnableTextAssetRedirector=False
LogAllLoadedResources=False
EnableDumping=False
CacheMetadataForAllFiles=True

[Http]
UserAgent=
DisableCertificateValidation=True

[TranslationAggregator]
Width=400
Height=100
EnabledTranslators=

[Debug]
EnableConsole=False

[Migrations]
Enable=True
Tag=4.9.0

[Baidu]
BaiduAppId=
BaiduAppSecret=
DelaySeconds=1

[BingLegitimate]
OcpApimSubscriptionKey=

[Custom]
Url=

[GoogleLegitimate]
GoogleAPIKey=

[LecPowerTranslator15]
InstallationPath=

[Watson]
Url=
Key=

[Yandex]
YandexAPIKey=

**Comment by DogUoUo** [comment]
in case
EnableUIResizing = False
Changing to True, this problem still occurs.

**Comment by gravydevsupreme** [comment]
I'm not sure I understand what the question/problem is.

Pressing ALT+T toggles the translation ON and OFF and enables/disables any text sizing modifications that has been applied.

`EnableUIResizing` simply tells the plugin to attempt to allow dialogs to have proper wrapping/size behaviour. It also enables any `resizer` configuration files that may be present in the translation directory.
