### ISSUE TITLE
Auto translator folder doesnt appear

### ISSUE THREAD

**Issue by Nergal777** [bbepis/XUnity.AutoTranslator#80]
Hello,

sry if there was some mistake I did that I havent realized yet, but I followed the instructions to install the reipatcher onto my unity game, the problem is everything is appearing as intended but the only thing missing is the autotranslator folder. 
I would like to know if there is maybe something already known about this issue or if there maybe is a way to resolve my issue.
Thanks you for your time.

**Comment by gravydevsupreme** [comment]
Greetings,

The AutoTranslator folder will be generated when you run the game.

**Comment by Nergal777** [comment]
I already ran my game  before but the folder didn't appear

**Comment by gravydevsupreme** [comment]
If the folder doesn't appear when you run the game, then the most common reason is that it has been AOT compiled with IL2CPP, which this plugin does not support.

You can confirm this yourself by opening the "{GameExeName}_Data" folder to see if you can find any files/folders named anything related to il2cpp.

If it does not have such files/folders in the "{GameExeName}_Data" directory then I would like to know what game it is. 

If it does have such files however, this plugin will never work with that game.

**Comment by Nergal777** [comment]
You're right it does have a folder with il2cpp. Thanks for answering me. 
But are there maybe any alternatives that i can use to machine translate the game or are games with the il2cpp file not translateable with a machine translator

**Comment by gravydevsupreme** [comment]
I guess it should be possible to hook these games with normal text hooking (AGTH, ITH, Textractor, VNR, etc.) and send such hooked text to a machine translator (Translation Aggregator, VNR, etc.) like any other native application.

In this regard I think Textractor is the new kid on the block. Here's an [issue dealing with IL2CPP games](https://github.com/Artikash/Textractor/issues/303) specifically.

However, I cannot guide you how to set something like this up correctly for IL2CPP games, as I don't know myself.

**Comment by AstralOceane** [comment]
I would like to translate Disney Dream Light Valley, but the game files are in il2cpp. How can I translate it?

**Comment by Lushy696** [comment]
I have the same problem, I follow the instructions but the autotranslator folder doesn't appear, I looked for some il2cpp folder/file but I didn't find anything.

game name: Yuukaku ni Urareta Ore no Kanojo

sorry for the bad English
