### ISSUE TITLE
Translator doesn't hook

### ISSUE THREAD

**Issue by spiritov0d** [bbepis/XUnity.AutoTranslator#87]
Hello. There is chinese game called 九霄缳神记 JIU XIAO, which has been released recently. It seems the game is using some kind of modified text module - and thus translator doesn't work (it doesn't even create config file). 
Could you please check it and tell, if it's possible to add support for the game or it's not worth it. You can get whole "managed" folder [link removed]. Also, text files are probably loaded from "StreamingAssets\AssetBundles\Assets\resources bundle\csv" path [link removed]. Thanks in advance.

**Comment by gravydevsupreme** [comment]
If the config file isn't even created then the plugin has never gotten a chance to initialize. 

Are you using BepInEx or the standalone ReiPatcher-based installer?

**Comment by spiritov0d** [comment]
I've tried both - latest ReiPatcher and latest stable/bleeding edge BepInEx versions. ReiPatcher installs without any errors and BepInEx produces this log in game folder: [preloader.log](https://drive.google.com/file/d/1CWzJ8HsIbl8dpSuevGY1D0WREVLedD_s/view?usp=sharing)

Thanks for explanation. I thought that the translator is using some default settings if config is not present (and because ReiPatcher patched files without noticable errors). It seems it's not translator's fault, but injector's. Should I close the issue then and open new one in BepInEx section?

**Comment by gravydevsupreme** [comment]
This log would suggest that BepInEx has trouble initializing. Can't really see why, though.

Do note that if you have tried both: The ReiPatcher-installer modifies and adds files to the Managed directory that must be removed for BepInEx to work properly.

Even so, I would still expect the ReiPatcher-installer to work (if used without BepInEx). If you installed it through ReiPatcher does it create the config file and/or can you show the UI (through ALT+0)?

**Comment by spiritov0d** [comment]
I'm aware of ReiPatcher modifying files, so I used BepInEx version with original unmodified files. And while ReiPatcher is seemingly patching files without errors in console, it doesn't create AutoTranslator folder or any other configs upon patching via "Patch and Run" shortcut (like it should). And in-game none of translator's hotkeys works (including UI), so I assume it doesn't hook properly.  
The game doesn't have any protection aside from usual steam check, but maybe it's checking integrity of some engine files? Though I can run the game with patched files just fine. Maybe there is a way to activate debug logs or something for ReiPatcher/BepInEx to narrow down the problem?

**Comment by gravydevsupreme** [comment]
I have taken a closer look at the managed directory. I think this may be a case of the developers having trimmed unused code away before publishing, which means that code BepInEx and this plugin relies on simply don't exist in the distributed runtime.

This is just a guess. I cannot test it myself, but when I compare the distributed framework assemblies (mscorlib, netstandard, System.Xxx) to distribution with other games targeting netstandard, I find that each one of them is much smaller and has less programming structures when inspected. 

Maybe it can be resolved by simply taking the assemblies from another game which also targets that same platform, but that has not been trimmed.

I had two games lying around that used netstandard. A Unity 2018.3 and Unity 2019.1 game.

As I cannot test it myself, perhaps you can try by overriding these files in the managed directory.

Not sure if other files needs to be replaced, but could be. Don't really know that much about this kinda of stuff.


[Managed-netstandard-2018.3.zip](https://github.com/bbepis/XUnity.AutoTranslator/files/4497372/Managed-netstandard-2018.3.zip)
[Managed-netstandard-2019.1.zip](https://github.com/bbepis/XUnity.AutoTranslator/files/4497373/Managed-netstandard-2019.1.zip)

Even if this makes it possible to initialize the plugin I still fear it might not work if specific unity constructs are referenced in the plugin that have been trimmed. For instance IMGUI constructs when it comes to the translator plugin.

**Comment by spiritov0d** [comment]
Thanks, it actually works, at least partially. Now AutoTranslator folder with config and all is properly created, but the translator doesn't work in-game (not even UI). I think you are right about other files, probably some UnityEngine.* should be replaced as well. I'll try to find a game with similar version, or maybe it'll be better to just create empty unity project with the same engine version (2018.4.5) and try to re-use some modules from it (especially IMGUI and TextCore). 
I'll report back when I find something out and test stuff. Thanks again for your help and all those updates for the translator.

**Comment by gravydevsupreme** [comment]
I suspect very much it work work if you did that. Make a project with correct version, target netstandard, include the required modules (not entirely sure how to do that), publish/build it and simply copy the DLLs in the Managed directory and override:
 * Mono.Security.dll
 * mscorlib.dll
 * netstandard.dll
 * System.*.dll
 * UnityEngine.*.dll

Doubt you would need to copy specialized packages such as Unity.*.dll (which are installed through their package manager)

**Comment by spiritov0d** [comment]
Yes, it worked. Translator now hooks and works as expected. Btw, default sample project in unity includes all required modules, so it was easier than I thought. Here are those compiled libraries, maybe you or someone else will need them (e.g. for references) - [link](https://drive.google.com/file/d/1nzEjy-pkxDOJOzEVEll3zrCdaaaeblQs/view?usp=sharing).

I really appreciate your help. If you don't have any further questions about this issue, you can close it, otherwise I'll close it by myself in a day.
