### ISSUE TITLE
Using number or names as variables

### ISSUE THREAD

**Issue by CALADARI** [bbepis/XUnity.AutoTranslator#88]
When playing RPG game there will be entries like:

```
防御消費MP-0%=MP cost on defending -0%
防御消費MP-5%=MP cost on defending -5%
ムニと仲良くなった=You are now a firend of ムニ
```

the basic text are same, only the name and number changes. Is there any way to make 'MP cost on defending' be const and the number be variables?

See, in current version , i could add `防御消費=MP cost on defending` in `_Substitutions.txt`. But in `_AutoGeneratedTranslations.txt` will need to be like:

```
{{A}}-0%={{A}}-0%
{{A}}-5%={{A}}-5%
```

Thus no much work reduced, but google translate 防御消費 compeletly wrong in my languague...
Maybe I'm just using it wrongly.Any suggestion and help will be appriciated. :v

**Comment by gravydevsupreme** [comment]
You can use a regex like so, to handle the number:

```
r:"^防御消費MP([\-\+]{1}[0-9]{0,2})%$"="Cost on defending $1%"
```

You can also use a splitting regex, like so, to handle and translate the name and text:

```
sr:"^([\w\s]+)と仲良くなった$"="You are now a friend of $1"
```

Note that I have not tested any of these specific regexes.

**Comment by CALADARI** [comment]
Wilco. Maybe I should really start learning regexes ...

**Comment by gravydevsupreme** [comment]
Just create a new txt file in the same directory as the other translation files and place them in that. It should not go into the the files starting with underscore (_) by default.

**Comment by gravydevsupreme** [comment]
Closed due to inactivity. Feel free to re-open if you find your problem has not been solved.
