### ISSUE TITLE
BaiduTranslate doesn't work for it uses jp rather than ja represents japanese

### ISSUE THREAD

**Issue by mint-aqrua** [bbepis/XUnity.AutoTranslator#89]

**Comment by gravydevsupreme** [comment]
Does this work?

(You still have to specify "ja" in the configuration)

[BaiduTranslate.zip](https://github.com/bbepis/XUnity.AutoTranslator/files/4536044/BaiduTranslate.zip)

**Comment by gravydevsupreme** [comment]
I'm going to need your help to test this as I cannot do so myself. So it would be greatly appreciated if you could tell me if this solves the problem.

**Comment by 2020-Ziyuan** [comment]
Hi, I think it still doesn't work. I know nothing about C# so I am not sure about the problem, but I sent you a temporary key with a C# demo through email

**Comment by gravydevsupreme** [comment]
Alright. You can send it to me at gravydev@protonmail.com

I'm not really sure why it would suddenly used "jp" rather than  "ja". Pretty sure it used "ja" in the past.

https://github.com/bbepis/XUnity.AutoTranslator/issues/2#issuecomment-386364744 (the entire translator plugin is based on the information provided in this one comment)
https://github.com/bbepis/XUnity.AutoTranslator/issues/2#issuecomment-386397606

Maybe they changed their API entirely and that's the problem?

**Comment by gravydevsupreme** [comment]
If you want this fixed, you're gonna have to help me out here. I am going to remove my mail in a couple of days. @2020-Ziyuan

**Comment by freetreer** [comment]
> If you want this fixed, you're gonna have to help me out here. I am going to remove my mail in a couple of days. @2020-Ziyuan

I  should already sent you an email on Apr 30th with app id and key

**Comment by gravydevsupreme** [comment]
Interesting. Could you try again? I have not received anything and cannot find anything in the spam folder either.

**Comment by freetreer** [comment]
> Interesting. Could you try again? I have not received anything and cannot find anything in the spam folder either.

Try this link anyway.
https://drive.google.com/file/d/1x3jJkJNzVhVuBVC4BLzthGLfLYv3CxLl/view?usp=sharing

**Comment by gravydevsupreme** [comment]
Thanks. Got it.

**Comment by gravydevsupreme** [comment]
Hello again @freetreer 

Sorry for the delay and silence. Been very busy with various things.

Anyway, I got it working with your key/id.

[BaiduTranslate.zip](https://github.com/bbepis/XUnity.AutoTranslator/files/4705559/BaiduTranslate.zip)

NOTE: That even though Baidu uses "jp" to indicate Japanese, you must still use "ja" as the from language. And the following monikers are supported for Chinese: "zh". "zh-CN", "zh-TW", "zh-Hans", "zh-Hant".

Made this way to have some consistency across different translators.

**Comment by freetreer** [comment]
> Hello again @freetreer @2020-Ziyuan
> 
> Sorry for the delay and silence. Been very busy with various things.
> 
> Anyway, I got it working with your key/id.
> 
> [BaiduTranslate.zip](https://github.com/bbepis/XUnity.AutoTranslator/files/4705559/BaiduTranslate.zip)
> 
> NOTE: That even though Baidu uses "jp" to indicate Japanese, you must still use "ja" as the from language. And the following monikers are supported for Chinese: "zh". "zh-CN", "zh-TW", "zh-Hans", "zh-Hant".
> 
> Made this way to have some consistency across different translators.

Yes, it works. Thank you!

**Comment by gravydevsupreme** [comment]
This issue should now be fixed in 4.11.3, which has just been released.
