### ISSUE TITLE
Hooking up text issue

### ISSUE THREAD

**Issue by JackN01** [bbepis/XUnity.AutoTranslator#91]
Would it be possible to somehow hook up or manualy translate text such as this:
" <color=#ff6347><闇強化>闇属性のスキル威力増加　…5％</color> "
" <color=#000000><賢者>消費ＭＰ減少　　　　　　　…8％</color> "
It doesnt show up in _AutoGeneratedTranslations and I was able to catch it using other text hooker.

**Comment by gravydevsupreme** [comment]
I am not sure why that text specifically would not be caught by the plugin. The plugin should have no problem picking up any text, even if it has markup.

To help you I would need a way to reproduce the issue on my end.

**Comment by JackN01** [comment]
The title is Gears of Dragoon 2 ~Reimei no Fragments~
https://vndb.org/v17988
Here is the shop site at which you can download a trial version (体験版ダウンロード)(881.36MB)
https://www.dlsite.com/pro/work/=/product_id/VJ010100.html

The text in question shows up in character screen at enchancements list, although I just tried it for trial version and it works fine.
