### ISSUE TITLE
Multiple Languages

### ISSUE THREAD

**Issue by Grentari** [bbepis/XUnity.AutoTranslator#92]
Is it possible to translate two languages, the game has both English and Japanese text.

Adding lines of a language that is not used in the plug-in settings file to the "_auto Generated Translations" file manually successfully replaces the game text with a second language, but I would like to automate entry in "_auto Generated Translations" second language.

**Comment by gravydevsupreme** [comment]
Greetings,

Supporting multiple input languages is certainly something I have considered, but it does require the translator used to be able to determine input language itself, which some can (to some degree) and others cant.

I might look into supporting it for select endpoints. Been putting off a release of this plugin for a while, so maybe I can put this feature into that.
