### ISSUE TITLE
Questions about not being able to access Google in China

### ISSUE THREAD

**Issue by youke-haoa** [bbepis/XUnity.AutoTranslator#97]
“Translate.google.com” cannot be accessed in China , but “translate.google.cn” can be used normally .
Using translate.google.com to get TKK will not work in China. Set Language=zh.CN then Use the following modifications can fix this problem.

Will you consider fixing this problem?

thank you, and look forward to your reply!

![image](https://user-images.githubusercontent.com/1960585/85122078-94b55780-b258-11ea-89a3-655adfd4f327.png)

**Comment by gravydevsupreme** [comment]
Hello,

I have implemented support for specifying an alternative service backend for google in the following version.

Note, that it is not implemented like your example above. You must keep using zh-CN as the output language, and you must specify the following configuration in the config file:

```ini
[Google]
ServiceUrl=https://translate.google.cn
```

Could you verify if this works?

**Comment by youke-haoa** [comment]
Hi,

I used release 4.11.3 for testing, It can be used in China. 
Setting Language=zh-TW or Language=zh-CN can translate normally.

Thank you for fixing this problem, Looking forward to its release!
